- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- CHANGELOG.md
- README.md
- docs/commands/PSRule/en-US/Invoke-RuleEngine.md
- docs/keywords/PSRule/en-US/about_PSRule_Keywords.md
- Updates to readme and module documentation
> Documentation updates

- .gitignore
- .platyps.yml
- .vscode/launch.json
- .vscode/settings.json
- .vscode/tasks.json
- PSRule.build.ps1
- PSRule.sln
- ThirdPartyNotices.txt
- appveyor.yml
- azure-pipelines.yml
- scripts/vstsbuild.ps1
- src/PSRule/PSRule.csproj
- src/PSRule/PSRule.psd1
- Use Azure DevOps for build
- Updates to module project files and CI process
> CI process update

- docs/concepts/PSRule/en-US/about_PSRule_Options.md
- docs/concepts/PSRule/en-US/about_PSRule_Variables.md
- src/PSRule/Commands/AssertAllOfCommand.cs
- src/PSRule/Commands/AssertAnyOfCommand.cs
- src/PSRule/Commands/AssertExistsCommand.cs
- src/PSRule/Commands/AssertMatchCommand.cs
- src/PSRule/Commands/AssertTypeOfCommand.cs
- src/PSRule/Commands/AssertWithinCommand.cs
- src/PSRule/Commands/LanguageBlock.cs
- src/PSRule/Commands/LanguageBlockCommand.cs
- src/PSRule/Commands/NewRuleDefinitionCommand.cs
- src/PSRule/Commands/RuleKeyword.cs
- src/PSRule/Commands/RuleLanguageNouns.cs
- src/PSRule/Commands/SetPSRuleHintCommand.cs
- src/PSRule/Host/Host.cs
- src/PSRule/Host/HostHelper.cs
- src/PSRule/Host/LanguageContext.cs
- src/PSRule/Pipeline/GetRulePipeline.cs
- src/PSRule/Pipeline/IRulePipeline.cs
- src/PSRule/Pipeline/InvokeRulePipeline.cs
- src/PSRule/Pipeline/RulePipeline.cs
- src/PSRule/Rules/Rule.cs
- src/PSRule/Rules/RuleBlock.cs
- src/PSRule/Rules/RuleConditionResult.cs
- src/PSRule/Rules/RuleFilter.cs
- tests/PSRule/FromFile.Rule.ps1
- tests/PSRule/PSRule.Common.Tests.ps1
- tests/PSRule/Rules/appService.Rule.ps1
- tests/PSRule/Rules/common.Rule.ps1
- tests/PSRule/Rules/storageAccounts.Rule.ps1
- Documentation and comment updates
> Pre-release module update 02

- PSRule.build.ps1
- README.md
- docs/commands/PSRule/en-US/PSRule.md
- src/PSRule/PSRule.csproj
- src/PSRule/PSRule.psm1
- Switch to native .NET Standard
- Add module page
> Pre-release module update 03

- PSRule.build.ps1
- azure-pipelines.yml
- scripts/vstsbuild.ps1
- Updates to CI process to handle passing version number down to release pipeline
> Updated build name for release pipeline

- CHANGELOG.md
- README.md
- ThirdPartyNotices.txt
- docs/scenarios/install-instructions.md
> Pre-release 01

- docs/keywords/PSRule/en-US/about_PSRule_Keywords.md
> Fix documentation link

- CHANGELOG.md
> v0.1.0-B181222 release

- PSRule.build.ps1
- azure-pipelines.yml
- scripts/pipeline-build.ps1
- Updates to build and release processes for module publishing
Fixes #15
> Update CI process for release publishing #15

- PSRule.build.ps1
- Fix build script check for NuGetApiKey
> Fix build script issue

- CHANGELOG.md
> Pre-release v0.1.0-B181235

- CHANGELOG.md
- Update change log for pre-release
> Pre-release 0.2.0-B19010501

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/PULL_REQUEST_TEMPLATE.md
- .vscode/settings.json
- README.md
- Add PR template
- Update bug report
- Fix readme typo
- Add VSCode editing settings
> Update GitHub documentation

- CHANGELOG.md
- Update to change log for pre-release 0.2.0-B190113
> Pre-release 0.2.0-B190113

- README.md
- docs/concepts/PSRule/en-US/about_PSRule_Variables.md
- docs/keywords/PSRule/en-US/about_PSRule_Keywords.md
- docs/scenarios/azure-tags/azure-tags.md
- docs/scenarios/azure-tags/azureTags.Rule.ps1
- src/PSRule/Host/Host.cs
- src/PSRule/Host/RuntimeRule.cs
- src/PSRule/Pipeline/PipelineContext.cs
- tests/PSRule.Tests/FromFile.Rule.ps1
- Update configuration variable to `$Configuration` from `$Rule.Configuration`
- Update Azure tag validation documentation
Fixes #27 
> Update name of configuration variable

- CHANGELOG.md
- Updated change log for release
> Pre-release v0.2.0-B190120

- CHANGELOG.md
> Update change log for v0.2.0-B190121

- docs/scenarios/azure-tags/PSRule.yaml
- docs/scenarios/azure-tags/azure-tags.md
- Grammatical corrections for azure-tags scenario documentation
> Update azure-tags scenario with minor corrections

- CHANGELOG.md
- Update change log for v0.2.0 release
> Update change log for v0.2.0

- PSRule.build.ps1
- docs/commands/PSRule/en-US/toc.yml
- Update CI pipeline to clean up old temp paths
- Update cmdlet TOC to include Test-PSRuleTarget
> Update pipeline and cmdlet toc

- azure-pipelines.yml
- Bump Azure DevOps pipeline version to 0.3.0 for new builds
> Post v0.2.0

- CHANGELOG.md
- src/PSRule/PSRule.psm1
- Added online help links to keywords #72
Fixes #72 
> Added online help links to keywords

- .vscode/settings.json
- CHANGELOG.md
- PSRule.build.ps1
- README.md
- schemas/PSRule-options-0.2.0.schema.json
- Added schema for PSRule options #74
Fixes #74
> Add schema for PSRule options #74

- .vscode/settings.json
- CHANGELOG.md
- README.md
- docs/commands/PSRule/en-US/Invoke-PSRule.md
- docs/commands/PSRule/en-US/Test-PSRuleTarget.md
- docs/concepts/PSRule/en-US/about_PSRule_Options.md
- schemas/PSRule-options-0.3.0.schema.json
- src/PSRule/Common/YamlConverters.cs
- src/PSRule/Configuration/InputOption.cs
- src/PSRule/Configuration/PSRuleOption.cs
- src/PSRule/PSRule.psm1
- src/PSRule/Pipeline/InvokeRulePipelineBuilder.cs
- src/PSRule/Pipeline/PipelineReciever.cs
- src/PSRule/Pipeline/PipelineStream.cs
- tests/PSRule.Tests/InputFormatDeserializerTests.cs
- tests/PSRule.Tests/ObjectFromFile.yaml
- tests/PSRule.Tests/ObjectFromFileNested.yaml
- tests/PSRule.Tests/ObjectPathTests.cs
- tests/PSRule.Tests/PSRule.Common.Tests.ps1
- tests/PSRule.Tests/PSRule.Tests.csproj
- tests/PSRule.Tests/PSRule.Tests.yml
Support nested TargetObjects #77
Fixes #77 
> Support nested TargetObjects #77

- CHANGELOG.md
- Update change log for pre-release
> Pre-release for v0.3.0-B190208

- CHANGELOG.md
> Pre-release for 0.3.0-B190224

- CHANGELOG.md
> Pre-release v0.3.0-B190231

- CHANGELOG.md
- src/PSRule/Pipeline/PipelineReciever.cs
- tests/PSRule.Tests/PSRule.Common.Tests.ps1
- Added support for input deserialization from FileInfo objects #95
Fixes #95 
> Add support for input deserialization from FileInfo objects #95

- CHANGELOG.md
- PSRule.build.ps1
- docs/commands/PSRule/en-US/Get-PSRule.md
- docs/commands/PSRule/en-US/Invoke-PSRule.md
- docs/commands/PSRule/en-US/Test-PSRuleTarget.md
- src/PSRule/PSRule.psm1
- **Breaking change** - Changed parameter alias for `-Path` from `-f` to `-p` #99
> Change -Path parameter alias from -f to -p #99

- azure-pipelines.yml
> Update pipeline version to v0.4.0

- README.md
- docs/scenarios/install-instructions.md
- Added references and links to VSCode extension
> Add reference to VSCode extension

- CHANGELOG.md
- Update change log for pre-release.
> Pre-release v0.4.0-B190313

- CHANGELOG.md
- src/PSRule/Common/JsonConverters.cs
- src/PSRule/Common/YamlConverters.cs
- tests/PSRule.Tests/FromFile.Rule.ps1
- tests/PSRule.Tests/InputFormatDeserializerTests.cs
- tests/PSRule.Tests/ObjectFromFile.json
- tests/PSRule.Tests/ObjectFromFile.yaml
- tests/PSRule.Tests/ObjectFromFile2.yaml
- tests/PSRule.Tests/PSRule.Common.Tests.ps1
- Fix incorrect JSON de-serialization of nested arrays. #109
Fixes #109
> Fix deserialization of nested JSON arrays #109

- CHANGELOG.md
- Update change log for pre-release.
> Pre-release v0.4.0-B190320

- .gitignore
- PSRule.sln
- azure-pipelines.yml
- tests/PSRule.Tests/PSRule.Tests.csproj
- Add SonarCloud integration to pipeline
> Add SonarCloud to CI pipeline

- CHANGELOG.md
> Pre-release v0.4.0-B190328

- CHANGELOG.md
- src/PSRule/Runtime/ObjectHelper.cs
- tests/PSRule.Tests/FromFile.Rule.ps1
- tests/PSRule.Tests/PSRule.Exists.Tests.ps1
- Fix null reference exception when traversing null field #123
Fixes #123 
> Fix null reference exception when traversing null field #123

- CHANGELOG.md
- PSRule.build.ps1
- azure-pipelines.yml
- Update pipeline build version
- Fix missing help topics for options and variables #125
Fixes #125 
> Post v0.4.0 pipeline update

- CHANGELOG.md
- README.md
> Pre-release v0.5.0-B190405

- CHANGELOG.md
- README.md
- azure-pipelines.yml
- docs/commands/PSRule/en-US/Get-PSRule.md
- docs/commands/PSRule/en-US/Invoke-PSRule.md
- docs/commands/PSRule/en-US/New-PSRuleOption.md
- docs/commands/PSRule/en-US/Test-PSRuleTarget.md
- docs/scenarios/validation-pipeline/file.Rule.ps1
- docs/scenarios/validation-pipeline/validation-pipeline.md
- src/PSRule/Configuration/OutputFormat.cs
- src/PSRule/PSRule.psd1
- src/PSRule/PSRule.psm1
- src/PSRule/Pipeline/InvokeResult.cs
- src/PSRule/Pipeline/InvokeRulePipeline.cs
- src/PSRule/Pipeline/NUnit3Serializer.cs
- src/PSRule/Pipeline/PipelineContext.cs
- src/PSRule/Pipeline/PowerShellPipelineStream.cs
- src/PSRule/Rules/RuleRecord.cs
- src/PSRule/en-AU/PSRule.Resources.psd1
- src/PSRule/en-US/PSRule.Resources.psd1
- tests/PSRule.Tests/PSRule.EndToEnd.Tests.ps1
- Added validation pipeline scenario.
- Added `-OutputFormat NUnit3` to `Invoke-PSRule` return NUnit formatted output. #129
Fixes #129 
> Add NUnit output format and validation #129

- README.md
- docs/commands/PSRule/en-US/Invoke-PSRule.md
- docs/commands/PSRule/en-US/Test-PSRuleTarget.md
- Minor updates/ corrections to documentation.
> Minor updates to documentation pre-v0.5.0

- .vscode/tasks.json
- PSRule.build.ps1
- docs/commands/PSRule/en-US/Get-PSRule.md
- docs/commands/PSRule/en-US/Invoke-PSRule.md
- docs/commands/PSRule/en-US/New-PSRuleOption.md
- docs/commands/PSRule/en-US/Test-PSRuleTarget.md
- docs/concepts/PSRule/en-US/about_PSRule_Options.md
- docs/docfx.json
- Update cmdlet online links.
- Minor doc corrections.
- Update CI script.
> Updates to build and documentation pre-v0.5.0

- CHANGELOG.md
- docs/commands/PSRule/en-US/New-PSRuleOption.md
- docs/commands/PSRule/en-US/Set-PSRuleOption.md
- docs/concepts/PSRule/en-US/about_PSRule_Options.md
- src/PSRule/Configuration/PSRuleOption.cs
- src/PSRule/PSRule.psm1
- tests/PSRule.Tests/PSRule.Options.Tests.ps1
- Improve handling of default YAML options file. #137
Fixes #137 
> Improve handling of default YAML options file #137

- CHANGELOG.md
- Updated change log for release.
> Pre-release v0.5.0-B190423

- CHANGELOG.md
- src/PSRule/Pipeline/NUnit3Serializer.cs
- tests/PSRule.Tests/NUnit.Schema.xsd
- tests/PSRule.Tests/PSRule.Common.Tests.ps1
- Fix schema conformance of `-OutputFormat NUnit3` to NUnit report schema. #141
Fixes #141 
> Fix schema conformance for NUnit3 #141

- azure-pipelines.yml
- Update CI pipeline version number.
> Post v0.5.0 pipeline update

- docs/commands/PSRule/en-US/toc.yml
- docs/index.md
- docs/scenarios/install-instructions.md
- Update reference table of contents.
- Update index with badges.
- Update install instructions.
> Update docs and reference toc

- .vscode/settings.json
- CHANGELOG.md
- src/PSRule/Host/Host.cs
- Fix operation is not supported on this platform failure. #152
Fixes #152 
> Fix operation not supported error #152

- .vscode/settings.json
- CHANGELOG.md
- src/PSRule/PSRule.psm1
- src/PSRule/Pipeline/InputPathBuilder.cs
- tests/PSRule.Tests/ObjectFromFile2.json
- tests/PSRule.Tests/PSRule.Common.Tests.ps1
- Fix FullName cannot be found on this object error. #149
Fixes #149 
> Fix FullName cannot be found on this object error #149

- CHANGELOG.md
> Pre-release v0.6.0-B190514

- PSRule.build.ps1
- src/PSRule.Benchmark/PSRule.Benchmark.csproj
- src/PSRule.Benchmark/PSRule.cs
- src/PSRule.Benchmark/Program.cs
- src/PSRule/Annotations/BlockMetadata.cs
- src/PSRule/Pipeline/NUnit3Serializer.cs
- src/PSRule/Pipeline/PipelineReciever.cs
- src/PSRule/Pipeline/PowerShellPipelineStream.cs
- src/PSRule/Rules/TagSet.cs
- tests/PSRule.Tests/PSRule.Tests.csproj
- Bump dependency versions.
- Code cleanup.
> Update dependencies and cleanup

- CHANGELOG.md
> Pre-release v0.6.0-B190614

- CHANGELOG.md
- pipeline.build.ps1
- Fix CI process does not use tag as module version.
> Fix CI tag versioning

- pipeline.build.ps1
- Update module versioning process and output.
> Update CI module versioning

- CHANGELOG.md
> Pre-release v0.6.0-B190627

- .azure-pipelines/azure-pipelines.yaml
- Updated pipeline version to v0.7.0.
> Post v0.6.0 pipeline update

- docs/commands/PSRule/en-US/PSRule.md
- docs/index.md
> Updated TOC

- README.md
- docs/scenarios/azure-tags/azure-tags.md
- docs/scenarios/fruit/isFruit.Rule.ps1
- docs/scenarios/kubernetes-resources/kubernetes-resources.md
- docs/scenarios/validation-pipeline/validation-pipeline.md
- Update README.md to make usage of `.Rule.ps1` files clearer. #179 
- Update older samples to reflect recent module changes.
> README example update

- .azure-pipelines/azure-pipelines.yaml
- CHANGELOG.md
- Updated change log for release.
- Update GitHub release.
> Pre-release v0.7.0-B190613

- .azure-pipelines/azure-pipelines.yaml
- Update stage condition to not progress to release if build failure.
> Add stage condition for success

- CHANGELOG.md
> Pre-release v0.7.0-B190624

- docs/commands/PSRule/en-US/Invoke-PSRule.md
- docs/scenarios/azure-resources/azure-resources.md
- src/PSRule/en-AU/PSRule.Resources.psd1
- src/PSRule/en-GB/PSRule.Resources.psd1
- src/PSRule/en-US/PSRule.Resources.psd1
-  Update documentation relating to #195 #182
> Update documentation relating to #195 #182

- CHANGELOG.md
> Pre-release v0.7.0-B190633

- CHANGELOG.md
> Pre-release v0.7.0-B190652

- docs/commands/PSRule/en-US/Invoke-PSRule.md
- docs/concepts/PSRule/en-US/about_PSRule_Docs.md
- docs/concepts/PSRule/en-US/about_PSRule_Variables.md
- docs/keywords/PSRule/en-US/about_PSRule_Keywords.md
- src/PSRule/PSRule.psd1
- src/PSRule/PSRule.psm1
- Minor documentation updates.
- Export `$LocalizedData` variable.
> Minor documentation updates and export LocalizedData variable

- CHANGELOG.md
- src/PSRule/Rules/RuleConditionResult.cs
- tests/PSRule.Tests/FromFile.Rule.ps1
- tests/PSRule.Tests/PSRule.Common.Tests.ps1
- Improve handling of null rule result. #224
Fixes #224 
> Improve handling of null rule result #224

- CHANGELOG.md
> Pre-release v0.7.0-B190664

- .azure-pipelines/azure-pipelines.yaml
- Increase CI pipeline version.
> Post v0.7.0 pipeline update

- CHANGELOG.md
- Updated change log for release.
> Pre-release v0.8.0-B190708

- docs/keywords/PSRule/en-US/about_PSRule_Keywords.md
- Fix documented support for `Write-Debug`.
> Minor doc updates to correct support for Write-Debug

- schemas/PSRule-options.schema.json
- Update options schema for `Wide` output format. #200
> Update schema for Wide output format #200

- CHANGELOG.md
- docs/keywords/PSRule/en-US/about_PSRule_Keywords.md
- src/PSRule/Commands/AssertAllOfCommand.cs
- src/PSRule/Commands/AssertAnyOfCommand.cs
- src/PSRule/Commands/AssertExistsCommand.cs
- src/PSRule/Commands/AssertMatchCommand.cs
- src/PSRule/Commands/AssertTypeOfCommand.cs
- src/PSRule/Commands/AssertWithinCommand.cs
- src/PSRule/Commands/InvokeRuleBlockCommand.cs
- src/PSRule/Commands/LanguageBlock.cs
- src/PSRule/Commands/LanguageKeywords.cs
- src/PSRule/Commands/NewRuleDefinitionCommand.cs
- src/PSRule/Commands/RuleKeyword.cs
- src/PSRule/Commands/WriteReasonCommand.cs
- src/PSRule/Commands/WriteRecommendCommand.cs
- src/PSRule/Host/Host.cs
- src/PSRule/Host/HostHelper.cs
- src/PSRule/Pipeline/ExecutionScope.cs
- src/PSRule/Pipeline/PipelineContext.cs
- src/PSRule/Resources/PSRuleResources.Designer.cs
- src/PSRule/Resources/PSRuleResources.resx
- tests/PSRule.Tests/FromFile.Rule.ps1
- tests/PSRule.Tests/PSRule.Exists.Tests.ps1
- tests/PSRule.Tests/PSRule.Match.Tests.ps1
- tests/PSRule.Tests/PSRule.TypeOf.Tests.ps1
- tests/PSRule.Tests/PSRule.Within.Tests.ps1
- Add detection for improper keyword use. #203
Fixes #203 
> Add detection for improper keyword use. #203

- CHANGELOG.md
- src/PSRule/PSRule.psm1
- tests/PSRule.Tests/PSRule.Common.Tests.ps1
- Automatically load rule modules based on preference variable. #218
Fixes #218 
> Automatically load rule modules #218

- .azure-pipelines/azure-pipelines.yaml
- .gitignore
- .vscode/extensions.json
- pipeline.build.ps1
- src/PSRule.Benchmark/PSRule.Benchmark.csproj
- src/PSRule/PSRule.csproj
- tests/PSRule.Tests/PSRule.PSGallery.Tests.ps1
- tests/PSRule.Tests/PSRule.Tests.csproj
- Updated PowerShell SDK version to 6.2.2.
> Update dependencies for test and benchmark

- CHANGELOG.md
- docs/keywords/PSRule/en-US/about_PSRule_Keywords.md
- src/PSRule.Benchmark/PSRule.cs
- src/PSRule.Benchmark/Program.cs
- src/PSRule/PSRule.psm1
- src/PSRule/Rules/RuleBlock.cs
- src/PSRule/Rules/RuleHelper.cs
- tests/PSRule.Tests/PSRule.Common.Tests.ps1
- tests/PSRule.Tests/TestModule2/TestModule2.psd1
- tests/PSRule.Tests/TestModule2/rules/Rule1.Rule.ps1
- tests/PSRule.Tests/TestModule2/rules/Rule2.Rule.ps1
- tests/PSRule.Tests/TestModule3/TestModule3.psd1
- tests/PSRule.Tests/TestModule3/rules/Module3.Rule.ps1
- Use rule references consistent with cmdlet fully qualified syntax. #217
Fixes #217 
> Use consistent rule references #217

- ThirdPartyNotices.txt
- Updated ThirdPartyNotices.txt with Manatee.Json license.
> Add Manatee.Json license

- README.md
- docs/concepts/PSRule/en-US/about_PSRule_Assert.md
- docs/scenarios/fruit/fruit-example.ps1
- docs/scenarios/fruit/isFruit.Rule.ps1
- Minor documentation updates.
> Update examples and assert docs

- CHANGELOG.md
- ThirdPartyNotices.txt
- src/PSRule/Host/HostHelper.cs
- src/PSRule/Pipeline/PipelineContext.cs
- tests/PSRule.Tests/FromFile.Rule.ps1
- tests/PSRule.Tests/PSRule.Common.Tests.ps1
- Fix rule synopsis comment capture. #214
Fixes #214 
> Fix synopsis comment capture #214

- CHANGELOG.md
- Fix module reloading with different versions. #254
- Fix not finding rules in current path by default. #256
- Fix rule synopsis comment capture. #214
> Pre-release v0.8.0-B190806

- .azure-pipelines/azure-pipelines.yaml
- .markdownlint.json
> Update CI pipeline version v0.9.0

- CHANGELOG.md
- src/PSRule/Host/HostHelper.cs
- src/PSRule/Rules/RuleConditionResult.cs
- tests/PSRule.Tests/PSRule.Common.Tests.ps1
- Fix outcome reported when error or exception is raised. #211
Fixes #211 
> Fix outcome reporting on error #211

- src/PSRule/Common/JsonConverters.cs
- src/PSRule/Parser/TokenStream.cs
- src/PSRule/Pipeline/GetRuleHelpPipelineBuilder.cs
- src/PSRule/Pipeline/GetRulePipelineBuilder.cs
- src/PSRule/Pipeline/InvokeRulePipelineBuilder.cs
- src/PSRule/Pipeline/PipelineBuilder.cs
- src/PSRule/Pipeline/PipelineExeception.cs
- src/PSRule/Pipeline/PipelineSerializationException.cs
- src/PSRule/Pipeline/RuleParseException.cs
- src/PSRule/Pipeline/RuleRuntimeException.cs
- src/PSRule/Resources/PSRuleResources.Designer.cs
- src/PSRule/Resources/PSRuleResources.resx
- src/PSRule/Rules/RuleOutcome.cs
- Minor code quality updated. Only refactoring, no changes to functionality.
> Minor code quality updates

- ps-project.yaml
- Added project metadata file.
> Add project metadata

- CHANGELOG.md
- ps-project.yaml
- Improve feedback of parsing errors. #185
- Fix outcome reported when error or exception is raised. #211
> Pre-release v0.9.0-B190810

- docs/index.md
- Added reference to PSRule.Rules.Azure module in index page.
> Added PSRule.Rules.Azure to index

- CHANGELOG.md
- docs/keywords/PSRule/en-US/about_PSRule_Keywords.md
- src/PSRule.Benchmark/Benchmark.Within.Rule.ps1
- src/PSRule.Benchmark/PSRule.Benchmark.csproj
- src/PSRule.Benchmark/PSRule.cs
- src/PSRule/Commands/AssertWithinCommand.cs
- src/PSRule/Pipeline/PipelineContext.cs
- src/PSRule/Resources/PSRuleResources.Designer.cs
- src/PSRule/Resources/PSRuleResources.resx
- tests/PSRule.Tests/FromFile.Rule.ps1
- tests/PSRule.Tests/PSRule.Within.Tests.ps1
- Added support for a wildcard match using the `Within` keyword. #272
Fixes #272 
> Within with wildcard match #272

- .azure-pipelines/azure-pipelines.yaml
- docs/commands/PSRule/en-US/toc.yml
- pipeline.build.ps1
- Update TOC for documentation.
- Increase CI pipeline version to v0.10.0.
- Bump PSScriptAnalyzer version to v1.18.3.
> Updated docs TOC and post v0.9.0

- src/PSRule/Commands/NewRuleDefinitionCommand.cs
- src/PSRule/Common/JsonConverters.cs
- src/PSRule/Common/YamlConverters.cs
- src/PSRule/Configuration/PSRuleOption.cs
- src/PSRule/Host/HostHelper.cs
- src/PSRule/Parser/TokenStream.cs
- src/PSRule/Pipeline/PipelineConfigurationException.cs
- src/PSRule/Pipeline/PipelineExeception.cs
- src/PSRule/Pipeline/PipelineSerializationException.cs
- src/PSRule/Pipeline/RuleParseException.cs
- src/PSRule/Pipeline/RuleRuntimeException.cs
- src/PSRule/Rules/ISpec.cs
- src/PSRule/Rules/RuleBlock.cs
- src/PSRule/Rules/TagSet.cs
- src/PSRule/Runtime/ObjectHelper.cs
- Refactoring to clean up comments and improve quality. No functional changes.
> Code quality refactoring post v0.9.0

- .azure-pipelines/azure-pipelines.yaml
- Add code coverage for Sonar.
> Collect coverage reports for Sonar

- .azure-pipelines/azure-pipelines.yaml
- pipeline.build.ps1
- Package module in `.nupkg` within pipeline.
> Add NuGet package to CI

- CHANGELOG.md
- Added assertion helper for checking field default value. #289
> Pre-release v0.10.0-B1910011

- .azure-pipelines/azure-pipelines.yaml
- pipeline.build.ps1
- Fix CI upload of module NuGet package.
> Fix CI uploading NuGet

- .azure-pipelines/azure-pipelines.yaml
- Fix update of GitHub release task CI for V1.
> Fix update of GitHub release CI task for V1

- CHANGELOG.md
- Fix `Get-PSRuleHelp` -Online in constrained language mode. #296
- Added `Assert-PSRule` cmdlet to improve integration into CI processes. #290
- Added `Output.Style` option to support output in the following styles:
- Client/ Plain - Output returns easy to read log of rule pass/ fail.
- Azure Pipelines - Report rule failures as errors collected by Azure Pipelines.
- GitHub Actions - Reports rule failures as errors collected by GitHub Actions.
> Pre-release v0.10.0-B1910025

- docs/concepts/PSRule/en-US/about_PSRule_Options.md
- docs/scenarios/validation-pipeline/validation-pipeline.md
-Update options and pipeline examples.
> Update option and pipeline examples

- .azure-pipelines/azure-pipelines.yaml
> Update CI post v0.10.0

- .azure-pipelines/azure-pipelines.yaml
- .github/CODEOWNERS
- .github/PULL_REQUEST_TEMPLATE.md
- CHANGELOG.md
- CONTRIBUTING.md
- README.md
- docs/commands/PSRule/en-US/Assert-PSRule.md
- docs/commands/PSRule/en-US/Get-PSRule.md
- docs/commands/PSRule/en-US/Get-PSRuleBaseline.md
- docs/commands/PSRule/en-US/Get-PSRuleHelp.md
- docs/commands/PSRule/en-US/Invoke-PSRule.md
- docs/commands/PSRule/en-US/New-PSRuleOption.md
- docs/commands/PSRule/en-US/PSRule.md
- docs/commands/PSRule/en-US/Set-PSRuleOption.md
- docs/commands/PSRule/en-US/Test-PSRuleTarget.md
- docs/concepts/PSRule/en-US/about_PSRule_Assert.md
- docs/concepts/PSRule/en-US/about_PSRule_Docs.md
- docs/concepts/PSRule/en-US/about_PSRule_Options.md
- docs/concepts/PSRule/en-US/about_PSRule_Variables.md
- docs/index.md
- docs/keywords/PSRule/en-US/about_PSRule_Keywords.md
- docs/scenarios/validation-pipeline/validation-pipeline.md
- docs/toc.yml
- ps-project.yaml
- src/PSRule/PSRule.csproj
- src/PSRule/PSRule.psd1
- src/PSRule/PSRule.psm1
- tests/PSRule.Tests/TestModule/en-AU/M1.Rule1.md
- tests/PSRule.Tests/TestModule/en-US/M1.Rule1.md
- Updates to documentation to point to new Microsoft/PSRule location.
Fixes #307
> Update links after repo migration #307

- src/PSRule.Benchmark/PSRule.cs
- src/PSRule/Common/PSObjectExtensions.cs
- src/PSRule/Common/YamlConverters.cs
- src/PSRule/Configuration/BindingOption.cs
- src/PSRule/Configuration/OutputOption.cs
- src/PSRule/Configuration/PSRuleOption.cs
- src/PSRule/Parser/MarkdownReader.cs
- src/PSRule/Parser/MarkdownStream.cs
- src/PSRule/Parser/MarkdownToken.cs
- src/PSRule/Parser/MarkdownTokenExtensions.cs
- src/PSRule/Parser/RuleLexer.cs
- src/PSRule/Parser/RuleModels.cs
- src/PSRule/Parser/TokenStream.cs
- src/PSRule/Pipeline/AssertPipeline.cs
- src/PSRule/Pipeline/InvokeRulePipeline.cs
- src/PSRule/Pipeline/PipelineReciever.cs
- src/PSRule/Rules/RuleSource.cs
- src/PSRule/Rules/RuleSuppressionFilter.cs
- src/PSRule/Runtime/ObjectHelper.cs
- Code clean up only, no functional changes.
> Code quality improvements

- CHANGELOG.md
- Fixed null reference exception when bound property is null. #323
> Pre-release v0.11.0-B1911002

- .github/labeler.yml
- .github/workflows/labeler.yaml
- Add labeler workflow action for PRs.
> Add labeler workflow action

- .azure-pipelines/azure-pipelines.yaml
- Update pipeline version for CI.
> Update pipeline version post v0.11.0

- .github/labeler.yml
- CHANGELOG.md
- src/PSRule/Pipeline/NUnit3OutputWriter.cs
- tests/PSRule.Tests/PSRule.Common.Tests.ps1
- Fixed NUnit serialization issue for unprocessed rules. #332
Fixes #332 
> Fix NUnit serialization issue #332

- src/PSRule.Benchmark/PSRule.Benchmark.csproj
- src/PSRule/Common/DictionaryExtensions.cs
- src/PSRule/Common/PSObjectExtensions.cs
- src/PSRule/PSRule.csproj
- src/PSRule/Pipeline/PipelineBuilder.cs
- src/PSRule/Pipeline/TestPipeline.cs
- src/PSRule/Runtime/AssertResult.cs
- src/PSRule/Runtime/ObjectHelper.cs
- tests/PSRule.Tests/PSRule.Tests.csproj
- Updated dependency versions for .NET Core SDK and packages.
- Refactor to reduce complexity of some methods. No functional change.
> Update dependency versions and refactor

- docs/keywords/PSRule/en-US/about_PSRule_Keywords.md
- src/PSRule/PSRule.psm1
- Fix exists help and function stub. #331
> Fixed Exists help and function stub #331

- CHANGELOG.md
- Fixed NUnit serialization issue for unprocessed rules. #332
- Added `-All` option to `Exists` keyword. #331
> Pre-release v0.12.0-B1911013

- .github/ISSUE_TEMPLATE/feature_request.md
- CONTRIBUTING.md
- SECURITY.md
> Update OSS docs

- CHANGELOG.md
- src/PSRule/Pipeline/PipelineBuilder.cs
- Fixed key has already been added for default baseline. #349
Fixes #349 
> Fixed key for default baseline #349

- .azure-pipelines/azure-pipelines.yaml
- Update CI version post v0.12.0.
> Update CI post v0.12.0

- CHANGELOG.md
- Improves output logging and formatting for Assert-PSRule. #357
- Formatting now includes errors and warnings using style.
- Added PSRule banner with module information.
- Added rule success summary.
> Pre-release v0.13.0-B1912012

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- build.ps1
- docs/scenarios/install-instructions.md
- Updates to documentation for contributing to PSRule.
> Update to contributing docs

- CHANGELOG.md
- docs/concepts/PSRule/en-US/about_PSRule_Variables.md
- src/PSRule/Runtime/Configuration.cs
- tests/PSRule.Tests/AssertTests.cs
- tests/PSRule.Tests/ConfigurationTests.cs
- Added configuration helper for strings arrays. #363 
Fixes #363 
> Add configuration helper for strings arrays #363

- CHANGELOG.md
- src/PSRule/Commands/NewRuleDefinitionCommand.cs
- src/PSRule/Host/HostHelper.cs
- src/PSRule/Pipeline/GetBaselinePipeline.cs
- src/PSRule/Pipeline/GetRuleHelpPipeline.cs
- src/PSRule/Pipeline/GetRulePipeline.cs
- src/PSRule/Pipeline/InvokeRulePipeline.cs
- src/PSRule/Pipeline/PipelineBuilder.cs
- src/PSRule/Rules/RuleHelpInfo.cs
- src/PSRule/Runtime/LocalizedData.cs
- tests/PSRule.Tests/FromFile.Rule.ps1
- tests/PSRule.Tests/PSRule.Common.Tests.ps1
- tests/PSRule.Tests/PSRule.Variables.Tests.ps1
- tests/PSRule.Tests/TestModule/en/M1.Rule1.md
- tests/PSRule.Tests/en/PSRule-rules.psd1
- Added support for using a parent culture in rule help. #316
Fixes #316 
> Added support for parent cultures #316

- CHANGELOG.md
- docs/concepts/PSRule/en-US/about_PSRule_Variables.md
- src/PSRule/Rules/RuleRecord.cs
- src/PSRule/Runtime/PSRule.cs
- tests/PSRule.Tests/FromFile.Rule.ps1
- tests/PSRule.Tests/PSRule.Variables.Tests.ps1
- Added custom rule data to results. #322
Fixes #322 
> Add rule custom data #322

- CHANGELOG.md
- Added configuration helper for strings arrays. #363
- Added support for using a parent culture in rule help. #316
- Rule help will use parent culture when a more specific culture is not available.
- Added custom rule data to results. #322
- `$PSRule.Data` can be used to set custom data during rule execution that is included in output.
- See `about_PSRule_Variables` for usage details.
> Pre-release v0.13.0-B1912027

- README.md
- docs/scenarios/rule-docs/rule-docs.md
- docs/scenarios/rule-module/Enterprise.Rules/Enterprise.Rules.psd1
- docs/scenarios/rule-module/rule-module.md
- Added detailed instructions on how to package rules in modules.
> Added module packaging docs

- .ps-rule/OpenSource.Rule.ps1
- Update `OpenSource.Community` to include `CODE_OF_CONDUCT.md` and `README.md`.
> Update OSS rules with additional required files

- docs/scenarios/rule-module/rule-module.md
- docs/scenarios/validation-pipeline/azure-pipelines.yaml
- docs/scenarios/validation-pipeline/file.Rule.ps1
- docs/scenarios/validation-pipeline/pipeline-deps.ps1
- docs/scenarios/validation-pipeline/validate-files.ps1
- docs/scenarios/validation-pipeline/validation-pipeline.md
- Updated CI docs to used prefer `Assert-PSRule` instead of `Invoke-PSRule`.
> Update CI docs with Assert-PSRule

- README.md
- docs/features.md
- docs/scenarios/validation-pipeline/validation-pipeline.md
- Update docs with corrections and additional formatting.
- Added FAQ.
> Doc quality updates and added FAQ

- CHANGELOG.md
- src/PSRule/Common/JsonConverters.cs
- tests/PSRule.Tests/InputFormatDeserializerTests.cs
- tests/PSRule.Tests/ObjectFromFileSingle.json
- tests/PSRule.Tests/PSRule.Tests.csproj
- Fixed JSON de-serialization fails with single object. #379
- Fixed stack overflow when parsing malformed JSON. #380
Fixes #379 
Fixes #380 
> Fixed JSON parsing issues #379 #380

- .azure-pipelines/azure-pipelines.yaml
- Updated CI pipeline version.
> Update CI pipeline post v0.13.0

- docs/index.md
- Add a link to PSRule.Rules.Kubernetes which just reached v0.1.0.
> Add link to PSRule.Rules.Kubernetes

- docs/features.md
- Update features with doc corrections.
> Doc quality updates

- docs/commands/PSRule/en-US/New-PSRuleOption.md
- docs/commands/PSRule/en-US/Set-PSRuleOption.md
- docs/concepts/PSRule/en-US/about_PSRule_Options.md
- Added documentation for options parameters.
> Updated docs for option parameters #395

- src/PSRule/Common/DictionaryExtensions.cs
- src/PSRule/Pipeline/AssertPipeline.cs
- src/PSRule/Pipeline/BaselineContext.cs
- src/PSRule/Runtime/ObjectHelper.cs
- Code refactoring to reduce duplication. No functional changes.
> Code quality updates

- .azure-pipelines/azure-pipelines.yaml
- Updated CI pipeline version to v0.15.0.
> Update CI pipeline post v0.14.0

- CHANGELOG.md
- pipeline.build.ps1
- src/PSRule/Pipeline/PipelineBuilder.cs
- tests/PSRule.Tests/PSRule.Common.Tests.ps1
- tests/PSRule.Tests/en/FromFile1.md
- Fix parent culture unwind with POSIX. #414
Fixes #414 
> Fix parent culture unwind with POSIX #414

- CHANGELOG.md
- Fix parent culture unwind with POSIX. #414
> Pre-release v0.15.0-B2002005

- README.md
- Add related projects to readme.
> Add links for related projects

- .azure-pipelines/azure-pipelines.yaml
- .azure-pipelines/jobs/test.yaml
- .azure-pipelines/jobs/testContainer.yaml
- .azure-pipelines/pipeline-deps.ps1
- .vscode/settings.json
- pipeline.build.ps1
- src/PSRule/PSRule.csproj
- tests/PSRule.Tests/PSRule.Tests.csproj
- Added PowerShell 7.0 to CI pipeline. #391 
- Separated out pipeline in to additional stages and improved performance.
- Added check for secrets.
Fixes #391
> Added PowerShell 7.0 to CI pipeline

- CHANGELOG.md
- Added `-ResultVariable` to store results from Assert-PSRule into a variable. #412
> Pre-release v0.15.0-B2002019

- .azure-pipelines/azure-pipelines.yaml
- Updated CI version to v0.16.0.
> Post v0.15.0 CI update

- .azure-pipelines/azure-pipelines.yaml
- Updated CI pipeline to PS 7.0 GA image. #438
Fixes #438
> Update CI pipeline tests to use PS 7.0 GA image

- CHANGELOG.md
- README.md
- docs/commands/PSRule/en-US/New-PSRuleOption.md
- docs/commands/PSRule/en-US/Set-PSRuleOption.md
- docs/concepts/PSRule/en-US/about_PSRule_Options.md
- pipeline.build.ps1
- schemas/PSRule-options.schema.json
- src/PSRule/Configuration/PSRuleOption.cs
- src/PSRule/PSRule.psm1
- tests/PSRule.Tests/PSRule.Common.Tests.ps1
- tests/PSRule.Tests/PSRule.Options.Tests.ps1
- tests/PSRule.Tests/PSRule.Tests.yml
- tests/PSRule.Tests/PSRule.Tests2.yml
- Added configuration option `Output.Culture` for setting culture. #442
Fixes #442 
> Added configuration option for culture #442

- docs/concepts/PSRule/en-US/about_PSRule_Options.md
- Fix culture option example.
- Other minor markdown formatting changes.
> Fix culture option example

- CHANGELOG.md
- Added configuration option `Output.Culture` for setting culture. #442
- Improved handling of fields to allow the input object to be referenced with `.`. #437
- Bug fixes:
- Fixed numeric comparison assertion with non-int types. #436
> Pre-release v0.16.0-B2003022

- CHANGELOG.md
- src/PSRule/Configuration/PSRuleOption.cs
- src/PSRule/PSRule.psm1
- src/PSRule/Pipeline/PipelineBuilder.cs
- src/PSRule/Pipeline/PipelineWriter.cs
- src/PSRule/Pipeline/PipelineWriterExtensions.cs
- src/PSRule/Pipeline/RulePipeline.cs
- src/PSRule/Resources/PSRuleResources.Designer.cs
- src/PSRule/Resources/PSRuleResources.resx
- tests/PSRule.Tests/PSRule.Common.Tests.ps1
- tests/PSRule.Tests/PipelineTests.cs
- tests/PSRule.Tests/TestWriter.cs
- Fixed output culture option ignored. #449
Fixes #449 
> Fixed output culture option ignored #449

- CHANGELOG.md
- Bug fixes:
- Fixed output culture option ignored. #449
> Pre-release v0.16.0-B2003027

- .azure-pipelines/azure-pipelines.yaml
- Updated CI pipeline post v0.16.0 release.
> Post v0.16.0 CI update

- src/PSRule/Pipeline/PipelineBuilder.cs
> Minor code clean up post v0.16.0

- src/PSRule.Benchmark/PSRule.Benchmark.csproj
- src/PSRule/Host/Host.cs
- src/PSRule/PSRule.csproj
- src/PSRule/Pipeline/Output/NUnit3OutputWriter.cs
- src/PSRule/Pipeline/Output/WideOutputWriter.cs
- src/PSRule/Pipeline/PipelineContext.cs
- Minor code refactoring and clean up. No functional changes.
- Updated dependencies for `Manatee.Json`, `BenchmarkDotNet` and `BenchmarkDotNet.Diagnostics.Windows`.
> Refactor and code clean up

- README.md
- docs/scenarios/install-instructions.md
- Added documentation links for Azure Pipelines extension.
> Add Azure Pipelines extension links

- CHANGELOG.md
- Improved `Assert-PSRule` output formatting.
- Added recommendation and reasons for `Client` and `Plain` styles. #456
- Added support for configuration of default module options. #459
- `binding` and `configuration` options can be set to a default value.
- Updated `New-PSRuleOption` parameter sets and help based on updates to module config.
- Added support for module fallback culture. #441
- Bug fixes:
- Fixed resource schema to include `useQualifiedName` and `nameSeparator` option. #458
> Pre-release v0.17.0-B2005010

- .azure-pipelines/azure-pipelines.yaml
- Update CI pipeline to v0.18.0.
> Update CI pipeline post v0.17.0 release

- docs/index.md
- Added Azure DevOps extension to docs.
> Added Azure Pipelines extension to docs

- CHANGELOG.md
- src/PSRule/Pipeline/AssertPipeline.cs
- Fixed recommendation output with client style. #467
Fixes #467 
> Fixed recommendation output with client style #467

- CHANGELOG.md
- Improved `Assert-PSRule` output formatting. #472
- Added recommendation and reasons for `AzurePipelines` and `GitHubActions` styles.
- Summary line is has been updated to include synopsis instead of reasons.
- Bug fixes:
- Fixed binding with ModuleConfig. #468
- Fixed recommendation output with client style. #467
> Pre-release v0.18.0-B2005015

- .azure-pipelines/azure-pipelines.yaml
- Update CI pipeline version to v0.19.0 post release.
> Update CI post v0.18.0

- .azure-pipelines/azure-pipelines.yaml
- .azure-pipelines/jobs/test.yaml
- Add PS 7.1 preview to unit tests.
- Add tests for Windows 2019.
> Add PS 7.1 preview to unit tests

- .devcontainer/devcontainer.json
- Add Codespaces settings file.
> Add Codespaces settings file

- docs/concepts/PSRule/en-US/about_PSRule_Options.md
- docs/features.md
- docs/scenarios/install-instructions.md
- Added FAQs for ignoring a rule and setting options.
- Minor updates to other FAQ and install instruction docs.
Fixes #482
> Add ignore rule FAQ #482

- src/PSRule.Benchmark/PSRule.Benchmark.csproj
- src/PSRule/PSRule.csproj
- src/PSRule/Runtime/Assert.cs
- tests/PSRule.Tests/PSRule.Tests.csproj
- Updated package dependencies for `Microsoft.PowerShell.SDK`, `Manatee.Json`, `Microsoft.NET.Test.Sdk` and `xunit.runner.visualstudio`.
> Update package dependencies

- CHANGELOG.md
- Bug fixes:
- Fixed `Csv` output format with summary for `Invoke-PSRule`. #486
> Pre-release v0.19.0-B2006018

- README.md
- Added readme link to GitHub Actions project _ps-rule_.
> Added link to ps-rule GitHub Actions project

- CHANGELOG.md
- Bug fixes:
- Fixed unable to read properties for .NET `DynamicObject`. #491
- Fixed read of JSON input format with null array item. #490
> Pre-release v0.19.0-B2006027

- CHANGELOG.md
- README.md
- src/PSRule/PSRule.csproj
- src/PSRule/PSRule.psd1
What's changed since v0.18.0:
- Bug fixes:
- Fixed unable to read properties for .NET `DynamicObject`. #491
- Fixed read of JSON input format with null array item. #490
- Fixed `Csv` output format with summary for `Invoke-PSRule`. #486
> Release v0.18.1

- pipeline.build.ps1
- Add option to force publish patch releases.
> Add force publish for patch releases

- src/PSRule/Commands/AssertAnyOfCommand.cs
- src/PSRule/Commands/AssertExistsCommand.cs
- src/PSRule/Commands/AssertMatchCommand.cs
- src/PSRule/Configuration/KeyMapDictionary.cs
- src/PSRule/Pipeline/Exceptions.cs
- src/PSRule/Pipeline/Output/NUnit3OutputWriter.cs
- src/PSRule/Pipeline/PipelineBuilder.cs
- src/PSRule/Runtime/Assert.cs
- src/PSRule/Runtime/ObjectHelper.cs
- src/PSRule/Runtime/Rule.cs
- src/PSRule/Runtime/SemanticVersion.cs
- Improvements to code quality, no functional changes.
> Clean up and improve code quality

- .azure-pipelines/azure-pipelines.yaml
- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
- README.md
- docs/concepts/PSRule/en-US/about_PSRule_Assert.md
- docs/concepts/PSRule/en-US/about_PSRule_Docs.md
- docs/concepts/PSRule/en-US/about_PSRule_Options.md
- docs/concepts/PSRule/en-US/about_PSRule_Variables.md
- docs/index.md
- docs/keywords/PSRule/en-US/about_PSRule_Keywords.md
- docs/scenarios/rule-docs/en-US/metadata.Name.md
- docs/scenarios/rule-docs/rule-docs.md
- docs/scenarios/rule-module/Enterprise.Rules/en/Org.Az.Resource.Tagging.md
- docs/scenarios/rule-module/Enterprise.Rules/en/Org.Az.Storage.UseHttps.md
- docs/scenarios/validation-pipeline/validation-pipeline.md
- src/PSRule/PSRule.csproj
- src/PSRule/PSRule.psd1
- Updated references to point to default main branch.
> Updated default branch to main

- CHANGELOG.md
- Added `Reason` method to assertion results. #500
- This new method, streamlines setting custom reasons particularly with formatted strings.
- The `Reason` method replaces any previously set reasons with a custom string.
- Optional arguments can be provided to be included in string formatting.
- Improvements to assertion methods.
- Added regular expression assertion helpers `Match`, and `NotMatch`. #502
- Added collection assertion helpers `In`, and `NotIn`. #501
- Added module version constraints. #498
- The module versions that PSRule uses can be constrained.
- Bug fixes:
- Fixed styling for no rule files warning with `Assert-PSRule`. #484
- Fixed actual value in reason for numeric comparison assertion method. #505
> Pre-release v0.19.0-B2007023

- README.md
- docs/docfx.json
- docs/index.md
- docs/scenarios/azure-resources/azure-resources.md
- docs/scenarios/index.md
- docs/scenarios/toc.yml
- docs/scenarios/validation-pipeline/validation-pipeline.md
- docs/toc.yml
- pipeline.build.ps1
- Updated documentation build process for using main branch.
- General improvements to documentation including linking to scenarios.
> Update docs build and links to scenarios

- docs/scenarios/install-instructions.md
- Minor updates to install instructions.
> Updated install instructions

- .github/dependabot.yml
- Added configuration for dependabot. #508 
Fixes #508
> Enable dependabot dependency updates #508

- .azure-pipelines/azure-pipelines.yaml
> Update CI pipeline to v0.20.0

- CHANGELOG.md
What's changed since v0.19.0:
- Added support for scanning repository files. #524
- Added `File` input type (`-InputType File`) to scan for files without deserializing them.
- Added `Input.PathIgnore` option to ignore files.
- When using the `File` input type path specs in `.gitignore` are ignored.
- Added `Get-PSRuleTarget` cmdlet to read input files and return raw objects. #525
- This cmdlet can be used to troubleshoot PSRule input issues.
> Pre-release v0.20.0-B2008002

- .github/dependabot.yml
- CHANGELOG.md
- src/PSRule/Common/YamlConverters.cs
- src/PSRule/Configuration/PSRuleOption.cs
- src/PSRule/Host/HostHelper.cs
- src/PSRule/PSRule.csproj
- src/PSRule/Pipeline/Output/YamlOutputWriter.cs
- src/PSRule/Pipeline/PipelineReciever.cs
- Bump YamlDotNet dependency to v8.1.2. #439
Fixes #439 
> Bump YamlDotNet dependency to v8.1.2 #439

- CHANGELOG.md
What's changed since pre-release v0.20.0-B2008010:
- Added file assertion helpers `FileHeader`, and `FilePath`. #534
- `FileHeader` checks for a comment header in the file.
- `FilePath` checks that a file path, optionally with suffixes exist.
- Engineering:
- Warn when deprecated `$Rule` properties are used. #536
- Bug fixes:
- Fixed out of bounds exception when empty markdown documentation is used. #516
- Fixed lines breaks in `RepositoryInfo` target name with git ref. #538
> Pre-release v0.20.0-B2009007

- CHANGELOG.md
What's changed since pre-release v0.20.0-B2009007:
- Added automatic binding for Rule object. #542
- Bug fixes:
- Fixed `InputFileInfo` `Type` property causes downstream binding issues. #541
> Pre-release v0.20.0-B2009013

- .azure-pipelines/azure-pipelines.yaml
- Update CI pipeline version to v0.21.0.
> Update CI pipeline version to v0.21.0

- CHANGELOG.md
- docs/concepts/PSRule/en-US/about_PSRule_Assert.md
- src/PSRule/Runtime/Assert.cs
- tests/PSRule.Tests/AssertTests.cs
- Numerical strings can be converted with numeric assertion helpers. #550
Fixes #550 
> Convert numerical strings #550

- CHANGELOG.md
What's changed since v0.20.0:
- Added support for formatting results as markdown. #474
- Use `-OutputFormat Markdown` or configure `Output.Format` to output markdown.
- To format as either detail or summary, use the `-As` parameter or configure `Output.As`.
- Numerical strings can be converted with numeric assertion helpers. #550
- Added outcome `Output.Outcome` as a configurable option. #552
> Pre-release v0.21.0-B2009006

- LICENSE
- README.md
- SECURITY.md
- SUPPORT.md
- pipeline.build.ps1
- src/PSRule/PSRule.csproj
- src/PSRule/PSRule.psd1
- Added support information.
- Updated project files.
- Minor corrections to other community files.
> Add SUPPORT.md

- CHANGELOG.md
What's changed since pre-release v0.21.0-B2009006:
- Added character case assertion helpers `IsLower`, and `IsUpper`. #555
- `IsLower` checks that all letters in a field value are lowercase.
- `IsUpper` checks that all letters in a field value are uppercase.
- Bug fixes:
- Fixed NUnit report reasons should be escaped in markdown. #471
> Pre-release v0.21.0-B2009016

- CHANGELOG.md
- schemas/PSRule-language.schema.json
- schemas/PSRule-options.schema.json
- Added help links and default snippets to schemas. #561
Fixes #561
> Added links and default snippets to schemas #561

- CHANGELOG.md
- docs/keywords/PSRule/en-US/about_PSRule_Keywords.md
- src/PSRule/Commands/InvokeRuleBlockCommand.cs
- src/PSRule/Commands/NewRuleDefinitionCommand.cs
- src/PSRule/Host/HostHelper.cs
- src/PSRule/Host/RuleLanguageAst.cs
- src/PSRule/PSRule.psm1
- src/PSRule/Pipeline/Exceptions.cs
- src/PSRule/Pipeline/RunspaceContext.cs
- src/PSRule/Resources/PSRuleResources.Designer.cs
- src/PSRule/Resources/PSRuleResources.resx
- src/PSRule/Rules/RuleBlock.cs
- tests/PSRule.Tests/FromFileParseError.Rule.ps1
- tests/PSRule.Tests/FromFileWithError.Rule.ps1
- tests/PSRule.Tests/PSRule.Common.Tests.ps1
- Fixed reporting of error when rule error is handled. #564
- Fixed first exception stops other rules from being processed. #566
Fixes #564 
Fixes #566 
> Fixed rule error handling issues #564 #566

- CHANGELOG.md
- Minor additional to change log.
> Added additional info to change log

- CHANGELOG.md
What's changed since pre-release v0.21.0-B2010003:
- Improved rule error reporting by including rule and source location. #565
> Pre-release v0.21.0-B2010010

- .azure-pipelines/azure-pipelines.yaml
> Update CI pipeline version to v0.22.0

- .azure-pipelines/azure-pipelines.yaml
- Update ubuntu image version.
- Added alpine container image.
> Update CI container images

- README.md
- docs/features.md
- docs/index.md
- docs/install-instructions.md
- src/PSRule/PSRule.csproj
- src/PSRule/PSRule.psd1
> Minor documentation update

- CHANGELOG.md
- src/PSRule.Benchmark/PSRule.cs
- src/PSRule/Commands/NewRuleDefinitionCommand.cs
- src/PSRule/Definitions/ModuleConfig.cs
- src/PSRule/Definitions/SpecFactory.cs
- src/PSRule/Host/DependencyGraphBuilder.cs
- src/PSRule/Host/HostHelper.cs
- src/PSRule/Host/IDependencyTarget.cs
- src/PSRule/PSRule.psm1
- src/PSRule/Pipeline/HostContext.cs
- src/PSRule/Pipeline/Output/HostPipelineWriter.cs
- src/PSRule/Pipeline/PipelineBuilder.cs
- src/PSRule/Pipeline/RulePipeline.cs
- src/PSRule/Pipeline/RunspaceContext.cs
- src/PSRule/Pipeline/SourcePipeline.cs
- src/PSRule/Rules/Rule.cs
- src/PSRule/Rules/RuleBlock.cs
- tests/PSRule.Tests/BaselineTests.cs
- tests/PSRule.Tests/ConfigTests.cs
- tests/PSRule.Tests/ConfigurationTests.cs
- tests/PSRule.Tests/PSRule.Common.Tests.ps1
- tests/PSRule.Tests/PipelineTests.cs
- Improved support for cross module rule dependencies. #248
- Rule dependencies are now automatically imported.
Fixes #248 
> Support for cross module rule dependencies #248

- CHANGELOG.md
What's changed since v0.21.0:
- Added `HasFields` assertion helper to check all fields exist. #578
- Updated `HasField` to check if any of the specified fields exist. #578
- Input format detection now includes `.jsonc` and `.markdown` file extensions. #575
- Improved support for cross module rule dependencies. #248
- Rule dependencies are now automatically imported.
- Bug fixes:
- Fixed handling for null or empty arrays with `StartsWith`, `Contains`, `EndsWith`, `In`, and `NotIn`. #579
> Pre-release v0.22.0-B2010014

- .azure-pipelines/azure-pipelines.yaml
> Bump CI version to v1.0.0

- .azure-pipelines/azure-pipelines.yaml
- .github/dependabot.yml
- docs/install-instructions.md
- Updated CI pipeline for PowerShell 7.1 release.
> Update CI for PowerShell 7.1 release

- .azure-pipelines/azure-pipelines.yaml
- tests/PSRule.Tests/PSRule.Tests.csproj
- tests/PSRule.Tests/PipelineTests.cs
- Added additional C# unit tests for options.
> Added additional options tests

- CHANGELOG.md
- Updated change log to reflect previous dependabot update. #591
> Add Manatee.Json reference to change log

- src/PSRule.Benchmark/PSRule.cs
- src/PSRule/Common/DictionaryExtensions.cs
- src/PSRule/Common/YamlConverters.cs
- src/PSRule/Configuration/BaselineOption.cs
- src/PSRule/Configuration/PSRuleOption.cs
- src/PSRule/Definitions/Baseline.cs
- src/PSRule/Pipeline/GetRulePipeline.cs
- src/PSRule/Pipeline/GetTargetPipeline.cs
- src/PSRule/Pipeline/SourcePipeline.cs
- Code quality improvements, no functional changes.
> General code clean up

- .azure-pipelines/azure-pipelines.yaml
> Fix release pipeline

- pipeline.build.ps1
- Fixes release version number for v1.
> Fix release version number

- docs/CHANGELOG-v1.md
- src/PSRule/Pipeline/SourcePipeline.cs
- Fixed module source key has already been added. #608
Fixes #608 
> Module source key has already been added #608

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/PULL_REQUEST_TEMPLATE.md
> Improve GitHub templates

- docs/CHANGELOG-v1.md
What's changed since v1.0.0:
- Bug fixes:
- Fixed module source key has already been added. #608
> Release v1.0.1

- .azure-pipelines/azure-pipelines.yaml
- Bumped CI pipeline version after release.
> Bump pipeline version to 1.1.0

- .github/ISSUE_TEMPLATE/question.md
- README.md
- SUPPORT.md
- docs/index.md
- docs/install-instructions.md
- Updated external project references.
- Updates support to point to discussion for questions.
> Update external project references

- docs/CHANGELOG-v1.md
What's changed since v1.0.1:
- Engineering:
- Bump Manatee.Json from 13.0.4 to 13.0.5. #619
- Bug fixes:
- Fixed `GetContent` processing of `InputFileInfo`. #625
- Fixed null reference of rule reason with wide output. #626
- Fixed markdown help handling of include code blocks with `[`. #627
- Fixed markdown help inclusion of fenced code blocks in notes and description. #628
> Release v1.0.2

- docs/CHANGELOG-v1.md
What's changed since v1.0.2:
- Bug fixes:
- Fixed reason reported fields for `HasField` and `HasFields` assertion helpers. #632
> Release v1.0.3

- docs/CHANGELOG-v1.md
What's changed since v1.0.3:
- Added type assertion helpers. #635
- Added `IsNumeric` to check field value is a numeric types.
- Added `IsInteger` to check field value is an integer types.
- Added `IsBoolean` to check field value is a boolean.
- Added `IsArray` to check field value is an array.
- Added `IsString` to check field value is a string.
- Added `TypeOf` to check field value is a specified type.
- Added content helpers. #637
- Added `$PSRule.GetContentFirstOrDefault` to get content and return the first object.
- Added `$PSRule.GetContentField` to get the field from content objects.
- Updated `HasJsonSchema` assertion helper. #636
- The URI scheme can optionally be ignored for `http://` or `https://` URIs.
- The fragment `#` is ignored.
> Pre-release v1.1.0-B2102019

- docs/CHANGELOG-v1.md
What's changed since pre-release v1.1.0-B2102019:
- Added assertion helpers. #640
- Added `NotHasField` to check object does not have any of the specified fields.
- Added `Null` to check field value is null.
- Added `NotNull` to check field value is not null.
> Pre-release v1.1.0-B2102024

- docs/CHANGELOG-v1.md
What's changed since pre-release v1.1.0-B2102024:
- Added support for `-Outcome` and `-As` to produce filtered output from `Assert-PSRule`. #643
- Configure `Output.As` with `Summary` to produce summarized results per object.
- Configure `Output.Outcome` to limit output to `Fail` or `Error`.
> Pre-release v1.1.0-B2102029

- docs/CHANGELOG-v1.md
What's changed since v1.1.0:
- Added support for extensibility with conventions. #650
- Conventions provide an extensibility point within PSRule to execution actions within the pipeline.
- A convention can expose `Begin`, `Process`, and `End` blocks.
- In additional to within rules `$PSRule.Data` can be accessed from `Begin` and `Process` blocks.
> Pre-release v1.2.0-B2103008

- README.md
- docs/concepts/PSRule/en-US/about_PSRule_Options.md
- Updated options docs for conventions.
> Update options for conventions

- docs/CHANGELOG-v1.md
What's changed since pre-release v1.2.0-B2103008:
- Bug fixes:
- Fixed dependent rule execution is skipped for consequent input objects. #657
> Pre-release v1.2.0-B2103016

- .vscode/settings.json
- README.md
- docs/specs/design-spec.md
> PSRule draft design spec

- docs/CHANGELOG-v1.md
What's changed since pre-release v1.2.0-B2103023:
- Added support for detecting files headers from additional file extensions. #664
- Added `.bicep`, `.csx`, `.jsx`, `.groovy`, `.java`, `.json`, `.jsonc`,
`.scala`, `.rb`, `.bat`, `.cmd`.
- Added support for `Jenkinsfile` and `Dockerfile` without an extension.
- Added support for automatic type binding with files that do not have a file extension. #665
> Pre-release v1.2.0-B2103031

- .github/workflows/analyze.yaml
- .github/workflows/stale.yaml
- Added workflow for stale issue clean up.
- Added workflow for MSFT OSS checks.
> Add stale bot

- docs/CHANGELOG-v1.md
- Added links to change log for new features.
> Added around links to change log

- docs/CHANGELOG-v1.md
- Fixes issue reference in change log that referred to the wrong issue.
> Fix change log for #692

- docs/CHANGELOG-v1.md
- src/PSRule/Common/YamlConverters.cs
- src/PSRule/Pipeline/Exceptions.cs
- src/PSRule/Pipeline/PipelineReciever.cs
- src/PSRule/Pipeline/PipelineWriterExtensions.cs
- src/PSRule/Resources/PSRuleResources.Designer.cs
- src/PSRule/Resources/PSRuleResources.resx
- tests/PSRule.Tests/InputFormatDeserializerTests.cs
- tests/PSRule.Tests/ObjectFromFile3.yaml
- tests/PSRule.Tests/PSRule.Common.Tests.ps1
- tests/PSRule.Tests/PSRule.Tests.csproj
- Fixed expected DocumentEnd got SequenceEnd. #698
Fixes #698 
> Fixed expected DocumentEnd got SequenceEnd #698

- .vscode/settings.json
- docs/concepts/PSRule/en-US/about_PSRule_Options.md
- docs/features.md
- docs/specs/design-spec.md
- Minor updates to design spec.
- Minor updates options documentation.
> Design spec and doc updates

- docs/CHANGELOG-v1.md
What's changed since pre-release v1.3.0-B2104030:
- Bug fixes:
- Fixed expected DocumentEnd got SequenceEnd. #698
> Pre-release v1.3.0-B2104042

- .vscode/tasks.json
- docs/CHANGELOG-v1.md
- docs/concepts/PSRule/en-US/about_PSRule_Baseline.md
- docs/concepts/PSRule/en-US/about_PSRule_Options.md
- docs/scenarios/rule-module/rule-module.md
- pipeline.build.ps1
- src/PSRule/Common/DictionaryExtensions.cs
- src/PSRule/Common/EnvironmentHelper.cs
- src/PSRule/Common/GitHelper.cs
- src/PSRule/Common/KeyMapDictionary.cs
- src/PSRule/Configuration/BaselineOption.cs
- src/PSRule/Configuration/ConfigurationOption.cs
- src/PSRule/Configuration/ConventionOption.cs
- src/PSRule/Configuration/ExecutionOption.cs
- src/PSRule/Configuration/InputOption.cs
- src/PSRule/Configuration/LoggingOption.cs
- src/PSRule/Configuration/OutputOption.cs
- src/PSRule/Configuration/PSRuleOption.cs
- src/PSRule/Configuration/RequiresOption.cs
- src/PSRule/Configuration/RuleOption.cs
- tests/PSRule.Tests/PSRule.Options.Tests.ps1
- tests/PSRule.Tests/PipelineTests.cs
- Options can be configured with environment variables. #691
Fixes #691 
> Configure options via environment variables #691

- docs/CHANGELOG-v1.md
What's changed since pre-release v1.3.0-B2104042:
- Options can be configured with environment variables. #691
- Exclude `.git` sub-directory by default for recursive scans. #697
- Added `Input.IgnoreGitPath` option to configure inclusion of `.git` path.
> Pre-release v1.3.0-B2105004

- docs/CHANGELOG-v1.md
What's changed since v1.3.0:
- PSRule banner can be configured in output when using `Assert-PSRule`. #708
> Pre-release v1.4.0-B2105004

- docs/CHANGELOG-v1.md
- docs/concepts/PSRule/en-US/about_PSRule_Assert.md
- src/PSRule/Resources/PSRuleResources.Designer.cs
- src/PSRule/Resources/PSRuleResources.resx
- src/PSRule/Runtime/SemanticVersion.cs
- tests/PSRule.Tests/AssertTests.cs
- tests/PSRule.Tests/SemanticVersionTests.cs
- Fixed pre-release constraint handling for pre-releases versions. #712
> Fixed pre-release constraint handling #712

- .vscode/settings.json
- docs/CHANGELOG-v1.md
- docs/concepts/PSRule/en-US/about_PSRule_Assert.md
- schemas/PSRule-options.schema.json
- src/PSRule/Common/EnvironmentHelper.cs
- src/PSRule/Common/KeyMapDictionary.cs
- src/PSRule/Configuration/BaselineOption.cs
- src/PSRule/Pipeline/PipelineBuilder.cs
- src/PSRule/Pipeline/PipelineReciever.cs
- src/PSRule/Runtime/Assert.cs
- src/PSRule/Runtime/ObjectHelper.cs
- src/PSRule/Runtime/SemanticVersion.cs
- tests/PSRule.Tests/AssertTests.cs
- tests/PSRule.Tests/SemanticVersionTests.cs
- Constraints can include pre-release versions of other matching versions. #714
- Constraint sets allow multiple constraints to be joined together. #715
Fixes #714 
Fixes #715 
> Version assertion improvements #714 #715

- docs/CHANGELOG-v1.md
- src/PSRule/Common/ExpressionHelpers.cs
- src/PSRule/Common/JsonConverters.cs
- src/PSRule/Common/ListExtensions.cs
- src/PSRule/Common/PSObjectExtensions.cs
- src/PSRule/Common/YamlConverters.cs
- src/PSRule/Data/TargetSourceInfo.cs
- src/PSRule/Host/HostHelper.cs
- src/PSRule/Pipeline/PipelineReciever.cs
- src/PSRule/Rules/RuleRecord.cs
- src/PSRule/Runtime/PSRuleMemberInfo.cs
- src/PSRule/Runtime/RunspaceContext.cs
- tests/PSRule.Tests/InputFormatDeserializerTests.cs
- tests/PSRule.Tests/ObjectFromFile.json
- tests/PSRule.Tests/PSRule.Common.Tests.ps1
- tests/PSRule.Tests/PipelineTests.cs
- Source location of object from input files are included in rule records. #624
Fixes #624 
> Add source location from input files #624

- docs/CHANGELOG-v1.md
What's changed since pre-release v1.4.0-B2105004:
- Source location of object from input files are included in rule records. #624
- Currently only JSON and YAML files support source locations.
- Improved support for version constraints by:
- Constraints can include prerelease versions of other matching versions. #714
- Constraints support using a `@prerelease` or `@pre` to include prerelease versions. #717
- Constraint sets allow multiple constraints to be joined together. #715
- See [about_PSRule_Assert] for details.
- Bug fixes:
- Fixed prerelease constraint handling for prerelease versions. #712
> Pre-release v1.4.0-B2105019

- schemas/PSRule-options.schema.json
- Added regex to validate requires in option schema.
> Added regex to validate Requires option

- docs/CHANGELOG-v1.md
What's changed since pre-release v1.4.0-B2105019:
- Bug fixes:
- Fixed null reference in convention for nested exceptions. #725
> Pre-release v1.4.0-B2105032

- docs/CHANGELOG-v1.md
What's changed since pre-release v1.4.0-B2105032:
- Source location of objects from the pipeline are read from properties. #729
- Assert output improvements:
- Added support for Visual Studio Code with `VisualStudioCode` style. #731
- Updated output format provides support for problem matchers in task output.
- Automatically detect output style from environment variables. #732
- _Assert-PSRule_ now defaults to `Detect` instead of `Client`.
> Pre-release v1.4.0-B2105041

- docs/CHANGELOG-v1.md
> Update YamlDotNet in change log for 11.2.0

- docs/CHANGELOG-v1.md
What's changed since v1.4.0:
- Engineering:
- Bump YamlDotNet from 11.1.1 to 11.2.0. #736
> Pre-release v1.5.0-B2106006

- .azure-pipelines/azure-pipelines.yaml
- .azure-pipelines/jobs/testContainer.yaml
- .github/dependabot.yml
- .github/workflows/analyze.yaml
- ps-rule.yaml
- Updated container image versions and CI pipeline.
> Update CI pipeline agent versions

- docs/CHANGELOG-v1.md
What's changed since pre-release v1.5.0-B2106006:
- Added string selector conditions. #747
- Use `startWith`, `contains`, and `endsWith` to check for a sub-string.
- Use `isString`, `isLower`, and `isUpper` to check for string type and casing.
- Engineering:
- Bump YamlDotNet dependency to 11.2.1. #740
- Bug fixes:
- Fixed options schema should allow spacing after `@pre`. #743
- Fixed match selector expression passing on missing field. #745
> Pre-release v1.5.0-B2107009

- docs/CHANGELOG-v1.md
- docs/concepts/PSRule/en-US/about_PSRule_Selectors.md
- Fixes for selector documentation.
> Minor fixes for selector documentation

- README.md
> Added Open in Visual Studio Code badge

- docs/CHANGELOG-v1.md
- docs/concepts/PSRule/en-US/about_PSRule_Variables.md
- src/PSRule/Commands/RuleKeyword.cs
- src/PSRule/Common/ExpressionHelpers.cs
- src/PSRule/Common/JsonConverters.cs
- src/PSRule/Common/YamlConverters.cs
- src/PSRule/Data/ITargetSourceCollection.cs
- src/PSRule/Data/InputFileInfo.cs
- src/PSRule/Data/TargetSourceInfo.cs
- src/PSRule/Host/Host.cs
- src/PSRule/Pipeline/GetTargetPipeline.cs
- src/PSRule/Pipeline/InvokeRulePipeline.cs
- src/PSRule/Pipeline/PipelineReader.cs
- src/PSRule/Pipeline/PipelineReciever.cs
- src/PSRule/Pipeline/TargetBinder.cs
- src/PSRule/Pipeline/TargetObject.cs
- src/PSRule/Resources/PSRuleResources.Designer.cs
- src/PSRule/Resources/PSRuleResources.resx
- src/PSRule/Runtime/Configuration.cs
- src/PSRule/Runtime/PSRule.cs
- src/PSRule/Runtime/PSRuleMemberInfo.cs
- src/PSRule/Runtime/RunspaceContext.cs
- tests/PSRule.Tests/FromFile.Rule.ps1
- tests/PSRule.Tests/InputFormatDeserializerTests.cs
- tests/PSRule.Tests/ObjectFromFile.json
- tests/PSRule.Tests/ObjectPathTests.cs
- tests/PSRule.Tests/PSRule.Common.Tests.ps1
- tests/PSRule.Tests/SourceTests.cs
- Added support for object source location in validation. #757
Fixes #757
> Added support for object source location #757

- docs/CHANGELOG-v1.md
What's changed since v1.5.0:
- Added support for object source location in validation. #757
- Default rule source location `.ps-rule/` is automatically included. #742
- Added `Include.Path` and `Include.Module` options to automatically include rule sources.
> Pre-release v1.6.0-B2107008

- docs/CHANGELOG-v1.md
- src/PSRule/Host/HostHelper.cs
- src/PSRule/Pipeline/InvokeRulePipeline.cs
- src/PSRule/Pipeline/PipelineBuilder.cs
- src/PSRule/Pipeline/PipelineContext.cs
- src/PSRule/Pipeline/TargetBinder.cs
- src/PSRule/Runtime/LanguageScope.cs
- src/PSRule/Runtime/RunspaceContext.cs
- tests/PSRule.Tests/AssertTests.cs
- tests/PSRule.Tests/BaselineTests.cs
- tests/PSRule.Tests/ConfigTests.cs
- tests/PSRule.Tests/ConventionTests.cs
- tests/PSRule.Tests/PipelineTests.cs
- tests/PSRule.Tests/SelectorTests.cs
- tests/PSRule.Tests/TargetBinderTests.cs
- tests/PSRule.Tests/TargetNameBindingTests.cs
- Fixed target binding across multiple scopes.
Fixes #762
> Fixed target binding across multiple scopes #762

- docs/CHANGELOG-v1.md
What's changed since pre-release v1.6.0-B2107008:
- Bug fixes:
- Fixed target binding across multiple scopes. #762
> Pre-release v1.6.0-B2108003

- docs/CHANGELOG-v1.md
What's changed since pre-release v1.6.0-B2108003:
- Added support for YAML rules. #603
- YAML rules evaluate an expression tree and return a result for each object.
- YAML provides an additional option for defining rules in addition to PowerShell script rules.
- Type and selector pre-conditions are supported.
> Pre-release v1.6.0-B2108009

- .azure-pipelines/azure-pipelines.yaml
- .github/ISSUE_TEMPLATE/bug_report.md
> Bump CI pipeline

- docs/commands/PSRule/en-US/toc.yml
- Fix table of contents for docs.
> Fix commands toc file

- docs/CHANGELOG-v1.md
What's changed since v1.6.0:
- Automatically exclude common repository files from input files. #721
- Added `Input.IgnoreRepositoryCommon` option to change default behavior.
- Added aggregation assertion methods for `AnyOf` and `AllOf`. #776
> Pre-release v1.7.0-B2108016

- docs/CHANGELOG-v1.md
What's changed since pre-release v1.7.0-B2108016:
- Bug fixes:
- Fixed configuration array deserializes as dictionary from YAML options. #779
> Pre-release v1.7.0-B2108021

- .azure-pipelines/azure-pipelines.yaml
- pipeline.build.ps1
- Update CI pipeline for force publish of v1.6.1.
> Add force publish to CI pipeline

- .azure-pipelines/azure-pipelines.yaml
- docs/CHANGELOG-v1.md
- pipeline.build.ps1
- Merge in change log updated for v1.6.1.
> Update change log for v1.6.1

- docs/CHANGELOG-v1.md
What's changed since pre-release v1.7.0-B2108032:
- Allow baselines to include local rules. #756
- The `Rule.IncludeLocal`option was automatically include local/ standalone rules not in a module.
- This option is useful when you want to include local rules not included in a baseline.
> Pre-release v1.7.0-B2109002

- docs/CHANGELOG-v1.md
What's changed since v1.7.0:
- Bug fixes:
- Fixed ResourceTags does not contain a method named ToHashtable. #798
> Release v1.7.1

- docs/CHANGELOG-v1.md
What's changed since v1.7.1:
- Bug fixes:
- Fixed `Get-PSRuleBaseline` does not return any results from module. #801
> Release v1.7.2

- docs/CHANGELOG-v1.md
What's changed since v1.7.2:
- Added assertion helpers and expressions for improving intersection checks. #795
- Added `Count` to determine of the field has a specific number of elements.
- Added `SetOf` to determine if a collection is another collection.
- Added `Subset` to determine if a collection is includes another collection.
> Pre-release v1.8.0-B2109015

- docs/CHANGELOG-v1.md
What's changed since pre-release v1.8.0-B2109015:
- Added support for conditional reason messages with `ReasonIf`. #804
- Added support for `type` and `name` expression properties. #810
- Use `type` to compare the bound type of the current object.
- Use `name` to compare the bound name of the current object.
> Pre-release v1.8.0-B2109022

- docs/CHANGELOG-v1.md
What's changed since pre-release v1.8.0-B2109022:
- Added YAML output format support for `Get-PSRuleBaseline`. #326
> Pre-release v1.8.0-B2110006

- docs/CHANGELOG-v1.md
What's changed since pre-release v1.8.0-B2110020:
- Added `Output.JsonIndent` option for JSON output format. #817
> Pre-release v1.8.0-B2110030

- README.md
- docs/CHANGELOG-v1.md
- docs/commands/PSRule/en-US/Export-PSRuleBaseline.md
- docs/commands/PSRule/en-US/Get-PSRuleBaseline.md
- src/PSRule/Common/BaselineJsonSerializationMapper.cs
- src/PSRule/Common/BaselineYamlSerializationMapper.cs
- src/PSRule/Common/DictionaryExtensions.cs
- src/PSRule/Common/HashtableExtensions.cs
- src/PSRule/Common/JsonCommentWriter.cs
- src/PSRule/Common/JsonConverters.cs
- src/PSRule/Common/StringExtensions.cs
- src/PSRule/Common/YamlConverters.cs
- src/PSRule/PSRule.psm1
- src/PSRule/Pipeline/ExportBaselinePipelineBuilder.cs
- src/PSRule/Pipeline/GetBaselinePipelineBuilder.cs
- src/PSRule/Pipeline/Output/JsonOutputWriter.cs
- src/PSRule/Pipeline/Output/YamlOutputWriter.cs
- src/PSRule/Pipeline/PipelineBuilder.cs
- tests/PSRule.Tests/PSRule.Baseline.Tests.ps1
- tests/PSRule.Tests/TestModule4/rules/Baseline.Rule.jsonc
Fix #839
Also made some slight improvements:
- Refactored Yaml implementation to sort properties consistently across the output. Some types such as dictionaries and arrays were not sorting due to not sorting the inner types. Made the same changes to JSON.
- Added missing `Output.JsonIndent` option to README
- Split the Yaml/Json mapping classes, although was trying to find a way to consolidate these implementations into one. Probably is possible but might get messy.
- Converted alot of variables to `var` to stay consistent with codebase. 
```powershell
Get-PSRuleBaseline -OutputFormat Json -Module PSRule.Rules.Azure -Option @{'Output.JsonIndent' = 4}
```
```jsonc
[
{
// Synopsis: Default baseline for Azure rules.
"apiVersion": "github.com/microsoft/PSRule/v1",
"kind": "Baseline", …
```
> Added JSON output format for baseline cmdlets and more refactoring

- docs/CHANGELOG-v1.md
- src/PSRule/Common/YamlConverters.cs
- src/PSRule/Definitions/Conventions/BaseConvention.cs
- src/PSRule/Definitions/Conventions/ConventionComparer.cs
- src/PSRule/Definitions/Conventions/ScriptBlockConvention.cs
- src/PSRule/Definitions/IConvention.cs
- src/PSRule/Definitions/Resource.cs
- src/PSRule/Host/HostHelper.cs
- src/PSRule/Pipeline/AssertPipeline.cs
- src/PSRule/Pipeline/ExportBaselinePipelineBuilder.cs
- src/PSRule/Pipeline/GetBaselinePipeline.cs
- src/PSRule/Pipeline/GetBaselinePipelineBuilder.cs
- src/PSRule/Pipeline/GetRuleHelpPipeline.cs
- src/PSRule/Pipeline/GetRulePipeline.cs
- src/PSRule/Pipeline/GetTargetPipeline.cs
- src/PSRule/Pipeline/InvokeRulePipeline.cs
- src/PSRule/Pipeline/OptionContext.cs
- src/PSRule/Pipeline/PipelineBuilder.cs
- src/PSRule/Pipeline/PipelineContext.cs
- src/PSRule/Pipeline/PipelineLogger.cs
- src/PSRule/Pipeline/PipelineWriter.cs
- src/PSRule/Pipeline/PipelineWriterExtensions.cs
- src/PSRule/Pipeline/RulePipeline.cs
- src/PSRule/Runtime/RunspaceContext.cs
- tests/PSRule.Tests/ConfigurationTests.cs
- tests/PSRule.Tests/ConventionTests.cs
- tests/PSRule.Tests/TestWriter.cs
- Fixed convention execution is out of order. #835
Fixes #835 
> Fixed convention execution is out of order #835

- docs/CHANGELOG-v1.md
What's changed since pre-release v1.9.0-B2110027:
- Added JSON output format for Baseline cmdlets. #839
- Bug fixes:
- Fixed convention execution is out of order. #835
> Pre-release v1.9.0-B2111009

- docs/CHANGELOG-v1.md
- docs/concepts/PSRule/en-US/about_PSRule_Assert.md
- src/PSRule/Common/PSObjectExtensions.cs
- src/PSRule/Data/ITargetIssueCollection.cs
- src/PSRule/Data/TargetIssueInfo.cs
- src/PSRule/Pipeline/PipelineReciever.cs
- src/PSRule/Pipeline/TargetObject.cs
- src/PSRule/Runtime/Assert.cs
- src/PSRule/Runtime/PSRule.cs
- src/PSRule/Runtime/PSRuleMemberInfo.cs
- tests/PSRule.Tests/FromFile.Rule.ps1
- tests/PSRule.Tests/ObjectFromFile.json
- tests/PSRule.Tests/PSRule.Common.Tests.ps1
- tests/PSRule.Tests/TargetInfoTests.cs
- Allow downstream issues to be consumed.
Fixes #843
> Allow downstream issues to be consumed #843

- .azure-pipelines/azure-pipelines.yaml
- Bump the CI pipeline images to use PowerShell 7.2.
> Bump CI pipeline images

- README.md
- Bump maintainers in README.md.
> Bump maintainers

- docs/CHANGELOG-v1.md
Whats's changed since v1.9.0:
- Added JSON support for reading rules and selectors from pipeline. #857
- Added `HasSchema` expression to check the schema of an object. #860
- Bug fixes:
- Fixed `$Assert.HasJsonSchema` accepts empty value. #859
> Pre-release v1.10.0-B2111024

- docs/CHANGELOG-v1.md
What's changed since pre-release v1.10.0-B2111024:
- Bug fixes:
- Fixed module configuration is not loaded when case does not match. #864
> Pre-release v1.10.0-B2112002

- docs/CHANGELOG-v1.md
What's changed since v1.10.0:
- Added `version` expression to check semantic version constraints. #861
- Added `hasDefault` expression to check field default value. #870
- Bug fixes:
- Fixed `GetReason()` not returning results for a failed assertion. #874
> Pre-release v1.11.0-B2112016

- .devcontainer/container-build.ps1
- .devcontainer/container-start.ps1
- .devcontainer/devcontainer.json
- .vscode/extensions.json
- Added configuration updates for building in codespaces.
> Added codespaces updates

- .github/workflows/analyze.yaml
- Updated code analysis to include DevSkim and CodeQL.
> Updated code analysis

- .github/workflows/docs.yaml
> Fix mike stable flag

- .github/workflows/docs.yaml
- Update CI for publishing docs.
> Update docs CI

- .github/workflows/docs.yaml
- mkdocs.yml
- Additional fixes for docs CI pipeline.
> Updates to docs pipeline

- .github/workflows/docs.yaml
- Get Git history for mike deployment.
> Get Git history for docs CI

- docs/creating-your-pipeline.md
- docs/install-instructions.md
- Updated documentation to use latest versions of GitHub Action and Azure Pipelines task.
> Update docs to use latest pipeline versions

- docs/CHANGELOG-v1.md
What's changed since v1.11.0:
- Added support for object path expressions. #808 #693
- Inspired by JSONPath, object path expressions can be used to access nested objects.
- Array members can be filtered and enumerated using object path expressions.
- Object path expressions can be used in YAML, JSON, and PowerShell rules and selectors.
- Improve tracking of suppressed objects. #794
- Added `Execution.SuppressedRuleWarning` option to output warning for suppressed rules.
- Engineering:
- **Breaking change:** Removal of deprecated default baseline from module manifest. #755
- Set the default module baseline using module configuration.
- **Breaking change:** Require `apiVersion` on YAML and JSON to be specified. #648
- Resources should use …
> Pre-release v2.0.0-B2201054

- docs/upgrade-notes.md
- Minor updates to upgrade notes wording for v2.
> Minor improvements to upgrade notes wording

- docs/CHANGELOG-v1.md
What's changed since pre-release v2.0.0-B2201054:
- Added support for rule aliases. #792
- Aliases allow rules to be references by an alternative name.
- When renaming rules, add a rule alias to avoid breaking references to the old rule name.
- To specify an alias use the `-Alias` parameter or `alias` metadata property in YAML or JSON.
- Added support for stable identifiers with rule refs. #881
- A rule ref may be optionally be used to reference a rule.
- Rule refs should be:
stable, not changing between releases;
opaque, as opposed to being a human-readable string.
Stable and opaque refs ease web lookup and to help to avoid language difficulties.
- To specify a rule ref use the `-Ref` parameter or `ref` metadata property in YAML or JSON.
- Bug fixes:
- Fixes …
> Pre-release v2.0.0-B2201075

- tests/PSRule.Tests/PSRule.Tests.csproj
- tests/PSRule.Tests/RulesTests.cs
- Improved test cases for rules.
> Improve rule test cases for v1

- schemas/PSRule-language.schema.json
- schemas/PSRule-options.schema.json
- Updated schemas to reference new docs pages instead of old broken links.
> Updated schema doc URLs

- tests/PSRule.Tests/PSRule.Tests.csproj
- tests/PSRule.Tests/RulesTests.cs
> Improve rule tests for v2

- docs/CHANGELOG-v1.md
What's changed since pre-release v2.0.0-B2201075:
- Add support for suppression groups. #793
- New `SuppressionGroup` resource has been included.
> Pre-release v2.0.0-B2201093

- .github/workflows/dependencies.yaml
- modules.json
- pipeline.build.ps1
- scripts/dependencies.psm1
- tests/PSRule.Tests/InputPathBuilderTests.cs
- Added dependency update automation.
> Automated dependency updates

- CHANGELOG.md
- docs/CHANGELOG-v0.md
- docs/CHANGELOG-v1.md
- docs/CHANGELOG-v2.md
- mkdocs.yml
- Updates to change log in preparation for v2.
> Updates to change log for v2

- docs/CHANGELOG-v2.md
What's changed since pre-release v2.0.0-B2201093:
- Add option to disable invariant culture warning. #899
- Added `Execution.InvariantCultureWarning` option.
> Pre-release v2.0.0-B2201117

- docs/CHANGELOG-v2.md
- src/PSRule/Commands/RuleKeyword.cs
- src/PSRule/Common/ExpressionHelpers.cs
- src/PSRule/Common/YamlConverters.cs
- src/PSRule/Data/ITargetInfo.cs
- src/PSRule/Data/ITargetSourceCollection.cs
- src/PSRule/Data/InputFileInfo.cs
- src/PSRule/Data/RepositoryInfo.cs
- src/PSRule/Pipeline/Output/SarifOutputWriter.cs
- src/PSRule/Pipeline/SourcePipeline.cs
- src/PSRule/Pipeline/TargetObject.cs
- src/PSRule/Rules/Rule.cs
- src/PSRule/Runtime/Assert.cs
- src/PSRule/Runtime/ObjectPath/PathExpressionBuilder.cs
- src/PSRule/Runtime/RuleConditionResult.cs
- tests/PSRule.Tests/OutputWriterTests.cs
- tests/PSRule.Tests/PipelineTests.cs
- tests/PSRule.Tests/TargetNameBindingTests.cs
- Added new properties for module lookup to SARIF results. #951
- Bug fixes:
- Fixed rule references in SARIF format for extensions need a toolComponent reference. #949
- Fixed file objects processed with file input format have no source location. #950
Fixes #949
Fixes #950 
Fixes #951 
> Improvements to SARIF output #949 #950 #951

- docs/CHANGELOG-v2.md
What's changed since pre-release v2.0.0-B2201161:
- Added new properties for module lookup to SARIF results. #951
- Bug fixes:
- Fixed rule references in SARIF format for extensions need a `toolComponent` reference. #949
- Fixed file objects processed with file input format have no source location. #950
> Pre-release v2.0.0-B2202006

- docs/scenarios/azure-resources/azure-resources.md
> Minor grammatical change

- docs/CHANGELOG-v2.md
What's changed since pre-release v2.0.0-B2202006:
- Bug fixes:
- Fixed GitHub code scanning alerts treats pass as problems. #955
- By default, SARIF output will only include fail or error outcomes.
- Added `Output.SarifProblemsOnly` option to include pass outcomes.
- Fixed SARIF output includes rule property for default tool component. #956
> Pre-release v2.0.0-B2202017

- docs/CHANGELOG-v2.md
What's changed since pre-release v2.0.0-B2202017:
- Added source expression property. #933
- Included the following expressions:
- `source`
- `withinPath`
- `notWithinPath`
> Pre-release v2.0.0-B2202024

- .markdownlint.json
- docs/analysis-output.md
- docs/concepts/PSRule/en-US/about_PSRule_Options.md
- mkdocs.yml
Added some example output related with #937
> Add docs for analysis output

- docs/CHANGELOG-v2.md
What's changed since pre-release v2.0.0-B2202024:
- Bug fixes:
- Fixed Invoke-PSRule hanging if JSON rule file is empty. #969
> Pre-release v2.0.0-B2202056

- docs/CHANGELOG-v1.md
What's changed since v1.11.1:
- Bug fixes:
- Fixed broken documentation links. #980
> Release v1.11.1

- README.md
- docs/CHANGELOG-v1.md
- docs/CHANGELOG-v2.md
- docs/commands/PSRule/en-US/Assert-PSRule.md
- docs/commands/PSRule/en-US/Export-PSRuleBaseline.md
- docs/commands/PSRule/en-US/Get-PSRule.md
- docs/commands/PSRule/en-US/Get-PSRuleBaseline.md
- docs/commands/PSRule/en-US/Get-PSRuleHelp.md
- docs/commands/PSRule/en-US/Get-PSRuleTarget.md
- docs/commands/PSRule/en-US/Invoke-PSRule.md
- docs/commands/PSRule/en-US/New-PSRuleOption.md
- docs/commands/PSRule/en-US/Set-PSRuleOption.md
- docs/commands/PSRule/en-US/Test-PSRuleTarget.md
- docs/concepts/PSRule/en-US/about_PSRule_Assert.md
- docs/concepts/PSRule/en-US/about_PSRule_Badges.md
- docs/concepts/PSRule/en-US/about_PSRule_Baseline.md
- docs/concepts/PSRule/en-US/about_PSRule_Conventions.md
- docs/concepts/PSRule/en-US/about_PSRule_Docs.md
- docs/concepts/PSRule/en-US/about_PSRule_Expressions.md
- docs/concepts/PSRule/en-US/about_PSRule_Options.md
- docs/concepts/PSRule/en-US/about_PSRule_Rules.md
- docs/concepts/PSRule/en-US/about_PSRule_Selectors.md
- docs/concepts/PSRule/en-US/about_PSRule_SuppressionGroups.md
- docs/concepts/PSRule/en-US/about_PSRule_Variables.md
- docs/keywords/PSRule/en-US/about_PSRule_Keywords.md
- mkdocs.yml
- Fixed broken documentation links. #980
> Fixes to docs and links #980 #982

- docs/CHANGELOG-v2.md
What's changed since pre-release v2.0.0-B2202056:
- Bug fixes:
- Fixed broken documentation links. #980
> Pre-release v2.0.0-B2202065

- .github/ISSUE_TEMPLATE/docs-update.md
- .github/ISSUE_TEMPLATE/question.md
- CONTRIBUTING.md
- docs/related-projects.md
- mkdocs.yml
- Updates to issue template and contributing docs.
> General repo documentation updates

- docs/CHANGELOG-v2.md
What's changed since pre-release v2.0.0-B2202065:
- Capture and output repository info in Assert-PSRule runs. #978
- Added `Repository.Url` option set repository URL reported in output.
- Repository URL is detected automatically for GitHub Actions and Azure Pipelines.
- Added `RepositoryInfo` to `Output.Banner` option.
- Repository info is shown by default.
- Bug fixes:
- Fixed SARIF should report base branch. #964
> Pre-release v2.0.0-B2202072

- docs/CHANGELOG-v2.md
What's changed since pre-release v2.0.0-B2202072:
- Added `convert` and `caseSensitive` to string comparison expressions. #1001
- The following expressions support type convertion and case-sensitive comparison.
- `startsWith`, `contains`, and `endsWith`.
- `equals` and `notEquals`.
> Pre-release v2.0.0-B2203019

- docs/CHANGELOG-v2.md
What's changed since pre-release v2.0.0-B2203033:
- Added `convert` to numeric comparison expressions. #943
- Type conversion is now supported for `less`, `lessOrEquals`, `greater`, and `greaterOrEquals`.
- **Breaking change:** Added validation of resource names. #1012
- Invalid rules names will now produce a specific error.
- Bug fixes:
- Fixed unclear error message on invalid rule names. #1012
> Pre-release v2.0.0-B2203045

- docs/CHANGELOG-v1.md
- docs/deprecations.md
- docs/upgrade-notes.md
- requirements-docs.txt
Merge corrections from v2 docs to v1 docs.
> Corrections for v1 docs

- README.md
- docs/commands/PSRule/en-US/Assert-PSRule.md
- docs/commands/PSRule/en-US/Export-PSRuleBaseline.md
- docs/commands/PSRule/en-US/Get-PSRule.md
- docs/commands/PSRule/en-US/Get-PSRuleBaseline.md
- docs/commands/PSRule/en-US/Get-PSRuleHelp.md
- docs/commands/PSRule/en-US/Get-PSRuleTarget.md
- docs/commands/PSRule/en-US/Invoke-PSRule.md
- docs/commands/PSRule/en-US/New-PSRuleOption.md
- docs/commands/PSRule/en-US/Set-PSRuleOption.md
- docs/commands/PSRule/en-US/Test-PSRuleTarget.md
- schemas/PSRule-language.schema.json
- schemas/PSRule-options.schema.json
- schemas/PSRule-resources.schema.json
- Update URLs is docs and schemas to use `https://` instead of `http://`.
> Update http URLs to https

- .github/workflows/docs.yaml
- Updated docs CI to push to stable alias.
> Update docs CI to push to stable

- .azure-pipelines/azure-pipelines.yaml
- mkdocs.yml
- Update CI version for next release.
- Fix docs navigation.
> Bump CI version

- docs/analysis-output.md
- docs/creating-your-pipeline.md
- docs/install-instructions.md
- Update docs to reference new action release.
> Update action version to v2.0.0

- README.md
> Fix vscode.dev badge

- docs/CHANGELOG-v2.md
What's changed since v2.0.0:
- Bug fixes:
- Fixed read JSON failed with comments. #1051
- Fixed null reference on elapsed time when required module check fails. #1054
- Fixed failed to read JSON objects with a empty property name. #1052
> Release v2.0.1

- docs/analysis-output.md
- docs/authoring/testing-infrastructure.md
- docs/quickstart/standalone-rule.md
- Updates to features to identify applicable version.
> Minor updates to features notes

- .azure-pipelines/azure-pipelines.yaml
- GitVersion.yml
- Disable repository releases.
- Add GitVersion config.
> Disable repository release

- .vscode/settings.json
- docs/CHANGELOG-v2.md
- Added code signing of module. #1049
- Added SBOM manifests to module. #1050
Fixes #1049 
Fixes #1050
> Added code signing and SBOM #1049 #1050

- docs/CHANGELOG-v2.md
What's changed since v2.0.1:
- Engineering:
- Added code signing of module. #1049
- Added SBOM manifests to module. #1050
> Release v2.1.0-B0015

- docs/CHANGELOG-v2.md
- src/PSRule/Common/ExpressionHelpers.cs
- src/PSRule/Configuration/PSRuleOption.cs
- src/PSRule/Definitions/Expressions/LanguageExpressions.cs
- src/PSRule/Runtime/Operand.cs
- tests/PSRule.Tests/SelectorTests.cs
- tests/PSRule.Tests/Selectors.Rule.jsonc
- tests/PSRule.Tests/Selectors.Rule.yaml
- Added source support for string conditions.
Fixes #1068
> Added source string condition support #1068

- docs/CHANGELOG-v2.md
What's changed since pre-release v2.1.0-B0015:
- Added custom suppression message during PSRule runs. #1046
- When a rule is suppressed using a suppression group the synopsis is shown in the suppression warning.
- Configure the suppression group synopsis to display a custom message.
- Suppression groups synopsis can be localized using markdown documentation.
- Use markdown to set a culture specific synopsis.
- Custom suppression messages are not supported when suppressing individual rules using `ps-rule.yaml`.
- Added source support for string conditions. #1068
- Engineering:
- Bump Sarif.Sdk to 2.4.14. #1064
- Bump Pester to 5.3.2. #1062
- Bug fixes:
- **Important change:** Fixed source scope not updated in multi-module runs. #1053
- Several properties of rule and …
> Pre-release v2.1.0-B0040

- docs/CHANGELOG-v2.md
- docs/concepts/PSRule/en-US/about_PSRule_Options.md
- ps-rule.yaml
- src/PSRule/Pipeline/PathFilter.cs
- Added additional repository paths to ignore by default.
Fixes #1043
> Ignore additional repo paths #1043

- docs/CHANGELOG-v2.md
What's changed since pre-release v2.1.0-B0040:
- Added `notStartsWith`, `notEndsWith`, and `notContains` expressions and assertion helpers. #1047
- Added `like`, `notLike` expressions and assertion helpers. #1048
- Added additional repository paths to ignore by default. #1043
- Engineering:
- Bump Sarif.Sdk to 2.4.15. #1075]
> Pre-release v2.1.0-B0069

- .github/workflows/stale.yaml
- Minor updates to stale workflow.
> Minor updates to stale workflow

- .github/workflows/dependencies.yaml
- .github/workflows/docs.yaml
- .github/workflows/first-interaction.yaml
- .github/workflows/stale.yaml
- Added greetings workflow for first interactions.
- Added dispatch trigger for stale workflow.
> Added greeting and add workflow trigger for stale

- .github/workflows/analyze.yaml
- docs/CHANGELOG-v2.md
- docs/analysis-output.md
- docs/creating-your-pipeline.md
- docs/install-instructions.md
- docs/scenarios/validation-pipeline/validate-files.ps1
- docs/scenarios/validation-pipeline/validation-pipeline.md
> Minor updates to docs

- docs/CHANGELOG-v2.md
- src/PSRule/Runtime/ObjectPath/PathTokenizer.cs
- tests/PSRule.Tests/PathExpressionTests.cs
- tests/PSRule.Tests/PathTokenizerTests.cs
- Fixed grouping of logical operators in object path.
Fixes #1101 
> Fixed grouping in object path #1101

- src/PSRule.Benchmark/PSRule.Benchmark.csproj
- src/PSRule.BuildTool/PSRule.BuildTool.csproj
- Update NuGet project options for non-package projects. #1093
> Update tool project NuGet options

- pipeline.build.ps1
- Clean up attachment of change log in CI which is no longer used.
> Cleanup CI attachment

- .vscode/settings.json
- docs/CHANGELOG-v2.md
- Added packaging publishing.
Fixes #1093
> Added NuGet publishing #1093

- docs/CHANGELOG-v2.md
What's changed since v2.1.0:
- Added `notCount` expression and assertion helper by @ArmaanMcleod.
[#1091](https://github.com/microsoft/PSRule/issues/1091)
- Engineering:
- Bump xunit.runner.visualstudio to 2.4.5.
[#1084](https://github.com/microsoft/PSRule/pull/1084)
- Bump Pester to 5.3.3.
[#1079](https://github.com/microsoft/PSRule/pull/1079)
- Bump Microsoft.NET.Test.Sdk to 17.2.0.
[#1089](https://github.com/microsoft/PSRule/pull/1089)
- Added NuGet packaging publishing by @BernieWhite.
[#1093](https://github.com/microsoft/PSRule/issues/1093)
- Updated NuGet packaging metadata by @BernieWhite.
[#1093](https://github.com/microsoft/PSRule/issues/1093)
- Bug fixes:
- Fixed grouping of logical operators in object path by @BernieWhite. …
> Pre-release v2.2.0-B0021

- .vscode/settings.json
- PSRule.sln
- src/PSRule.Badges/PSRule.Badges.csproj
- src/PSRule.Badges/Properties/AssemblyInfo.cs
- src/PSRule.Common.props
- src/PSRule.SDK/PSRule.SDK.csproj
- src/PSRule.SDK/README.md
- src/PSRule/PSRule.Format.ps1xml
- src/PSRule/PSRule.csproj
- src/PSRule/PSRule.psd1
- Updates to NuGet metadata and SDK package.
> Updates to NuGet packaging

- docs/CHANGELOG-v2.md
- src/PSRule/Rules/RuleRecord.cs
- tests/PSRule.Tests/PSRule.Common.Tests.ps1
- Fixed output of reason with wide format.
Fixes #1117 
> Fixed output of reason with wide format #1117

- README.md
- docs/CHANGELOG-v2.md
- docs/concepts/PSRule/en-US/about_PSRule_Options.md
- schemas/PSRule-options.schema.json
- src/PSRule/Common/PSObjectExtensions.cs
- src/PSRule/Configuration/InputOption.cs
- src/PSRule/Data/ITargetSourceCollection.cs
- src/PSRule/PSRule.psm1
- src/PSRule/Pipeline/GetTargetPipeline.cs
- src/PSRule/Pipeline/InvokeRulePipeline.cs
- src/PSRule/Pipeline/PipelineBuilder.cs
- src/PSRule/Pipeline/PipelineReader.cs
- src/PSRule/Pipeline/TargetObject.cs
- tests/PSRule.Tests/PSRule.Options.Tests.ps1
- tests/PSRule.Tests/PSRule.Tests.yml
- tests/PSRule.Tests/PathFilterTests.cs
- tests/PSRule.Tests/PipelineTests.cs
- Fixed piped input does not respect excluded paths.
Fixes #1114
> Fixed piped input with ignored paths #1114

- pipeline.build.ps1
- Fixed build for SDK project.
> Fix build for SDK project

- docs/CHANGELOG-v2.md
What's changed since pre-release v2.2.0-B0021:
- Added informational message when output has been written to disk by @BernieWhite.
[#1074](https://github.com/microsoft/PSRule/issues/1074)
- The `Output.Footer` option now supports `OutputFile` which reports the output file path.
This is enabled by default.
- Engineering:
- Added more object path tests by @ArmaanMcleod.
[#1110](https://github.com/microsoft/PSRule/issues/1110)
- Bug fixes:
- Fixed output of reason with wide format by @BernieWhite.
[#1117](https://github.com/microsoft/PSRule/issues/1117)
- Fixed piped input does not respect excluded paths by @BernieWhite.
[#1114](https://github.com/microsoft/PSRule/issues/1114)
> Pre-release v2.2.0-B0052

- src/PSRule.Common.props
> Update copyright for NuGet publishing

- src/PSRule.SDK/PSRule.SDK.csproj
- src/PSRule.SDK/PSRule.psd1
- Added module shim for loading dependency chains through the SDK.
> Added SDK module shim for dependency modules

- docs/CHANGELOG-v2.md
What's changed since pre-release v2.2.0-B0052:
- Improved reporting of the object path that caused rule failures by @BernieWhite.
[#1092](https://github.com/microsoft/PSRule/issues/1092)
- Output include a new `Detail` property with details of the reason and the object path.
- Custom methods `ReasonFrom` and `ReasonIf` accept a `path` parameter to specify the object path.
> Pre-release v2.2.0-B0089

- docs/CHANGELOG-v2.md
What's changed since pre-release v2.2.0-B0089:
- Added descendant selector to object path syntax.
[#1133](https://github.com/microsoft/PSRule/issues/1133)
- Use `..` to traverse into child objects, for example `$..name` finds names for all nested objects.
- Engineering:
- Bump Newtonsoft.Json to 13.0.1.
[#1137](https://github.com/microsoft/PSRule/pull/1137)
> Pre-release v2.2.0-B0131

- docs/CHANGELOG-v2.md
What's changed since v2.2.0:
- Bug fixes:
- Fixed path within SDK package causes `psd1` to compile by @BernieWhite.
[#1146](https://github.com/microsoft/PSRule/issues/1146)
> Pre-release v2.3.0-B0001

- docs/CHANGELOG-v2.md
What's changed since pre-release v2.3.0-B0001:
- Added PSRule for Azure expansion configuration to options schema by @BernieWhite.
[#1149](https://github.com/microsoft/PSRule/issues/1149)
- Engineering:
- Refactoring and updates to interfaces to allow use outside of PowerShell by @BernieWhite.
[#1152](https://github.com/microsoft/PSRule/issues/1152)
> Pre-release v2.3.0-B0006

- docs/CHANGELOG-v2.md
What's changed since pre-release v2.3.0-B0006:
- Bug fixes:
- Fixed null object reference for object equity comparison by @BernieWhite.
[#1157](https://github.com/microsoft/PSRule/issues/1157)
- Fixed expression evaluation not logging debug output when using the `-Debug` switch by @BernieWhite.
[#1158](https://github.com/microsoft/PSRule/issues/1158)
- Fixed startIndex cannot be larger than length of string by @BernieWhite.
[#1160](https://github.com/microsoft/PSRule/issues/1160)
> Pre-release v2.3.0-B0015

- docs/addon-modules.md
Added PSRule.Monitor to addon page
> Added PSRule.Monitor to addon-modules.md

- docs/CHANGELOG-v2.md
What's changed since pre-release v2.3.0-B0015:
- General improvements
- Improved reporting of full object path from pre-processed results.
[#1169](https://github.com/microsoft/PSRule/issues/1169)
> Pre-release v2.3.0-B0030

- docs/CHANGELOG-v2.md
- docs/concepts/PSRule/en-US/about_PSRule_Options.md
- Improve documentation for `Output.Outcome`.
Fixes #1166
> Improve outcome option docs #1166

- docs/CHANGELOG-v2.md
What's changed since pre-release v2.3.0-B0030:
- Added support for full path from JSON objects by @BernieWhite.
[#1174](https://github.com/microsoft/PSRule/issues/1174)
- Engineering:
- Added publishing support for NuGet symbol packages @BernieWhite.
[#1173](https://github.com/microsoft/PSRule/issues/1173)
- Updated outcome option docs by @BernieWhite.
[#1166](https://github.com/microsoft/PSRule/issues/1166)
- Bump Sarif.Sdk to v2.4.16.
[#1177](https://github.com/microsoft/PSRule/pull/1177)
> Pre-release v2.3.0-B0051

- docs/CHANGELOG-v2.md
- src/PSRule/Common/PipelineExtensions.cs
- src/PSRule/Configuration/PSRuleOption.cs
- src/PSRule/Pipeline/CommandLineBuilder.cs
- src/PSRule/Pipeline/InvokeRulePipeline.cs
- src/PSRule/Pipeline/PipelineBuilder.cs
- src/PSRule/Pipeline/RulePipeline.cs
- src/PSRule/Runtime/ObjectHelper.cs
- src/PSRule/Runtime/PSRuleMemberInfo.cs
- tests/PSRule.Tests/TargetBinderTests.cs
- Added support for binding with JSON objects.
Fixes #1182
> Improve JSON object binding #1182

- docs/CHANGELOG-v2.md
What's changed since pre-release v2.3.0-B0051:
- Added support for binding with JSON objects by @BernieWhite.
[#1182](https://github.com/microsoft/PSRule/issues/1182)
> Pre-release v2.3.0-B0074

- docs/CHANGELOG-v2.md
- src/PSRule/Common/JsonConverters.cs
- src/PSRule/Common/JsonHelper.cs
- src/PSRule/Pipeline/TargetObject.cs
- tests/PSRule.Tests/TargetBinderTests.cs
- Fixed handling for JSON objects in rules.
Fixes #1187
> Fixed handling for JSON objects in rules #1187

- docs/CHANGELOG-v2.md
What's changed since pre-release v2.3.0-B0074:
- Engineering:
- Added comment documentation to .NET classes and interfaces by @BernieWhite.
[#1186](https://github.com/microsoft/PSRule/issues/1186)
- Bug fixes:
- Fixed handling for JSON objects in rules by @BernieWhite.
[#1187](https://github.com/microsoft/PSRule/issues/1187)
> Pre-release v2.3.0-B0100

- docs/CHANGELOG-v0.md
- docs/CHANGELOG-v1.md
- Update release notes from prior version.
> Update prior release notes

- .github/workflows/docs.yaml
- docs/CHANGELOG-v0.md
- docs/CHANGELOG-v1.md
- docs/upgrade-notes.md
- mkdocs.yml
- overrides/main.html
- requirements-docs.txt
- Update change log and upgrade notes for legacy v1 docs.
> Update upgrade notes and change log for v1

- docs/CHANGELOG-v2.md
- src/PSRule/Data/RepositoryInfo.cs
- src/PSRule/Data/TargetSourceInfo.cs
- src/PSRule/Definitions/IResourceHelpInfo.cs
- src/PSRule/Definitions/InfoString.cs
- src/PSRule/Rules/RuleHelpInfo.cs
- src/PSRule/Rules/RuleRecord.cs
- Expose online link extension method.
- Additional improvements to comment docs.
Fixes #1195
> Expose online link extension method #1195

- docs/CHANGELOG-v2.md
What's changed since pre-release v2.3.0-B0100:
- Engineering:
- Expose online link extension method by @BernieWhite.
[#1195](https://github.com/microsoft/PSRule/issues/1195)
- Bug fixes:
- Fixes JSON parsing of string array for single objects by @BernieWhite.
[#1193](https://github.com/microsoft/PSRule/issues/1193)
> Pre-release v2.3.0-B0130

- docs/CHANGELOG-v2.md
What's changed since v2.3.0:
- Bug fixes:
- Fixed object path join handling of self path identifier by @BernieWhite.
[#1204](https://github.com/microsoft/PSRule/issues/1204)
> Release v2.3.1

- .vscode/settings.json
- docs/CHANGELOG-v2.md
- src/PSRule/Definitions/ResultReason.cs
- src/PSRule/Runtime/Operand.cs
- tests/PSRule.Tests/AssertTests.cs
- Merge changes from patch release v2.3.1.
> Merge changes from release v2.3.1

- docs/CHANGELOG-v2.md
- docs/install-instructions.md
- pipeline.build.ps1
- src/PSRule.Benchmark/PSRule.Benchmark.csproj
- src/PSRule.BuildTool/BadgeResource.cs
- src/PSRule.BuildTool/PSRule.BuildTool.csproj
- tests/PSRule.Tests/PSRule.Tests.csproj
- Bumped support projects to .NET 6.
Fixes #1209
> Bump support projects to .NET 6 #1209

- .editorconfig
- README.md
- src/PSRule.Badges/SvgBuilder.cs
- src/PSRule.BuildTool/ClientBuilder.cs
- src/PSRule/Badges/BadgeBuilder.cs
- src/PSRule/Common/KeyMapDictionary.cs
- src/PSRule/Common/ReadOnlyHashtable.cs
- src/PSRule/Configuration/BindingOption.cs
- src/PSRule/Configuration/ConfigurationOption.cs
- src/PSRule/Configuration/ExecutionOption.cs
- src/PSRule/Configuration/InputOption.cs
- src/PSRule/Configuration/PSRuleOption.cs
- src/PSRule/Configuration/RepositoryOption.cs
- src/PSRule/Configuration/RuleOption.cs
- src/PSRule/Configuration/SuppressionOption.cs
- src/PSRule/Pipeline/Source.cs
Non-functional changes including:
- Added/ updated comment docs for classes.
- Updates README with link updates.
- Added additional code formatting rules.
> Improved documentation of classes #1186

- .vscode/settings.json
- NuGet.config
- Add NuGet config to improve developer experience with private feeds are configured locally.
> Add NuGet config

- docs/CHANGELOG-v2.md
- src/PSRule/Commands/InvokeRuleBlockCommand.cs
- src/PSRule/Commands/NewRuleDefinitionCommand.cs
- src/PSRule/Definitions/Resource.cs
- src/PSRule/Host/HostHelper.cs
- src/PSRule/Runtime/RunspaceContext.cs
- Fixed scope handling issue for rules.
Fixes #1214 
> Fixes lost scope for rules #1214

- docs/CHANGELOG-v2.md
What's changed since v2.3.1:
- Bug fixes:
- Fixes lost scope for rules by @BernieWhite.
[#1214](https://github.com/microsoft/PSRule/issues/1214)
> Release v2.3.2

- docs/CHANGELOG-v2.md
- src/PSRule/Commands/InvokeRuleBlockCommand.cs
- src/PSRule/Commands/NewRuleDefinitionCommand.cs
- src/PSRule/Definitions/Resource.cs
- src/PSRule/Host/HostHelper.cs
- src/PSRule/Runtime/RunspaceContext.cs
> Merge changes from patch release v2.3.2

- docs/CHANGELOG-v2.md
What's changed since v2.3.2:
- Engineering:
- Bump support projects to .NET 6 by @BernieWhite.
[#1209](https://github.com/microsoft/PSRule/issues/1209)
- Bump Microsoft.NET.Test.Sdk to v17.3.0.
[#1213](https://github.com/microsoft/PSRule/pull/1208)
- Bug fixes:
- Fixed repository information not in output by @BernieWhite.
[#1219](https://github.com/microsoft/PSRule/issues/1219)
> Pre-release v2.4.0-B0009

- PSRule.sln
- docs/CHANGELOG-v2.md
- src/PSRule.SDK/PSRule.SDK.csproj
- src/PSRule.Tool/ClientBuilder.cs
- src/PSRule.Tool/ClientHelper.cs
- src/PSRule.Tool/ClientHost.cs
- src/PSRule.Tool/PSRule.Tool.csproj
- src/PSRule.Tool/Resources/CmdStrings.Designer.cs
- src/PSRule.Tool/Resources/CmdStrings.resx
- src/PSRule.Tool/RestoreOptions.cs
- src/PSRule.Types/Data/ModuleConstraint.cs
- src/PSRule.Types/Data/SemanticVersion.cs
- src/PSRule.Types/PSRule.Types.csproj
- src/PSRule.Types/Properties/AssemblyInfo.cs
- src/PSRule.Types/README.md
- src/PSRule/Commands/NewRuleDefinitionCommand.cs
- src/PSRule/Common/EnvironmentHelper.cs
- src/PSRule/Configuration/BaselineOption.cs
- src/PSRule/Configuration/RequiresOption.cs
- src/PSRule/Definitions/Expressions/LanguageExpressions.cs
- src/PSRule/PSRule.csproj
- src/PSRule/Pipeline/CommandLineBuilder.cs
- src/PSRule/Pipeline/ModulePathComparer.cs
- src/PSRule/Pipeline/PipelineBuilder.cs
- src/PSRule/Pipeline/SourcePipeline.cs
- src/PSRule/Resources/PSRuleResources.Designer.cs
- src/PSRule/Resources/PSRuleResources.resx
- src/PSRule/Runtime/Assert.cs
- tests/PSRule.Tests/ModulePathComparerTests.cs
- tests/PSRule.Tests/SemanticVersionTests.cs
- Updates to PSRule engine API.
- Added tool support for baselines parameter.
- Added module path discovery.
- Added output for verbose and debug messages.
Related to #1152 
> Updates to PSRule engine API #1152

- docs/CHANGELOG-v2.md
What's changed since pre-release v2.4.0-B0009:
- Engineering:
- Updates to PSRule engine API by @BernieWhite.
[#1152](https://github.com/microsoft/PSRule/issues/1152)
- Added tool support for baselines parameter.
- Added module path discovery.
- Added output for verbose and debug messages.
> Pre-release v2.4.0-B0022

- docs/CHANGELOG-v2.md
- src/PSRule/Common/JsonConverters.cs
- src/PSRule/Common/JsonReaderExtensions.cs
- src/PSRule/Definitions/SpecFactory.cs
- src/PSRule/Host/HostHelper.cs
- tests/PSRule.Tests/Baseline.Rule.jsonc
- tests/PSRule.Tests/Baseline.Rule.yaml
- tests/PSRule.Tests/BaselineTests.cs
Fixes exception on JSON baseline without a synopsis.
Fixes #1230 
> Fixes exception on resource without synopsis #1230

- docs/CHANGELOG-v2.md
What's changed since pre-release v2.4.0-B0022:
- **Experimental**: Added support for functions within YAML and JSON expressions.
[#1227](https://github.com/microsoft/PSRule/issues/1227)
- Added conversion functions `boolean`, `string`, and `integer`.
- Added lookup functions `configuration`, and `path`.
- Added string functions `concat`, `substring`.
- Bug fixes:
- Fixed reporting of duplicate identifiers which were not generating an error for all cases by @BernieWhite.
[#1229](https://github.com/microsoft/PSRule/issues/1229)
- Added `Execution.DuplicateResourceId` option to configure PSRule behaviour.
- By default, duplicate resource identifiers return an error.
- Fixed exception on JSON baseline without a synopsis by @BernieWhite. …
> Pre-release v2.4.0-B0039

- docs/CHANGELOG-v2.md
- docs/analysis-output.md
- docs/creating-your-pipeline.md
- docs/install-instructions.md
- Additional minor updates to documentation.
> Minor documentation updates

- docs/CHANGELOG-v2.md
- src/PSRule/Configuration/BannerFormat.cs
- src/PSRule/Configuration/BaselineOption.cs
- src/PSRule/Configuration/PSRuleOption.cs
- src/PSRule/Configuration/PipelineHook.cs
- src/PSRule/Configuration/ResultFormat.cs
- src/PSRule/Data/ITargetInfo.cs
- src/PSRule/Data/ITargetIssueCollection.cs
- src/PSRule/Data/InputFileInfo.cs
- src/PSRule/Definitions/Baselines/Baseline.cs
- src/PSRule/Definitions/Resource.cs
- src/PSRule/Definitions/ResourceId.cs
- src/PSRule/Definitions/Rules/Rule.cs
- src/PSRule/Definitions/Rules/RuleFilter.cs
- src/PSRule/Definitions/Selectors/Selector.cs
- src/PSRule/Definitions/Spec.cs
- src/PSRule/Definitions/SuppressionGroups/SuppressionGroup.cs
- src/PSRule/Definitions/SuppressionGroups/SuppressionGroupVisitor.cs
- src/PSRule/Pipeline/HostContext.cs
- src/PSRule/Pipeline/InvokePipelineBuilder.cs
- src/PSRule/Pipeline/OptionContext.cs
- src/PSRule/Pipeline/PipelineBuilder.cs
- src/PSRule/Pipeline/PipelineHookActions.cs
- src/PSRule/Pipeline/SourcePipeline.cs
- src/PSRule/Rules/SuppressionFilter.cs
- src/PSRule/Runtime/Assert.cs
- src/PSRule/Runtime/AssertResult.cs
- src/PSRule/Runtime/ObjectPath/PathExpression.cs
- tests/PSRule.Tests/TargetBinderTests.cs
- Improvements to PSRule engine API documentation.
Related to #1186
> Updates to PSRule engine API documentation #1186

- docs/about.md
- docs/analysis-output.md
- docs/authoring/testing-infrastructure.md
- docs/authoring/using-expressions.md
- docs/creating-your-pipeline.md
- docs/expressions/functions.md
- docs/expressions/sub-selectors.md
- docs/faq.md
- docs/features.md
- docs/install-instructions.md
- docs/license-contributing.md
- docs/support.md
- docs/upgrade-notes.md
- docs/validating-locally.md
- mkdocs.yml
- overrides/main.html
> Additional minor updates to documentation

- docs/CHANGELOG-v2.md
What's changed since pre-release v2.4.0-B0039:
- **Experimental**: Added support for sub-selector YAML and JSON expressions by @BernieWhite.
[#1024](https://github.com/microsoft/PSRule/issues/1024)
[#1045](https://github.com/microsoft/PSRule/issues/1045)
- Sub-selector pre-conditions add an additional expression to determine if a rule is executed.
- Sub-selector object filters provide an way to filter items from list properties.
- See [sub-selectors][4] for more information.
- Engineering:
- Improvements to PSRule engine API documentation by @BernieWhite.
[#1186](https://github.com/microsoft/PSRule/issues/1186)
> Pre-release v2.4.0-B0063

- schemas/PSRule-options.schema.json
> Minor snippet improvement

- docs/CHANGELOG-v2.md
What's changed since v2.4.0:
- Engineering:
- Bump Microsoft.NET.Test.Sdk to v17.3.1.
[#1248](https://github.com/microsoft/PSRule/pull/1248)
- Bug fixes:
- Fixed could not load Microsoft.Management.Infrastructure by @BernieWhite.
[#1249](https://github.com/microsoft/PSRule/issues/1249)
- To use minimal initial session state set `Execution.InitialSessionState` to `Minimal`.
- Fixed unhandled exception with GetRootedPath by @BernieWhite.
[#1251](https://github.com/microsoft/PSRule/issues/1251)
> Pre-release v2.5.0-B0004

- .azure-pipelines/azure-pipelines.yaml
- Update CI process to use latest container/ OS versions for testing.
> Update CI to use latest container versions

- docs/CHANGELOG-v2.md
- src/PSRule.BuildTask/Generators/EngineVersionGenerator.cs
- src/PSRule.Tool/ClientHelper.cs
- src/PSRule.Tool/Properties/launchSettings.json
- src/PSRule/Host/HostHelper.cs
- src/PSRule/Pipeline/AssertPipeline.cs
- src/PSRule/Pipeline/InvokePipelineBuilder.cs
- src/PSRule/Pipeline/Output/SarifOutputWriter.cs
- src/PSRule/Pipeline/PipelineBuilder.cs
- src/PSRule/Runtime/RunspaceContext.cs
- Added method to unblock files from a trusted publisher.
Fixes #1261 
> Provide unblock for command line tools #1261

- docs/CHANGELOG-v2.md
What's changed since pre-release v2.5.0-B0004:
- Provide unblock for command line tools by @BernieWhite.
[#1261](https://github.com/microsoft/PSRule/issues/1261)
> Pre-release v2.5.0-B0015

- ps-rule.yaml
- Suppress erroring file using bugfix #1269.
> Ignore docker file until fixed in #1269

- docs/CHANGELOG-v2.md
- docs/concepts/grouping-rules.md
- mkdocs.yml
- schemas/PSRule-language.schema.json
- src/PSRule/Commands/NewRuleDefinitionCommand.cs
- src/PSRule/Common/DictionaryExtensions.cs
- src/PSRule/Common/ExpressionHelpers.cs
- src/PSRule/Common/HashtableExtensions.cs
- src/PSRule/Common/JsonConverters.cs
- src/PSRule/Common/JsonReaderExtensions.cs
- src/PSRule/Common/YamlConverters.cs
- src/PSRule/Configuration/RuleOption.cs
- src/PSRule/Definitions/Conventions/ScriptBlockConvention.cs
- src/PSRule/Definitions/Resource.cs
- src/PSRule/Definitions/Rules/RuleFilter.cs
- src/PSRule/Host/HostHelper.cs
- src/PSRule/PSRule.psm1
- src/PSRule/Pipeline/OptionContext.cs
- src/PSRule/Rules/Rule.cs
- src/PSRule/Rules/RuleBlock.cs
- tests/PSRule.Tests/Baseline.Rule.jsonc
- tests/PSRule.Tests/Baseline.Rule.yaml
- tests/PSRule.Tests/BaselineTests.cs
- tests/PSRule.Tests/FromFile.Rule.jsonc
- tests/PSRule.Tests/FromFile.Rule.yaml
- tests/PSRule.Tests/FromFileBaseline.Rule.ps1
- tests/PSRule.Tests/PSRule.Baseline.Tests.ps1
- tests/PSRule.Tests/RuleFilterTests.cs
-  Added taxa metadata from grouping and filtering rules.
Fixes #1272
> Added taxa for grouping rules #1272

- docs/CHANGELOG-v2.md
- src/PSRule/Runtime/Assert.cs
- tests/PSRule.Tests/AssertTests.cs
- tests/PSRule.Tests/PSRule.Tests.csproj
- tests/PSRule.Tests/jenkinsfile
- Fixed Dockerfile case sensitivity.
Fixes #1269 
> Fixes Dockerfile case senstivity #1269

- docs/CHANGELOG-v2.md
What's changed since v2.4.0:
- Bug fixes:
- Fixed markdown parsing of Spanish translated help fails by @BernieWhite @jonathanruiz.
[#1286](https://github.com/microsoft/PSRule/issues/1286)
[#1285](https://github.com/microsoft/PSRule/pull/1285)
> Release v2.4.1

- docs/CHANGELOG-v2.md
- docs/concepts/grouping-rules.md
- schemas/PSRule-language.schema.json
- src/PSRule/Commands/NewRuleDefinitionCommand.cs
- src/PSRule/Configuration/RuleOption.cs
- src/PSRule/Definitions/Conventions/ScriptBlockConvention.cs
- src/PSRule/Definitions/Resource.cs
- src/PSRule/Definitions/Rules/RuleFilter.cs
- src/PSRule/Host/HostHelper.cs
- src/PSRule/PSRule.psm1
- src/PSRule/Pipeline/OptionContext.cs
- src/PSRule/Rules/Rule.cs
- src/PSRule/Rules/RuleBlock.cs
- tests/PSRule.Tests/Baseline.Rule.jsonc
- tests/PSRule.Tests/Baseline.Rule.yaml
- tests/PSRule.Tests/BaselineTests.cs
- tests/PSRule.Tests/FromFile.Rule.jsonc
- tests/PSRule.Tests/FromFile.Rule.yaml
- tests/PSRule.Tests/FromFileBaseline.Rule.ps1
- tests/PSRule.Tests/RuleFilterTests.cs
- Renames taxa to labels to reduce complexity with the terminology. #1272
> Rename taxa to labels #1272

- docs/CHANGELOG-v2.md
Merge change log update from patch v2.4.1.
> Merge change log from patch v2.4.1 (#1289)

- docs/CHANGELOG-v2.md
What's changed since pre-release v2.5.0-B0015:
- **Experimental**: Added support for only processing changed files by @BernieWhite.
[#688](https://github.com/microsoft/PSRule/issues/688)
- To ignore unchanged files, set the `Input.IgnoreUnchangedPath` option to `true`.
- Added labels metadata from grouping and filtering rules by @BernieWhite.
[#1272](https://github.com/microsoft/PSRule/issues/1272)
- Labels are metadata that extends on tags to provide a more structured way to group rules.
- Rules can be classified by setting the `metadata.labels` property or `-Labels` parameter.
- Bug fixes:
- Fixed Dockerfile case sensitivity by @BernieWhite.
[#1269](https://github.com/microsoft/PSRule/issues/1269)
- Fixed markdown parsing of Spanish translated …
> Pre-release v2.5.0-B0045

- .devcontainer/Dockerfile
- .devcontainer/container-build.ps1
- .devcontainer/container-start.ps1
- .devcontainer/devcontainer.json
- .vscode/settings.json
- .vscode/tasks.json
- pipeline.build.ps1
- scripts/dependencies.psm1
- Updated tasks and vscode settings.
> Update tasks and vscode settings

- docs/CHANGELOG-v0.md
- docs/CHANGELOG-v1.md
- docs/CHANGELOG-v2.md
- docs/about.md
- docs/addon-modules.md
- docs/deprecations.md
- docs/features.md
- docs/license-contributing.md
- docs/related-projects.md
- docs/support.md
- docs/upgrade-notes.md
- docs/versioning.md
- mkdocs.yml
- overrides/main.html
- overrides/partials/giscus.html
> Add feedback for pages with Giscus

- tests/PSRule.Tests/InputPathBuilderTests.cs
> Fix CI test

- docs/CHANGELOG-v2.md
What's changed since v2.4.1:
- Bug fixes:
- Fixed exception with `PathExpressionBuilder.GetAllRecurse` by @BernieWhite.
[#1301](https://github.com/microsoft/PSRule/issues/1301)
> Release v2.4.2

- docs/CHANGELOG-v2.md
What's changed since pre-release v2.5.0-B0045:
- Bug fixes:
- Fixed exception with `PathExpressionBuilder.GetAllRecurse` by @BernieWhite.
[#1301](https://github.com/microsoft/PSRule/issues/1301)
> Pre-release v2.5.0-B0080

- README.md
Implemented a summary in the repository readme to ease getting information and improve the readability. It will also be useful to improve the accessibility of screen readers, since in addition to the table of contents, options to return to the table of contents have been implemented at important points where information is finalized.
> Improved readme accessibility and usability

- docs/analysis-output.md
- docs/creating-your-pipeline.md
- docs/install-instructions.md
- docs/scenarios/containers/container-execution.md
- Additional updates to documentation.
> Update creating your pipeline and docs

- .azure-pipelines/azure-pipelines.yaml
- docs/CHANGELOG-v2.md
- src/PSRule/Runtime/ObjectPath/PathExpressionBuilder.cs
- tests/PSRule.Tests/AssertTests.cs
- Fixed `In` with array source object and dot object path.
Fixes #1314
> Fixed In with array source #1314

- .github/workflows/analyze.yaml
- .github/workflows/dependencies.yaml
- .github/workflows/docs.yaml
- .github/workflows/first-interaction.yaml
- .github/workflows/stale.yaml
- Remove permissions from root scope.
> Further scope workflow permissions

- docs/CHANGELOG-v2.md
What's changed since v2.5.0:
- Bug fixes:
- Fixed `In` with array source object and dot object path by @BernieWhite.
[#1314](https://github.com/microsoft/PSRule/issues/1314)
> Release v2.5.1

- docs/CHANGELOG-v2.md
- src/PSRule/Pipeline/Output/NUnit3OutputWriter.cs
- src/PSRule/Pipeline/Output/OutputStringWriter.cs
- tests/PSRule.Tests/OutputWriterTests.cs
- Fixed incorrect XML header for encoding.
Fixes #1322 
> Fixes incorrect XML header for encoding #1322

- docs/CHANGELOG-v2.md
What's changed since v2.5.2:
- Bug fixes:
- Fixed incorrect XML header for encoding by @BernieWhite.
[#1322](https://github.com/microsoft/PSRule/issues/1322)
> Release v2.5.3

- docs/CHANGELOG-v2.md
- src/PSRule.Types/Data/SemanticVersion.cs
- src/PSRule/Definitions/IDependencyTarget.cs
- src/PSRule/Pipeline/Output/NUnit3OutputWriter.cs
- src/PSRule/Pipeline/PipelineWriter.cs
- Class clean up and documentation.
Working towards #1186.
> Class clean up and docs #1186

- docs/CHANGELOG-v2.md
What's changed since v2.5.3:
- Engineering:
- Bump Microsoft.NET.Test.Sdk to v17.3.2.
[#1283](https://github.com/microsoft/PSRule/pull/1283)
- Bump PSScriptAnalyzer to v1.21.0.
[#1318](https://github.com/microsoft/PSRule/pull/1318)
- Class clean up and documentation by @BernieWhite.
[#1186](https://github.com/microsoft/PSRule/issues/1186)
> Pre-release v2.6.0-B0013

- docs/CHANGELOG-v2.md
What's changed since pre-release v2.6.0-B0013:
- Added support for generating job summaries by @BernieWhite.
[#1264](https://github.com/microsoft/PSRule/issues/1264)
- Job summaries provide a markdown output for pipelines in addition to other supported output formats.
- To use, configure the `Output.JobSummaryPath` option.
- Added support for time bound suppression groups by @BernieWhite.
[#1335](https://github.com/microsoft/PSRule/issues/1335)
- Suppression groups can be configured to expire after a specified time by setting the `spec.expiresOn` property.
- When a suppression group expires, the suppression group will generate a warning by default.
- Configure the `Execution.SuppressionGroupExpired` option to ignore or error on expired suppression groups.
- Engineering:
- …
> Pre-release v2.6.0-B0034

- docs/CHANGELOG-v2.md
What's changed since v2.6.0:
- Bug fixes:
- Fixes exception calling `RuleSource` value cannot be null by @BernieWhite.
[#1343](https://github.com/microsoft/PSRule/issues/1343)
> Pre-release v2.7.0-B0001

- docs/CHANGELOG-v2.md
- src/PSRule/Common/JsonConverters.cs
- tests/PSRule.Tests/Baseline.Rule.jsonc
- tests/PSRule.Tests/Baseline.Rule.yaml
- tests/PSRule.Tests/SelectorTests.cs
- tests/PSRule.Tests/Selectors.Rule.jsonc
- tests/PSRule.Tests/Selectors.Rule.yaml
- Improve handling and test cases for handling of comments in JSON baselines.
Fixes #1336
> Fixes comment handling is baselines #1336

- README.md
- docs/CHANGELOG-v2.md
- docs/concepts/PSRule/en-US/about_PSRule_Expressions.md
- docs/concepts/PSRule/en-US/about_PSRule_Variables.md
- schemas/PSRule-language.schema.json
- src/PSRule/Common/PSObjectExtensions.cs
- src/PSRule/Data/ITargetSourceCollection.cs
- src/PSRule/Data/RepositoryInfo.cs
- src/PSRule/Definitions/Expressions/LanguageExpressions.cs
- src/PSRule/Pipeline/PipelineHookActions.cs
- src/PSRule/Pipeline/TargetObject.cs
- src/PSRule/Runtime/LanguageScope.cs
- src/PSRule/Runtime/Operand.cs
- src/PSRule/Runtime/PSRule.cs
- src/PSRule/Runtime/PSRuleMemberInfo.cs
- tests/PSRule.Tests/SelectorTests.cs
- tests/PSRule.Tests/Selectors.Rule.jsonc
- tests/PSRule.Tests/Selectors.Rule.yaml
- tests/PSRule.Tests/SuppressionGroupTests.cs
- tests/PSRule.Tests/SuppressionGroups.Rule.jsonc
- tests/PSRule.Tests/SuppressionGroups.Rule.yaml
- Added support target scope.
Fixes #1350 
> Add support for target scope #1350

- docs/CHANGELOG-v2.md
What's changed since pre-release v2.7.0-B0001:
- Added support target scope by @BernieWhite.
[#1350](https://github.com/microsoft/PSRule/issues/1350)
- Bug fixes:
- Fixed exception with comments in JSON baselines by @BernieWhite.
[#1336](https://github.com/microsoft/PSRule/issues/1336)
> Pre-release v2.7.0-B0006

- .azure-pipelines/azure-pipelines.yaml
- docs/CHANGELOG-v2.md
- src/PSRule/Pipeline/PipelineContext.cs
- src/PSRule/Rules/PowerShellCondition.cs
- src/PSRule/Runtime/LanguageScriptBlock.cs
- Fixed handling of constrained language mode with PowerShell 7.3.
Fixes #1348 
> Fixes constrained language mode with PS 7.3 #1348

- docs/CHANGELOG-v2.md
- src/PSRule/Pipeline/Output/JobSummaryWriter.cs
- tests/PSRule.Tests/OutputWriterTests.cs
-  Fixed job summary directory creation.
Fixes #1353 
> Fixes job summary directory creation #1353

- docs/CHANGELOG-v2.md
- src/PSRule/Definitions/DependencyTargetCollection.cs
- tests/PSRule.Tests/FromFile.Json.schema.json
- tests/PSRule.Tests/FromFile.Rule.jsonc
- tests/PSRule.Tests/FromFile.Rule.yaml
- tests/PSRule.Tests/FromFileAlias.Rule.jsonc
- tests/PSRule.Tests/RulesTests.cs
- Fixed same key for ref and name.
Fixes #1354 
> Fixes same key for ref and name #1354

- docs/CHANGELOG-v2.md
What's changed since pre-release v2.7.0-B0006:
- Bug fixes:
- Fixed job summary directory creation by @BernieWhite.
[#1353](https://github.com/microsoft/PSRule/issues/1353)
- Fixed same key for ref and name by @BernieWhite
[#1354](https://github.com/microsoft/PSRule/issues/1354)
> Release v2.7.0-B0016

- docs/CHANGELOG-v2.md
What's changed since pre-release v2.7.0-B0016:
- Added API version date comparison assertion method and expression by @BernieWhite.
[#1356](https://github.com/microsoft/PSRule/issues/1356)
[#1227](https://github.com/microsoft/PSRule/issues/1227)
- Added support for `trim`, `replace`, `split`, `first`, and `last`.
- Bug fixes:
- Fixes CLI failed to load required assemblies by @BernieWhite.
[#1361](https://github.com/microsoft/PSRule/issues/1361)
- Fixes CLI ignores modules specified in `Include.Modules` by @BernieWhite.
[#1362](https://github.com/microsoft/PSRule/issues/1362)
> Pre-release v2.7.0-B0031

- docs/CHANGELOG-v2.md
- src/PSRule/Common/JsonConverters.cs
- src/PSRule/Common/JsonReaderExtensions.cs
- src/PSRule/Resources/PSRuleResources.Designer.cs
- src/PSRule/Resources/PSRuleResources.resx
- tests/PSRule.Tests/FromFile.Rule.jsonc
- tests/PSRule.Tests/FromFile.Rule.yaml
- Fixed loop stuck parsing JSON allOf not rule condition.
Fixes #1370 
> Fixes loop stuck parsing JSON in rule #1370

- docs/CHANGELOG-v2.md
What's changed since pre-release v2.7.0-B0031:
- Bug fixes:
- Fixed loop stuck parsing JSON `allOf` `not` rule condition by @BernieWhite.
[#1370](https://github.com/microsoft/PSRule/issues/1370)
- Fixed handling of uint64 with `LessOrEqual` assertion method by @BernieWhite.
[#1366](https://github.com/microsoft/PSRule/issues/1366)
> Pre-release v2.7.0-B0049

- docs/CHANGELOG-v2.md
- src/PSRule/Host/HostHelper.cs
- tests/PSRule.Tests/FromFile.Rule.jsonc
- tests/PSRule.Tests/FromFile.Rule.yaml
- tests/PSRule.Tests/RulesTests.cs
- Fixed rule annotations are not included from YAML/ JSON definition.
Fixes #1378
> Fixes rule annotation from definition #1378

- docs/CHANGELOG-v2.md
What's changed since pre-release v2.7.0-B0049:
- Bug fixes:
- Fixed object path fails to iterate JSON object with wildcard selector by @BernieWhite.
[#1376](https://github.com/microsoft/PSRule/issues/1376)
- Fixed rule annotations are not included from YAML/ JSON definition by @BernieWhite.
[#1378](https://github.com/microsoft/PSRule/issues/1378)
> Pre-release v2.7.0-B0070

- docs/CHANGELOG-v2.md
- docs/authoring/writing-rule-help.md
- docs/hooks.py
- schemas/PSRule-language.schema.json
- src/PSRule/Commands/NewRuleDefinitionCommand.cs
- src/PSRule/Common/ResourceHelpInfoExtensions.cs
- src/PSRule/Definitions/IResourceHelpInfo.cs
- src/PSRule/Definitions/InfoString.cs
- src/PSRule/Definitions/Resource.cs
- src/PSRule/Definitions/Rules/Rule.cs
- src/PSRule/Definitions/SpecFactory.cs
- src/PSRule/Host/HostHelper.cs
- src/PSRule/Rules/Rule.cs
- src/PSRule/Rules/RuleBlock.cs
- src/PSRule/Rules/RuleHelpInfo.cs
- tests/PSRule.Tests/FromFile.Rule.jsonc
- tests/PSRule.Tests/FromFile.Rule.yaml
- tests/PSRule.Tests/RulesTests.cs
- Added help properties to rules from YAML/ JSON resources.
Fixes #1386 
> Added help properties to rule #1386

- docs/CHANGELOG-v2.md
What's changed since pre-release v2.7.0-B0070:
- Added support for `hasValue` expression with `scope` by @BernieWhite.
[#1382](https://github.com/microsoft/PSRule/issues/1382)
- Return target object scope as an array by @BernieWhite.
[#1383](https://github.com/microsoft/PSRule/issues/1383)
- Improve support of string comparisons to support an array of strings by @BernieWhite.
[#1384](https://github.com/microsoft/PSRule/issues/1384)
- Added help properties to rules from YAML/ JSON resources by @BernieWhite.
[#1386](https://github.com/microsoft/PSRule/issues/1386)
- Engineering:
- Bump Newtonsoft.Json to v13.0.2.
[#1358](https://github.com/microsoft/PSRule/pull/1358)
- Bump System.Drawing.Common to v7.0.0.
[#1332](https://github.com/microsoft/PSRule/pull/1332)
- Bump …
> Pre-release v2.7.0-B0097

- docs/CHANGELOG-v2.md
What's changed since pre-release v2.7.0-B0097:
- Bug fixes:
- Fixed null reference for link property by @BernieWhite.
[#1393](https://github.com/microsoft/PSRule/issues/1393)
- Fixed reason are emitted for pre-condition sub-selectors by @BernieWhite.
[#1394](https://github.com/microsoft/PSRule/issues/1394)
> Pre-release v2.7.0-B0126

- docs/CHANGELOG-v2.md
- tests/PSRule.Tests/AssertTests.cs
- Fixes handling of numerics in tests for that are impacted by regional format.
Fixes #1405
> Fixes dot numeric separator in tests #1405

- docs/concepts/PSRule/en-US/about_PSRule_Options.md
- docs/faq.md
- Added additional FAQ entries.
> Updates to FAQ

- README.md
- docs/versioning.md
> Minor updates to readme

- .devcontainer/Dockerfile
- .devcontainer/container-build.ps1
- docs/analysis-output.md
- docs/creating-your-pipeline.md
- docs/install-instructions.md
- docs/troubleshooting.md
- mkdocs.yml
- Updates to docs relating to self-hosted agents/ runners and NuGet provider.
- Additional updates to dev container config.
Fixes #1443
> Add NuGet provider notes #1443

- docs/CHANGELOG-v2.md
- schemas/PSRule-options.schema.json
- Added additional options to schema for PSRule for Azure.
Fixes #1446 
> Add PSRule for Azure options #1446

- .github/dependabot.yml
- docs/CHANGELOG-v2.md
- docs/troubleshooting.md
- src/PSRule/Configuration/PSRuleOption.cs
- src/PSRule/Pipeline/Exceptions.cs
- src/PSRule/Resources/PSRuleResources.Designer.cs
- src/PSRule/Resources/PSRuleResources.resx
- Improved error message for failing to read options file.
Fixes #1433 
> Improved error for failing to read options #1433

- docs/CHANGELOG-v2.md
- docs/concepts/PSRule/en-US/about_PSRule_Variables.md
- src/PSRule/Pipeline/PipelineReader.cs
- src/PSRule/Pipeline/TargetBinder.cs
- src/PSRule/Pipeline/TargetObject.cs
- src/PSRule/Runtime/PSRule.cs
- tests/PSRule.Tests/FromFileConventions.Rule.ps1
- tests/PSRule.Tests/PSRule.Conventions.Tests.ps1
- tests/PSRule.Tests/TargetBinderTests.cs
- Added support for import within initialize block.
- Added direct typing on import.
Fixes #1448 
Fixes #1449
> Add import on initialize and with type #1448 #1449

- docs/install-instructions.md
- mkdocs.yml
- Add docs for using release branches.
Fixes #1431
> Add docs for release branches #1431

- docs/CHANGELOG-v2.md
What's changed since v2.7.0:
- **Important change**: Replaced `SuppressedRuleWarning` execution option with `RuleSuppressed` by @BernieWhite.
[#1456](https://github.com/microsoft/PSRule/issues/1456)
- Improved options for output of suppressed rules with `RuleSuppressed` option.
- Deprecated `SuppressedRuleWarning` option, which will be removed in v3.
- Added support for logging excluded rules by @BernieWhite.
[#1432](https://github.com/microsoft/PSRule/issues/1432)
- Added additional options to schema for PSRule for Azure by @BernieWhite.
[#1446](https://github.com/microsoft/PSRule/issues/1446)
- Improved error message for failing to read options file by @BernieWhite.
[#1433](https://github.com/microsoft/PSRule/issues/1433)
- Added support for import within …
> Pre-release v2.8.0-B0034

- docs/CHANGELOG-v2.md
- docs/specs/option-spec.md
- src/PSRule/Commands/InvokeRuleBlockCommand.cs
- src/PSRule/Common/LoggerExtensions.cs
- src/PSRule/Common/RunspaceContextDiagnosticExtensions.cs
- src/PSRule/Definitions/Expressions/ExpressionContext.cs
- src/PSRule/Definitions/Expressions/LanguageExpressions.cs
- src/PSRule/Host/HostHelper.cs
- src/PSRule/Host/RuleLanguageAst.cs
- src/PSRule/Pipeline/IBindingOption.cs
- src/PSRule/Pipeline/InvokeRulePipeline.cs
- src/PSRule/Pipeline/OptionContext.cs
- src/PSRule/Pipeline/OptionContextBuilder.cs
- src/PSRule/Pipeline/PipelineContext.cs
- src/PSRule/Pipeline/TargetBinder.cs
- src/PSRule/Runtime/ILogger.cs
- src/PSRule/Runtime/LanguageScope.cs
- src/PSRule/Runtime/RunspaceContext.cs
- tests/PSRule.Tests/BaselineTests.cs
- tests/PSRule.Tests/FunctionBuilderTests.cs
- tests/PSRule.Tests/ModuleConfigTests.cs
- tests/PSRule.Tests/OptionContextTests.cs
- tests/PSRule.Tests/PSRule.EndToEnd.Tests.ps1
- tests/PSRule.Tests/PSRuleOptionTests.cs
- tests/PSRule.Tests/RulesTests.cs
- tests/PSRule.Tests/SelectorTests.cs
- tests/PSRule.Tests/SuppressionGroupTests.cs
- tests/PSRule.Tests/TargetBinderTests.cs
- Fixed problem binding when not set locally.
Fixes #1473 
> Fixed problem when binding not set locally #1473

- docs/CHANGELOG-v2.md
What's changed since pre-release v2.8.0-B0121:
- Added support for case sensitivity matching with `match` and `notMatch` expressions by @BernieWhite.
[#1480](https://github.com/microsoft/PSRule/issues/1480)
- Bug fixes:
- Fixed no output with using job summary with as summary by @BernieWhite.
[#1483](https://github.com/microsoft/PSRule/issues/1483)
- Fixed output and added error for unsupported scenarios.
> Pre-release v2.8.0-B0171

- docs/CHANGELOG-v2.md
- src/PSRule/Common/RunspaceContextDiagnosticExtensions.cs
- src/PSRule/Resources/PSRuleResources.Designer.cs
- src/PSRule/Resources/PSRuleResources.resx
- tests/PSRule.Tests/PipelineTests.cs
- Fixed wrong message for excluded rules.
Fixes #1493 
> Fixes wrong message for excluded rules #1493

- docs/CHANGELOG-v2.md
- src/PSRule/Pipeline/InvokeRulePipeline.cs
- src/PSRule/Pipeline/Output/JobSummaryWriter.cs
- tests/PSRule.Tests/OutputWriterTests.cs
- tests/PSRule.Tests/PSRule.Common.Tests.ps1
- Fixed job summary reports completed time.
Fixes #1492.
> Fixed job summary reports completed time #1492

- docs/CHANGELOG-v2.md
What's changed since release v2.8.0:
- Bug fixes:
- Fixed wrong message for excluded rules by @BernieWhite.
[#1493](https://github.com/microsoft/PSRule/issues/1493)
- Fixed job summary reports completed time by @BernieWhite.
[#1492](https://github.com/microsoft/PSRule/issues/1492)
> Release v2.8.1

- tests/PSRule.Tests/OutputWriterTests.cs
Fixes test for release pipeline preventing release of v2.8.1.
> Fix test for release pipeline

- docs/CHANGELOG-v2.md
- docs/concepts/PSRule/en-US/about_PSRule_Expressions.md
- schemas/PSRule-language.schema.json
- schemas/PSRule-options.schema.json
- schemas/PSRule-resources.schema.json
- src/PSRule/Definitions/Expressions/LanguageExpressions.cs
- tests/PSRule.Tests/SelectorTests.cs
- tests/PSRule.Tests/Selectors.Rule.jsonc
- tests/PSRule.Tests/Selectors.Rule.yaml
Merge fixes from patch v2.8.1:
- Bug fixes:
- Fixed wrong message for excluded rules by @BernieWhite.
[#1493](https://github.com/microsoft/PSRule/issues/1493)
- Fixed job summary reports completed time by @BernieWhite.
[#1492](https://github.com/microsoft/PSRule/issues/1492)
Fixes #1492 
Fixes #1493
> Merge patch v2.8.1

- SECURITY.md
- SUPPORT.md
> Updated docs files

- docs/CHANGELOG-v2.md
- src/PSRule/Pipeline/InvokePipelineBuilder.cs
- src/PSRule/Pipeline/PathBuilder.cs
- src/PSRule/Pipeline/PipelineWriterExtensions.cs
- src/PSRule/Resources/PSRuleResources.Designer.cs
- src/PSRule/Resources/PSRuleResources.resx
- tests/PSRule.Tests/InputPathBuilderTests.cs
- Fixed tool output on access denied to path.
Fixes #1490 
> Fixed tool output on access denied to path #1490

- docs/CHANGELOG-v2.md
- src/PSRule.Tool/ClientBuilder.cs
- src/PSRule.Tool/ClientHelper.cs
- src/PSRule.Tool/ClientHost.cs
- src/PSRule/Pipeline/AssertPipeline.cs
- src/PSRule/Pipeline/HostContext.cs
- src/PSRule/Pipeline/InvokeRulePipeline.cs
- src/PSRule/Pipeline/PipelineBuilder.cs
- src/PSRule/Pipeline/PipelineLogger.cs
- src/PSRule/Pipeline/PipelineWriter.cs
- src/PSRule/Pipeline/RulePipeline.cs
- tests/PSRule.Tests/InputPathBuilderTests.cs
- Fixed tool exit code on error or failure.
Fixes #1491 
> Fixes tool exist code on failure #1491

- ps-rule.yaml
> Analysis report successes

- ps-rule.yaml
Update CI to only include failed results in scan.
> Update SARIF result include

- docs/concepts/PSRule/en-US/about_PSRule_Conventions.md
- docs/creating-your-pipeline.md
> Updates to docs

- docs/CHANGELOG-v2.md
What's changed since pre-release v2.9.0-B0013:
- Added sub-selector quantifiers for `allOf` or `anyOf` operators by @BernieWhite.
[#1423](https://github.com/microsoft/PSRule/issues/1423)
- Quantifiers allow you to specify the number of matches with `count`, `less`, `lessOrEqual`, `greater`, or `greaterOrEqual`.
- See [Sub-selectors][4] for more information.
[#1422](https://github.com/microsoft/PSRule/issues/1422)
- Added support for `padLeft`, and `padRight`.
> Pre-release v2.9.0-B0033

- docs/CHANGELOG-v2.md
- src/PSRule.Types/PSRule.Types.csproj
- Bump YamlDotNet to v13.1.1
Fixes #1399
> Bump YamlDotNet to v13.1.1 #1399

- CHANGELOG.md
- docs/CHANGELOG-v2.md
- docs/CHANGELOG-v3.md
- mkdocs.yml
> Bump docs for v3

- src/PSRule.Types/Data/TargetSourceInfo.cs
- src/PSRule/Badges/BadgeBuilder.cs
- src/PSRule/Common/ExpressionHelpers.cs
- src/PSRule/Common/ExternalToolHelper.cs
- src/PSRule/Common/GitHelper.cs
- src/PSRule/Definitions/Expressions/LanguageExpressions.cs
- src/PSRule/Pipeline/PathBuilder.cs
- src/PSRule/Runtime/PSRule.cs
- tests/PSRule.Tests/AssertTests.cs
- tests/PSRule.Tests/BaselineTests.cs
- tests/PSRule.Tests/FunctionBuilderTests.cs
- tests/PSRule.Tests/ModuleConfigTests.cs
- tests/PSRule.Tests/ResourceValidatorTests.cs
- tests/PSRule.Tests/RulesTests.cs
- tests/PSRule.Tests/SelectorTests.cs
- tests/PSRule.Tests/SuppressionFilterTests.cs
- tests/PSRule.Tests/SuppressionGroupTests.cs
- tests/PSRule.Tests/Usings.cs
Refactoring to allow global usings of `Assert` and clean up.
> Update global usings in tests

- .github/workflows/docs.yaml
Update CI pipeline to publish v3 docs on main.
> Update CI to push v3 docs

- .devcontainer/devcontainer.json
- .vscode/extensions.json
Updates to configuration for working with dev containers.
> Update devcontainer configuration

- docs/assets/stylesheets/extra.css
Update the banner style on docs.
> Update banner style

- .github/PULL_REQUEST_TEMPLATE.md
- docs/analysis-output.md
- docs/concepts/baselines.md
- docs/creating-your-pipeline.md
- docs/install-instructions.md
> Bump version is docs

- src/PSRule.Types/Converters/TypeConverter.cs
- src/PSRule.Types/Converters/Yaml/StringArrayConverter.cs
- src/PSRule.Types/Converters/Yaml/StringArrayMapConverter.cs
- src/PSRule.Types/Data/DateVersion.cs
- src/PSRule.Types/Data/IFileInfo.cs
- src/PSRule.Types/Data/ITargetInfo.cs
- src/PSRule.Types/Data/InputFileInfo.cs
- src/PSRule.Types/Data/SemanticVersion.cs
- src/PSRule.Types/Data/StringArrayMap.cs
- src/PSRule.Types/Data/TargetIssueInfo.cs
- src/PSRule.Types/Data/TargetSourceInfo.cs
- src/PSRule.Types/DictionaryExtensions.cs
- src/PSRule.Types/Environment.cs
- src/PSRule.Types/Expressions/Helpers.cs
- src/PSRule.Types/Options/BaselineOption.cs
- src/PSRule.Types/Options/ExecutionOption.cs
- src/PSRule.Types/Options/IOption.cs
- src/PSRule.Types/Options/IOptionContext.cs
- src/PSRule.Types/PSRule.Types.csproj
- src/PSRule.Types/StringExtensions.cs
- src/PSRule/Common/RunspaceContextDiagnosticExtensions.cs
- src/PSRule/Runtime/Configuration.cs
- Code refactoring and update support for nullables.
> Refactoring options

- .vscode/settings.json
- docs/CHANGELOG-v3.md
- src/PSRule/Common/JsonConverters.cs
- src/PSRule/Configuration/PSRuleOption.cs
- src/PSRule/Definitions/ILanguageBlock.cs
- src/PSRule/Definitions/Resource.cs
- src/PSRule/Definitions/Rules/Rule.cs
- src/PSRule/Definitions/Rules/RuleVisitor.cs
- src/PSRule/Definitions/Selectors/SelectorVisitor.cs
- src/PSRule/PSRule.Format.ps1xml
- src/PSRule/PSRule.psm1
- src/PSRule/Pipeline/Output/JsonOutputWriter.cs
- src/PSRule/Pipeline/PipelineBuilder.cs
- src/PSRule/Pipeline/Source.cs
- src/PSRule/Rules/PowerShellCondition.cs
- src/PSRule/Rules/Rule.cs
- src/PSRule/Rules/RuleBlock.cs
- src/PSRule/Runtime/Assert.cs
- tests/PSRule.Tests/PSRule.Baseline.Tests.ps1
- tests/PSRule.Tests/PSRule.Common.Tests.ps1
- Remove deprecated object properties.
Fixes #1601 
> Remove deprecated object properties #1601

- docs/related-projects.md
Add a link to _PSRule.Rules.AzureDevOps_ in `related-projects.md`
This project uses PSRule to check an Azure DevOps project for some best practices.
> Add ref to PSRule.Rules.AzureDevOps to related projects

- docs/related-projects.md
- requirements-docs.txt
Updated related community projects.
> Update related projects

- .github/workflows/analyze.yaml
> Upload codeql SARIF

- .github/workflows/docs.yaml
- mkdocs.yml
- requirements-docs.txt
> Fix v2 doc publishing

- .github/workflows/docs.yaml
- mkdocs.yml
> Minor fixes for documentation links

- README.md
- SECURITY.md
> Updates to started repo files

- docs/CHANGELOG-v3.md
- src/PSRule.Tool/ClientHelper.cs
- src/PSRule/Pipeline/CommandLineBuilder.cs
- Fixed CLI IndexOutOfRangeException with lock file.
Fixes #1676 
> Fixed IndexOutOfRangeException on lock file #1676

- docs/CHANGELOG-v2.md
- docs/concepts/PSRule/en-US/about_PSRule_Options.md
- Added reference to PSRule version supporting the specified option.
- Added a reference to change log for additional option.
> Improvements to options doco

- docs/CHANGELOG-v3.md
What's changed since pre-release v3.0.0-B0093:
- **Breaking change:** Renamed `analyze` CLI command to `run` by @BernieWhite.
[#1713](https://github.com/microsoft/PSRule/issues/1713)
- Added `--outcome` argument for CLI to support filtering output by @bernieWhite.
[#1706](https://github.com/microsoft/PSRule/issues/1706)
- Engineering:
- Bump xunit to v2.6.3.
[#1699](https://github.com/microsoft/PSRule/pull/1699)
- Bump xunit.runner.visualstudio to v2.5.5.
[#1700](https://github.com/microsoft/PSRule/pull/1700)
- Bump Microsoft.NET.Test.Sdk to v17.8.0.
[#1659](https://github.com/microsoft/PSRule/pull/1659)
- Bump Microsoft.CodeAnalysis.NetAnalyzers to v8.0.0.
[#1674](https://github.com/microsoft/PSRule/pull/1674)
- Bump Microsoft.CodeAnalysis.Common to v4.8.0. …
> Pre-release v3.0.0-B0122

- docs/concepts/cli/index.md
- docs/concepts/cli/module.md
- docs/concepts/cli/run.md
- mkdocs.yml
- src/PSRule.Tool/ClientBuilder.cs
- src/PSRule.Tool/Resources/CmdStrings.Designer.cs
- src/PSRule.Tool/Resources/CmdStrings.resx
> Improvements to CLI docs and help

- .vscode/settings.json
- README.md
- docs/CHANGELOG-v3.md
- docs/concepts/PSRule/en-US/about_PSRule_Options.md
- schemas/PSRule-options.schema.json
- src/PSRule.Badges/BadgeResources.cs
- src/PSRule.Types/Options/ExecutionActionPreference.cs
- src/PSRule.Types/Options/ExecutionOption.cs
- src/PSRule.Types/Options/LanguageMode.cs
- src/PSRule.Types/Options/RestrictScriptSource.cs
- src/PSRule.Types/Options/SessionState.cs
- src/PSRule/Host/HostHelper.cs
- src/PSRule/PSRule.psm1
- src/PSRule/Pipeline/InvokePipelineBuilder.cs
- src/PSRule/Pipeline/Output/SarifBuilder.cs
- src/PSRule/Pipeline/PipelineBuilder.cs
- src/PSRule/Pipeline/PipelineContext.cs
- src/PSRule/Pipeline/SourcePipeline.cs
- tests/PSRule.Tests/PSRule.Options.Tests.ps1
- tests/PSRule.Tests/PSRule.Tests.yml
- tests/PSRule.Tests/SourcePipelineBuilderTests.cs
- Added support to allow disabling PowerShell features that can be run from a repository.
Fixes #1742 
> Allow disabling PowerShell features #1742

- docs/CHANGELOG-v3.md
What's changed since pre-release v3.0.0-B0137:
- SARIF output has been improved to include effective configuration from a run by @BernieWhite.
[#1739](https://github.com/microsoft/PSRule/issues/1739)
- SARIF output has been improved to include file hashes for source files from a run by @BernieWhite.
[#1740](https://github.com/microsoft/PSRule/issues/1740)
- Added support to allow disabling PowerShell features that can be run from a repository by @BernieWhite.
[#1742](https://github.com/microsoft/PSRule/issues/1742)
- Added the `Execution.RestrictScriptSource` option to disable running scripts from a repository.
- Engineering:
- Bump YamlDotNet to v15.1.0.
[#1737](https://github.com/microsoft/PSRule/pull/1737)
> Pre-release v3.0.0-B0141

- docs/CHANGELOG-v3.md
- src/PSRule.Tool/Commands/ModuleCommand.cs
- src/PSRule/Pipeline/Dependencies/LockFile.cs
- tests/PSRule.Tool.Tests/CommandTests.cs
- Fixed CLI null reference when include module is undefined.
Fixes #1746
> Fixed null reference in CLI #1746

- docs/install.md
- mkdocs.yml
Minor updates to install docs.
> Updates to install docs

- docs/CHANGELOG-v3.md
What's changed since pre-release v3.0.0-B0141:
- Improved support for packaging with Visual Studio Code by @BernieWhite.
[#1755](https://github.com/microsoft/PSRule/issues/1755)
- Engineering:
- **Breaking change:** Bump development tools to .NET 8.0 SDK by @BernieWhite.
[#1673](https://github.com/microsoft/PSRule/pull/1673)
- Running PSRule from PowerShell 7.x is supported on 7.4 and above.
- Running PSRule from Windows PowerShell 5.1 is still supported but deprecated and will be removed in PSRule v4.
- Bump Microsoft.NET.Test.Sdk to v17.9.0.
[#1752](https://github.com/microsoft/PSRule/pull/1752)
- Bug fixes:
- Fixed CLI null reference when include module is undefined by @BernieWhite.
[#1746](https://github.com/microsoft/PSRule/issues/1746)
> Pre-release v3.0.0-B0151

- docs/concepts/baselines.md
- docs/concepts/cli/index.md
- docs/concepts/cli/module.md
- docs/concepts/cli/run.md
- docs/creating-your-pipeline.md
- docs/expressions/functions.md
- docs/expressions/sub-selectors.md
- docs/faq.md
- docs/features.md
- docs/install.md
- docs/license-contributing.md
- docs/troubleshooting.md
- docs/validating-locally.md
- docs/versioning.md
- src/PSRule.BuildTask/Generators/EngineVersionGenerator.cs
Updates and corrections to documentation.
> Fixes to documentation

- docs/CHANGELOG-v3.md
- src/PSRule.CommandLine/Commands/ModuleCommand.cs
- src/PSRule/Pipeline/Dependencies/LockFile.cs
> Additional fixes for #1746

- docs/CHANGELOG-v3.md
What's changed since pre-release v3.0.0-B0151:
- Bug fixes:
- Fixes null references for CLI module handling by @BernieWhite.
[#1746](https://github.com/microsoft/PSRule/issues/1746)
> Pre-release v3.0.0-B0153

- .github/workflows/analyze.yaml
- .github/workflows/build.yaml
- .github/workflows/dependencies.yaml
- .github/workflows/docs.yaml
- .vscode/extensions.json
- docs/CHANGELOG-v2.md
- docs/analysis-output.md
- docs/commands/PSRule/en-US/Get-PSRuleBaseline.md
- docs/commands/PSRule/en-US/Get-PSRuleHelp.md
- docs/concepts/baselines.md
- docs/creating-your-pipeline.md
- docs/expressions/functions.md
- docs/expressions/sub-selectors.md
- docs/faq.md
- docs/features.md
- docs/install.md
- docs/license-contributing.md
- docs/quickstart/standalone-rule.md
- docs/troubleshooting.md
- docs/validating-locally.md
- docs/versioning.md
- mkdocs.yml
- requirements-docs.txt
Merge latest documentation to stable release branch.
> Latest doc updates for v2.9.x

- .vscode/settings.json
- docs/analysis-output.md
- docs/creating-your-pipeline.md
- docs/install.md
Updates install docs with additional guidance around pinning.
> Update install docs

- .vscode/settings.json
- docs/CHANGELOG-v3.md
- src/PSRule.Tool/Program.cs
- src/PSRule.Tool/Properties/launchSettings.json
- src/PSRule.Types/Environment.cs
- src/PSRule/Pipeline/SourcePipeline.cs
- src/PSRule/Runtime/ObjectPath/PathExpressionBuilder.cs
- Fixed discovery of installed modules in CLI.
Fixes #1779
> Fixes CLI discovery of installed modules #1779

- src/PSRule.CommandLine/ClientContext.cs
- src/PSRule.CommandLine/Commands/ModuleCommand.cs
- src/PSRule.Types/Converters/TypeConverter.cs
- src/PSRule.Types/Data/IFileInfo.cs
- src/PSRule.Types/Data/IFileStream.cs
- src/PSRule.Types/Data/ITargetObject.cs
- src/PSRule.Types/Data/TargetSourceInfo.cs
- src/PSRule.Types/Options/InputFormat.cs
- src/PSRule/Common/YamlConverters.cs
- src/PSRule/Configuration/InputOption.cs
- src/PSRule/PSRule.psm1
- src/PSRule/Pipeline/GetTargetPipeline.cs
- src/PSRule/Pipeline/InvokePipelineBuilder.cs
- src/PSRule/Pipeline/PathFilter.cs
- src/PSRule/Pipeline/TargetObject.cs
- src/PSRule/Runtime/ObjectHelper.cs
- src/PSRule/Runtime/PSRule.cs
- src/PSRule/Runtime/PSRuleMemberInfo.cs
- tests/PSRule.Tests/PSRule.AllOf.Tests.ps1
- tests/PSRule.Tests/PipelineTests.cs
Refactoring and quality updates.
> Code refactoring and quality updates

- docs/troubleshooting.md
Update docs to reference issue for "Cannot process argument because the value of argument "name" is not valid."
Fixes #1723
> Add PS issue to docs #1723

- docs/CHANGELOG-v3.md
What's changed since pre-release v3.0.0-B0153:
- Engineering:
- Bump System.Drawing.Common to v8.0.4.
[#1790](https://github.com/microsoft/PSRule/pull/1790)
- Bump Bump xunit to v2.7.1.
[#1793](https://github.com/microsoft/PSRule/pull/1793)
- Bump xunit.runner.visualstudio to v2.5.8.
[#1792](https://github.com/microsoft/PSRule/pull/1792)
- Bump YamlDotNet to v15.1.2.
[#1771](https://github.com/microsoft/PSRule/pull/1771)
- Bump Microsoft.CodeAnalysis.Common to v4.9.2.
[#1773](https://github.com/microsoft/PSRule/pull/1773)
- Bug fixes:
- Fixed discovery of installed modules in CLI by @BernieWhite.
[#1779](https://github.com/microsoft/PSRule/issues/1779)
> Pre-release v3.0.0-B0179

- docs/CHANGELOG-v3.md
- docs/deprecations.md
- docs/upgrade-notes.md
- src/PSRule/Common/GitHelper.cs
- src/PSRule/Pipeline/GetTargetPipelineBuilder.cs
- src/PSRule/Pipeline/InvokePipelineBuilder.cs
- src/PSRule/Pipeline/PipelineReciever.cs
- tests/PSRule.Tests/GitHelperTests.cs
- Fixed for git head in tests.
Fixes #1801 
> Fixes for git head in tests #1801

- tests/PSRule.Tests/GitHelperTests.cs
> Fixes for .git tests

- tests/PSRule.Tests/GitHelperTests.cs
Update Git pathing for CI tests.
> Update git pathing for CI

- src/PSRule.Benchmark/packages.lock.json
- src/PSRule.Types/Environment.cs
- src/PSRule/Common/GitHelper.cs
- tests/PSRule.Tests/GitHelperTests.cs
Additional fixes for git pathing with submodules.
> Fixes for handing git paths

- docs/CHANGELOG-v3.md
What's changed since pre-release v3.0.0-B0153:
- Engineering:
- Bump System.Drawing.Common to v8.0.5.
[#1817](https://github.com/microsoft/PSRule/pull/1817)
- Bump Bump xunit to v2.8.0.
[#1809](https://github.com/microsoft/PSRule/pull/1809)
- Bump xunit.runner.visualstudio to v2.8.0.
[#1808](https://github.com/microsoft/PSRule/pull/1808)
- Bump YamlDotNet to v15.1.4.
[#1816](https://github.com/microsoft/PSRule/pull/1816)
- Bump Microsoft.CodeAnalysis.Common to v4.9.2.
[#1773](https://github.com/microsoft/PSRule/pull/1773)
- Bug fixes:
- Fixed discovery of installed modules in CLI by @BernieWhite.
[#1779](https://github.com/microsoft/PSRule/issues/1779)
- Fixed for git head in tests by @BernieWhite.
[#1801](https://github.com/microsoft/PSRule/issues/1801)
> Pre-release v3.0.0-B0198

- .github/workflows/analyze.yaml
- docs/CHANGELOG-v3.md
- pipeline.build.ps1
- schemas/PSRule-options.schema.json
- src/PSRule/Pipeline/Output/CsvOutputWriter.cs
- tests/PSRule.Tests/OutputWriterTests.cs
- tests/PSRule.Tests/PSRule.Common.Tests.ps1
- Fixes CSV output of multiple lines.
Fixes #1627 
> Fixes CSV output of multiple lines #1627

- docs/install.md
- src/PSRule.Tool/README.md
Minor CLI docs update.
Fixes #1152
> Bump tool CLI docs

- docs/concepts/security.md
- mkdocs.yml
- Added security guidance doc.
> Add security guidance

- docs/CHANGELOG-v3.md
- modules.json
Update PowerShell dependencies.
> Bump PowerShell dependencies

- docs/concepts/feature-flagging.md
- src/PSRule.Types/Emitters/IEmitterContext.cs
- src/PSRule.Types/PSRule.Types.csproj
- src/PSRule.Types/Runtime/IConfiguration.cs
- src/PSRule/Pipeline/Emitters/EmitterContext.cs
- src/PSRule/Pipeline/GetTargetPipelineBuilder.cs
- src/PSRule/Pipeline/IInvokePipelineBuilder.cs
- src/PSRule/Pipeline/InvokePipelineBuilderBase.cs
- src/PSRule/Pipeline/InvokeRulePipelineBuilder.cs
- src/PSRule/Pipeline/PipelineBuilder.cs
- src/PSRule/Pipeline/PipelineInputStream.cs
- src/PSRule/Runtime/Configuration.cs
- src/PSRule/Runtime/RunspaceScope.cs
- tests/PSRule.Tests/PipelineTests.cs
Add an `IConfiguration` interface working towards #1838.
> Add IConfiguration interface #1838

- src/PSRule.Types/Definitions/ISourceExtent.cs
- src/PSRule.Types/Definitions/InfoString.cs
- src/PSRule/Definitions/SourceExtent.cs
- src/PSRule/Pipeline/Dependencies/LockFile.cs
- src/PSRule/Runtime/RuleConditionHelper.cs
- src/PSRule/Runtime/RunspaceContext.cs
Refactoring to better handle nullable.
> Refactoring for nullable

- .devcontainer/devcontainer.json
- Updated configuration for dev containers.
> Updated Dev Container config

- src/PSRule.Benchmark/packages.lock.json
- src/PSRule.CommandLine/packages.lock.json
- src/PSRule.SDK/packages.lock.json
- src/PSRule.Tool/packages.lock.json
- src/PSRule/PSRule.csproj
- src/PSRule/Pipeline/Emitters/EmitterBuilder.cs
- src/PSRule/Pipeline/Emitters/EmitterCollection.cs
- src/PSRule/packages.lock.json
Add dependency injection for emitters.
Related to #1837
> Add DI container for emitters

- .devcontainer/devcontainer.json
- .vscode/extensions.json
- Update Dev Container configuration.
> Updates to Dev Container

- .devcontainer/container-build.ps1
- .devcontainer/devcontainer.json
- global.json
- src/PSRule.Benchmark/PSRule.Benchmark.csproj
- src/PSRule.Benchmark/packages.lock.json
- src/PSRule.CommandLine/packages.lock.json
- src/PSRule.SDK/packages.lock.json
- src/PSRule.Tool/packages.lock.json
- src/PSRule/PSRule.csproj
- src/PSRule/packages.lock.json
- tests/PSRule.Tests/InputPathBuilderTests.cs
- Added global.json for SDK versioning.
> Added global.json

- .config/dotnet-tools.json
- .devcontainer/devcontainer.json
- NuGet.config
> Updated tool configuration

- src/PSRule/Host/HostHelper.cs
- src/PSRule/Pipeline/PipelineContext.cs
> Updates for context refactoring

- src/PSRule/Definitions/IResourceDiscoveryContext.cs
- src/PSRule/Definitions/IScriptResourceDiscoveryContext.cs
- src/PSRule/Definitions/InternalResource.cs
- src/PSRule/Definitions/Resource.cs
- src/PSRule/Host/HostHelper.cs
- src/PSRule/Pipeline/IResourceCache.cs
- src/PSRule/Pipeline/PipelineWriterExtensions.cs
- src/PSRule/Pipeline/ResourceCache.cs
- src/PSRule/Pipeline/ResourceCacheBuilder.cs
- src/PSRule/Pipeline/ResourceCacheDiscoveryContext.cs
- src/PSRule/Runtime/RunspaceContext.cs
- tests/PSRule.Tests/Pipeline/ResourceCacheTests.cs
Refactor - split out context interfaces for discovery.
> Split out context interfaces for discovery

- .github/dependabot.yml
- src/PSRule.Tool/packages.lock.json
Group PowerShell dependencies.
> Group PowerShell dependencies

- .config/dotnet-tools.json
- .github/dependabot.yml
- src/PSRule.Benchmark/packages.lock.json
- src/PSRule.CommandLine/packages.lock.json
- src/PSRule.SDK/packages.lock.json
- src/PSRule.Tool/packages.lock.json
> Rollback Git Version tool

- src/PSRule.Types/Options/BaselineOption.cs
- src/PSRule.Types/Options/ExecutionOption.cs
- src/PSRule.Types/Options/IOption.cs
- src/PSRule/Configuration/BindingOption.cs
- src/PSRule/Configuration/PSRuleOption.cs
- src/PSRule/Pipeline/Emitters/EmitterCollection.cs
Additional refactoring for options interface.
> Option interface refactoring

- src/PSRule/Pipeline/IPipelineContext.cs
- src/PSRule/Pipeline/InvokePipelineBuilderBase.cs
- src/PSRule/Pipeline/OptionContextBuilder.cs
- src/PSRule/Pipeline/PipelineBuilderBase.cs
- src/PSRule/Pipeline/PipelineContext.cs
- src/PSRule/Pipeline/ResourceCache.cs
- src/PSRule/Pipeline/ResourceCacheBuilder.cs
- src/PSRule/Pipeline/RulePipeline.cs
- src/PSRule/Runtime/RunspaceContext.cs
- tests/PSRule.Tests/AssertTests.cs
- tests/PSRule.Tests/BaselineTests.cs
- tests/PSRule.Tests/FunctionBuilderTests.cs
- tests/PSRule.Tests/FunctionTests.cs
- tests/PSRule.Tests/ModuleConfigTests.cs
- tests/PSRule.Tests/OutputWriterTests.cs
- tests/PSRule.Tests/PSRuleOptionTests.cs
- tests/PSRule.Tests/PipelineTests.cs
- tests/PSRule.Tests/ResourceValidatorTests.cs
- tests/PSRule.Tests/RulesTests.cs
- tests/PSRule.Tests/SelectorTests.cs
- tests/PSRule.Tests/SuppressionFilterTests.cs
- tests/PSRule.Tests/SuppressionGroupTests.cs
- tests/PSRule.Tests/TargetNameBindingTests.cs
> Refactor context

- src/PSRule.Benchmark/packages.lock.json
- src/PSRule.CommandLine/packages.lock.json
- src/PSRule.SDK/packages.lock.json
- src/PSRule.Tool/packages.lock.json
- src/PSRule/Definitions/IResourceExtensions.cs
- src/PSRule/packages.lock.json
- tests/PSRule.Tests/AssertTests.cs
- tests/PSRule.Tests/BaseTests.cs
- tests/PSRule.Tests/BaselineTests.cs
- tests/PSRule.Tests/ConventionTests.cs
- tests/PSRule.Tests/LockFileTests.cs
- tests/PSRule.Tests/ModuleConfigTests.cs
- tests/PSRule.Tests/ObjectHelperTests.cs
- tests/PSRule.Tests/ObjectPathTests.cs
- tests/PSRule.Tests/OptionContextTests.cs
- tests/PSRule.Tests/OutputWriterTests.cs
- tests/PSRule.Tests/PSRuleOptionTests.cs
- tests/PSRule.Tests/PathExpressionTests.cs
- tests/PSRule.Tests/ResourceValidatorTests.cs
- tests/PSRule.Tests/RuleLanguageAstTests.cs
- tests/PSRule.Tests/SelectorTests.cs
- tests/PSRule.Tests/SourcePipelineBuilderTests.cs
- tests/PSRule.Tests/SuppressionGroupTests.cs
Code refactoring for improve reuse in tests.
> Test refactoring

- docs/CHANGELOG-v3.md
- mkdocs.yml
- src/PSRule/Host/HostHelper.cs
- src/PSRule/Pipeline/PipelineContext.cs
- src/PSRule/Runtime/ILanguageScope.cs
- src/PSRule/Runtime/ILanguageScopeCollection.cs
- src/PSRule/Runtime/LanguageScope.cs
- src/PSRule/Runtime/LanguageScopeSet.cs
- src/PSRule/Runtime/RunspaceContext.cs
- tests/PSRule.Tests/FunctionTests.cs
- tests/PSRule.Tests/PSRuleOptionTests.cs
- tests/PSRule.Tests/SelectorTests.cs
> Refactoring of language scopes

- src/PSRule/Pipeline/PipelineBuilderBase.cs
- src/PSRule/Pipeline/PipelineContext.cs
- src/PSRule/Runtime/ILanguageScopeSet.cs
- src/PSRule/Runtime/LanguageScopeSet.cs
- src/PSRule/Runtime/LanguageScopeSetBuilder.cs
- src/PSRule/Runtime/RunspaceContext.cs
- tests/PSRule.Tests/AssertTests.cs
- tests/PSRule.Tests/BaselineTests.cs
- tests/PSRule.Tests/ContextBaseTests.cs
- tests/PSRule.Tests/FunctionBuilderTests.cs
- tests/PSRule.Tests/FunctionTests.cs
- tests/PSRule.Tests/ModuleConfigTests.cs
- tests/PSRule.Tests/OutputWriterTests.cs
- tests/PSRule.Tests/PSRuleOptionTests.cs
- tests/PSRule.Tests/PipelineTests.cs
- tests/PSRule.Tests/ResourceValidatorTests.cs
- tests/PSRule.Tests/RulesTests.cs
- tests/PSRule.Tests/SelectorTests.cs
- tests/PSRule.Tests/SuppressionFilterTests.cs
- tests/PSRule.Tests/SuppressionGroupTests.cs
- tests/PSRule.Tests/TargetNameBindingTests.cs
Additional refactoring of language scopes.
> Refactoring of language scopes - part 2

- src/PSRule.Tool/packages.lock.json
- src/PSRule/Commands/ExportConventionCommand.cs
- src/PSRule/Commands/NewRuleDefinitionCommand.cs
- src/PSRule/Common/JsonConverters.cs
- src/PSRule/Common/YamlConverters.cs
- src/PSRule/Definitions/IResourceDiscoveryContext.cs
- src/PSRule/Definitions/ResourceBuilder.cs
- src/PSRule/Definitions/ResourceObject.cs
- src/PSRule/Definitions/SuppressionGroups/SuppressionGroupVisitor.cs
- src/PSRule/Host/HostHelper.cs
- src/PSRule/Pipeline/ResourceCacheDiscoveryContext.cs
- src/PSRule/Runtime/RunspaceContext.cs
- tests/PSRule.Tests/BaselineTests.cs
- tests/PSRule.Tests/SuppressionGroups.Rule.yaml
Refactoring for using resource discovery context.
> Context refactoring

- global.json
- schemas/PSRule-language.schema.json
Update SDK configuration and schema minor updates.
> Update SDK config

- src/PSRule.EditorServices/PSRule.EditorServices.csproj
Disable packing of editor services lib which does not need NuGet publishing.
> Update packaging for editor services

- package.json
Updating packaging options for CI pipeline.
> Update packaging for CI pipeline

- .devcontainer/container-build.ps1
- .devcontainer/devcontainer.json
> Updates to dev container configuration

- .github/workflows/docs.yaml
> Update docs workflow

- src/PSRule/Definitions/IGetLocalizedPathContext.cs
- src/PSRule/Definitions/IResourceDiscoveryContext.cs
- src/PSRule/Definitions/ResourceFilter_T.cs
- src/PSRule/Definitions/SuppressionGroups/SuppressionGroupFilter.cs
- src/PSRule/Host/HostHelper.cs
- src/PSRule/Pipeline/IResourceCache.cs
- src/PSRule/Pipeline/InvokeRulePipeline.cs
- src/PSRule/Pipeline/PipelineBuilderBase.cs
- src/PSRule/Pipeline/PipelineContext.cs
- src/PSRule/Pipeline/ResourceCache.cs
- src/PSRule/Pipeline/ResourceCacheBuilder.cs
- src/PSRule/Pipeline/ResourceCacheDiscoveryContext.cs
- src/PSRule/Pipeline/ResourceIssue.cs
- src/PSRule/Runtime/ILanguageScopeSet.cs
- src/PSRule/Runtime/IMetaResourceDiscoveryContext.cs
- src/PSRule/Runtime/RunspaceContext.cs
- tests/PSRule.Tests/ContextBaseTests.cs
- tests/PSRule.Tests/ConventionTests.cs
- tests/PSRule.Tests/FromFile.Rule.jsonc
- tests/PSRule.Tests/FromFile.Rule.yaml
- tests/PSRule.Tests/FunctionTests.cs
- tests/PSRule.Tests/OptionContextTests.cs
- tests/PSRule.Tests/OutputWriterTests.cs
- tests/PSRule.Tests/Pipeline/ResourceCacheTests.cs
- tests/PSRule.Tests/RulesTests.cs
- tests/PSRule.Tests/SuppressionFilterTests.cs
- tests/PSRule.Tests/SuppressionGroupTests.cs
Refactoring of the codebase to improve scope handling #1215
> Code refactoring

- .devcontainer/devcontainer.json
- global.json
- src/PSRule.Tool/packages.lock.json
Update the dev container configuration.
> Update Dev Container config

- docs/CHANGELOG-v3.md
What's changed since pre-release v3.0.0-B0315:
- VSCode extension set to use Microsoft verified publisher name by @BernieWhite.
[#2636](https://github.com/microsoft/PSRule/issues/2636)
- Expose format options to emitters by @BernieWhite.
[#1838](https://github.com/microsoft/PSRule/issues/1838)
- Added support for overriding options path from the default in VSCode by @BernieWhite.
[#2635](https://github.com/microsoft/PSRule/issues/2635)
- Engineering:
- Migrated VSCode extension into PSRule repository by @BernieWhite.
[#2615](https://github.com/microsoft/PSRule/issues/2615)
- VSCode extension will now sit side-by-side with the other core PSRule components.
- Bug fixes:
- Fixes path filtering of ignored files includes prefixed files by @BernieWhite. …
> Pre-release v3.0.0-B0340

- docs/updates/v3.0.md
> Add doc updates

- docs/CHANGELOG-v3.md
What's changed since pre-release v3.0.0-B0340:
- VSCode extension includes PSRule runtime by @BernieWhite.
[#1755](https://github.com/microsoft/PSRule/issues/1755)
- The PSRule runtime is bundled with the VSCode extension.
- Separate installation of the PSRule PowerShell module is no longer required.
- VSCode extension asks to automatically restore modules by @BernieWhite.
[#2642](https://github.com/microsoft/PSRule/issues/2642)
- When opening a workspace, the extension will ask to restore any modules from the lock file.
- Alternatively, running the `PSRule: Restore modules` command manually will restore modules.
> Pre-release v3.0.0-B0342

- docs/concepts/PSRule/en-US/about_PSRule_Options.md
- docs/hooks/old_hooks.py
- mkdocs.yml
- package.json
- requirements-docs.txt
- src/PSRule.CommandLine/Commands/ModuleCommand.cs
- src/PSRule.EditorServices/ClientBuilder.cs
- src/vscode-ps-rule/README.md
- src/vscode-ps-rule/commands/initLock.ts
- src/vscode-ps-rule/extension.ts
Add command to initialize lock file from VSCode command palette.
> Add VSCode init locks command

- docs/scenarios/containers/container-execution.md
- src/bootstrap/README.md
- src/bootstrap/bootstrap.ps1
Add initial bootstrap script for CI.
> Add initial bootstrap script

- src/PSRule/Definitions/Conventions/BaseConvention.cs
- src/PSRule/Definitions/Conventions/ConventionComparer.cs
- src/PSRule/Definitions/Conventions/ScriptBlockConvention.cs
- src/PSRule/Definitions/IConventionV1.cs
- src/PSRule/Host/HostHelper.cs
- src/PSRule/Pipeline/OptionContext.cs
- src/PSRule/Pipeline/PipelineContext.cs
- src/PSRule/Pipeline/RulePipeline.cs
- src/PSRule/Runtime/LocalizedData.cs
- src/PSRule/Runtime/PSRule.cs
- src/PSRule/Runtime/RunspaceContext.cs
- src/PSRule/Runtime/RunspaceScope.cs
- tests/PSRule.Tests/BaselineTests.cs
- tests/PSRule.Tests/FromFileConventions.Rule.ps1
- tests/PSRule.Tests/FunctionBuilderTests.cs
- tests/PSRule.Tests/FunctionTests.cs
- tests/PSRule.Tests/PSRuleOptionTests.cs
- tests/PSRule.Tests/RulesTests.cs
- tests/PSRule.Tests/SelectorTests.cs
- tests/PSRule.Tests/SuppressionFilterTests.cs
- tests/PSRule.Tests/SuppressionGroupTests.cs
Code refactoring for conventions.
> Refactoring conventions

- .github/ISSUE_TEMPLATE/sample_proposal.yaml
- docs/CHANGELOG-v3.md
- samples/README.md
- samples/azure/README.md
- Added samples path working towards #2614
> Add sample path #2614

- docs/CHANGELOG-v3.md
- src/PSRule.Types/Data/SemanticVersion.cs
- tests/PSRule.Types.Tests/Data/SemanticVersionTests.cs
- Fixed string formatting of semantic version and constraints.
Fixes #1828 
> Fixed string formatting of semantic version and constraints #1828

- docs/CHANGELOG-v3.md
- src/PSRule/Definitions/Expressions/ExpressionContext.cs
- src/PSRule/Definitions/IDetailedRuleResultV2.cs
- src/PSRule/Definitions/IResultDetail.cs
- src/PSRule/Definitions/IResultReason.cs
- src/PSRule/Definitions/ResultDetail.cs
- src/PSRule/Definitions/ResultReason.cs
- src/PSRule/Rules/RuleRecord.cs
- src/PSRule/Runtime/AssertResult.cs
- src/PSRule/Runtime/RuleConditionHelper.cs
- tests/PSRule.Tests/AssertTests.cs
- tests/PSRule.Tests/BaseTests.cs
- tests/PSRule.Tests/Expressions/ExpressionContextTests.cs
- tests/PSRule.Tests/Runtime/AssertResultTests.cs
- Fixed duplicate reasons are reported for the same rule.
Fixes #2553
> Fixed duplicate reasons are reported for the same rule #2553

- docs/concepts/baselines.md
- docs/concepts/grouping-rules.md
- docs/concepts/lockfile.md
- docs/setup/index.md
- mkdocs.yml
> Update to docs

- docs/concepts/lockfile.md
- docs/updates/v3.0.md
- mkdocs.yml
Add updates to v3 release docs.
Working towards #2521
> Add format updates

- docs/CHANGELOG-v3.md
- docs/commands/PSRule/en-US/Assert-PSRule.md
- docs/concepts/cli/run.md
- docs/creating-your-pipeline.md
- docs/updates/v3.0.md
- mkdocs.yml
Fixes to documentation.
Fixes #2749
> Documentation fixes

- docs/changelog.md
- docs/concepts/formats.md
- src/PSRule.Types/Environment.cs
- src/PSRule.Types/Runtime/ILogger.cs
- src/PSRule.Types/Runtime/IRuntimeFactory.cs
- src/PSRule.Types/Runtime/IRuntimeFactoryContext.cs
- src/PSRule.Types/Runtime/RuntimeFactoryAttribute.cs
- src/PSRule/Emitters/EmitterBuilder.cs
- src/PSRule/Pipeline/Formatters/AssertFormatterBase.cs
- src/PSRule/Pipeline/Output/JobSummaryWriter.cs
- src/PSRule/Pipeline/Output/SarifBuilder.cs
- src/PSRule/Pipeline/PipelineBuilderBase.cs
- src/PSRule/Pipeline/Source.cs
- src/PSRule/Pipeline/SourcePipelineBuilder.cs
- src/PSRule/Resources/PSRuleResources.Designer.cs
- src/PSRule/Resources/PSRuleResources.resx
- src/PSRule/Runtime/LanguageScope.cs
- src/PSRule/Runtime/LanguageScopeSetBuilder.cs
- src/PSRule/Runtime/RuntimeFactoryBuilder.cs
- src/PSRule/Runtime/RuntimeFactoryContainer.cs
- src/PSRule/Runtime/RuntimeFactoryContext.cs
- tests/PSRule.Tests/BaselineTests.cs
- tests/PSRule.Tests/Emitters/EmitterBuilderTests.cs
- tests/PSRule.Tests/OptionContextTests.cs
- tests/PSRule.Tests/Runtime/BadRuntimeFactory.cs
- tests/PSRule.Tests/Runtime/RuntimeFactoryBuilderTests.cs
- tests/PSRule.Tests/Runtime/SimpleRuntimeFactory.cs
- tests/PSRule.Tests/TestObject.cs
- Fixed custom emitter loaded too late.
Fixes #2775
> Fixes custom emitter loaded to late #2775

- .github/workflows/build.yaml
- .github/workflows/dependencies.yaml
- .github/workflows/docs.yaml
- .github/workflows/first-interaction.yaml
- .github/workflows/stale.yaml
Update GitHub action workflows to use commit pinned dependencies.
> Pin actions to commit

- .github/dependabot.yml
- .github/workflows/build.yaml
- docs/scenarios/containers/dockerfile
- tests/PSRule.Tests/Dockerfile
Add additional pins for dependencies.
> Additional dependency pins for CI

- src/PSRule.CommandLine/ClientContext.cs
- src/PSRule/Common/ExternalToolHelper.cs
- src/PSRule/Common/GitHelper.cs
- src/PSRule/Configuration/BaselineOption.cs
- src/PSRule/Configuration/OutputOption.cs
- src/PSRule/Configuration/PSRuleOption.cs
- src/PSRule/PSRule.csproj
- src/PSRule/Pipeline/ExportBaselinePipelineBuilder.cs
- src/PSRule/Pipeline/GetBaselinePipelineBuilder.cs
- src/PSRule/Pipeline/GetRuleHelpPipeline.cs
- src/PSRule/Pipeline/GetRuleHelpPipelineBuilder.cs
- src/PSRule/Pipeline/GetRulePipelineBuilder.cs
- src/PSRule/Pipeline/GetTargetPipelineBuilder.cs
- src/PSRule/Pipeline/HelpWriter.cs
- src/PSRule/Pipeline/IPipelineBuilder.cs
- src/PSRule/Pipeline/InputPathBuilder.cs
- src/PSRule/Pipeline/InvokePipelineBuilderBase.cs
- src/PSRule/Pipeline/PathBuilder.cs
- src/PSRule/Pipeline/PathFilterBuilder.cs
- src/PSRule/Pipeline/PipelineBuilderBase.cs
- src/PSRule/Pipeline/PipelineContext.cs
- src/PSRule/Pipeline/Runs/IRun.cs
- src/PSRule/Pipeline/Runs/Run.cs
- src/PSRule/Pipeline/SourceScope.cs
General refactoring of pipeline code.
> Refactoring pipelines part 1

- docs/changelog.md
- src/PSRule/Definitions/Expressions/Functions.cs
- src/PSRule/Definitions/ResultReason.cs
- src/PSRule/Pipeline/Output/JobSummaryWriter.cs
- src/PSRule/Pipeline/Output/SarifBuilder.cs
- src/PSRule/Pipeline/Output/SarifOutputWriter.cs
- src/PSRule/Pipeline/PathBuilder.cs
- src/PSRule/Pipeline/TargetObject.cs
- src/PSRule/Runtime/IOperand.cs
- src/PSRule/Runtime/Operand.cs
- tests/PSRule.Tests/Pipeline/Output/SarifOutputWriterTests.cs
Fixes empty SARIF run metadata.
Fixes #2901
> Fixed empty SARIF run metadata #2901

- src/PSRule.Types/Data/ITargetObject.cs
- src/PSRule.Types/Data/ITargetObjectProperty.cs
- src/PSRule/Commands/AssertExistsCommand.cs
- src/PSRule/Commands/AssertMatchCommand.cs
- src/PSRule/Commands/AssertTypeOfCommand.cs
- src/PSRule/Commands/AssertWithinCommand.cs
- src/PSRule/Commands/RuleKeyword.cs
- src/PSRule/Common/PSObjectExtensions.cs
- src/PSRule/Pipeline/PipelineContext.cs
- src/PSRule/Pipeline/PipelineInputStream.cs
- src/PSRule/Pipeline/PipelineReciever.cs
- src/PSRule/Pipeline/TargetObject.cs
- src/PSRule/Pipeline/TargetObjectChild.cs
- src/PSRule/Rules/RuleRecord.cs
- src/PSRule/Runtime/DynamicPropertyBinder.cs
- src/PSRule/Runtime/ObjectHelper.cs
- src/PSRule/Runtime/ObjectPath/PathExpressionBuilder.cs
- src/PSRule/Runtime/PSRule.cs
- tests/PSRule.Tests/Binding/TargetBinderTests.cs
- tests/PSRule.Tests/Definitions/Selectors/SelectorVisitorTests.cs
- tests/PSRule.Tests/InputFormatDeserializerTests.cs
- tests/PSRule.Tests/ObjectExtensions.cs
- tests/PSRule.Tests/ObjectPathTests.cs
- tests/PSRule.Tests/YamlRulesTests.cs
Refactoring of pipelines and target object usage.
> Refactor pipelines part 4

- src/PSRule.Types/Data/ITargetObjectProperty.cs
- src/PSRule/Definitions/Expressions/LanguageExpressionBuilder.cs
- src/PSRule/Host/HostHelper.cs
- src/PSRule/Rules/SuppressionFilter.cs
- src/PSRule/Runtime/Operand.cs
Refactoring to improve code maintainability.
> Code refactor

- src/PSRule/Commands/AssertWithinCommand.cs
- src/PSRule/Common/GitHelper.cs
- src/PSRule/Definitions/Baselines/BaselineSpec.cs
- src/PSRule/Definitions/Rules/RuleV1Spec.cs
- src/PSRule/Rules/Rule.cs
- src/PSRule/Runtime/Assert.cs
- src/PSRule/Runtime/NameToken.cs
- src/PSRule/Runtime/ScopedItem.cs
Minor refactoring to fix linting issues.
> Fix linting issues

- .github/workflows/copilot-setup-steps.yml
- src/PSRule.MSBuild/Generators/EngineVersionGenerator.cs
- tests/PSRule.Tests/Pipeline/InputPathBuilderTests.cs
Add build to make it easier for copilot to build the project.
> Add copilot build

- .devcontainer/devcontainer.json
- dotnet-install.sh
Updates to dev container config.
> Updated devcontainer config

- src/PSRule/Common/RunspaceContextDiagnosticExtensions.cs
- src/PSRule/Definitions/DependencyGraphBuilder.cs
- src/PSRule/Host/HostHelper.cs
- src/PSRule/Pipeline/InvokeRulePipeline.cs
- src/PSRule/Pipeline/ResourceIssueType.cs
- src/PSRule/Pipeline/Runs/IRunBuilderContext.cs
- src/PSRule/Pipeline/Runs/RunCollectionBuilder.cs
- src/PSRule/Runtime/LegacyRunspaceContext.cs
> Refactoring runs
