CHANGELOG.md
docs/commands/PSRule/en-US/Get-PSRule.md
docs/commands/PSRule/en-US/Invoke-PSRule.md
src/PSRule/Host/HostHelper.cs
src/PSRule/Rules/RuleResult.cs
src/PSRule/Rules/TagSet.cs
tests/PSRule/FromFile.Rule.ps1
tests/PSRule/PSRule.Common.Tests.ps1

- Added rule tags to results to enable grouping and sorting #14
- Added support to check for rule tag existence. Use `*` for tag value on `-Tag` parameter with `Invoke-PSRule` and `Get-PSRule`
Fixes #14

Add tag mapping and tag existance filter

---

.github/ISSUE_TEMPLATE/bug_report.md
CHANGELOG.md
src/PSRule/Pipeline/InvokeRulePipeline.cs
tests/PSRule/FromFile.Rule.ps1
tests/PSRule/PSRule.Common.Tests.ps1

- Fix outcome filtering of summary results [#33](https://github.com/BernieWhite/PSRule/issues/33)
Fixes #33

Fix Invoke-PSRule summary ignores outcome filter #33

---

.github/ISSUE_TEMPLATE/bug_report.md
CHANGELOG.md
PSRule.build.ps1
src/PSRule/Commands/RuleKeyword.cs
src/PSRule/Pipeline/InvokeRulePipeline.cs
src/PSRule/Pipeline/PipelineContext.cs
tests/PSRule/FromFile.Rule.ps1
tests/PSRule/PSRule.Common.Tests.ps1
tests/PSRule/PSRule.Hint.Tests.ps1
tests/PSRule/PSRule.Match.Tests.ps1
tests/PSRule/PSRule.TypeOf.Tests.ps1
tests/PSRule/PSRule.Within.Tests.ps1

- Fix target object counter in verbose logging #35
- Fix hashtable keys should be handled as fields #36
- Improved unit test cases
- Updated GitHub issue report template
Fixes #35 
Fixes #36

Fix issue verbose logging and handling of hashtable keys #35 #36

---

CHANGELOG.md
src/PSRule/PSRule.psm1
tests/PSRule.Tests/PSRule.Common.Tests.ps1

- Fix Get-PSRule generates exception when no .rule.ps1 scripts exist in path #53
- Fix LocalizedData.PathNotFound warning when no .rule.ps1 scripts exist in path #54
Fixes #53 
Fixes #54

Fix source file path handling #53 #54

---

CHANGELOG.md
docs/keywords/PSRule/en-US/about_PSRule_Keywords.md
src/PSRule/Commands/AssertExistsCommand.cs
src/PSRule/Commands/AssertMatchCommand.cs
src/PSRule/Commands/AssertTypeOfCommand.cs
src/PSRule/Commands/AssertWithinCommand.cs
src/PSRule/PSRule.psm1
tests/PSRule.Tests/FromFile.Rule.ps1

- Added support for pipelining with `Exists`, `Within`, `Match` and `TypeOf` keywords #90
Fixes #90 

Add support for keyword pipelining #90

---

CHANGELOG.md
src/PSRule/Common/YamlConverters.cs
tests/PSRule.Tests/ObjectFromFile.yaml

- Fix empty YAML object causes format deserialize to fail #92
Fixes #92 

Fix empty YAML object causes format deserialize to fail #92

---

.vscode/settings.json
CHANGELOG.md
README.md
docs/concepts/PSRule/en-US/about_PSRule_Options.md
schemas/PSRule-options-0.4.0.schema.json
src/PSRule/Configuration/InputOption.cs
src/PSRule/Configuration/LoggingOption.cs
src/PSRule/Configuration/OutcomeLogStream.cs
src/PSRule/Configuration/PSRuleOption.cs
src/PSRule/Pipeline/InvokeRulePipeline.cs
src/PSRule/Pipeline/InvokeRulePipelineBuilder.cs
src/PSRule/Pipeline/PipelineContext.cs
src/PSRule/Resources/PSRuleResources.Designer.cs
src/PSRule/Resources/PSRuleResources.resx
tests/PSRule.Tests/PSRule.Common.Tests.ps1
tests/PSRule.Tests/PSRule.Tests.yml

- Added support for logging pass or fail outcomes to a data stream such as Error, Warning or Information #97
Fixes #97 

Add outcome logging to PowerShell streams #97

---

CHANGELOG.md
src/PSRule/Commands/SetPSRuleHintCommand.cs
src/PSRule/Pipeline/PipelineContext.cs
src/PSRule/Resources/PSRuleResources.Designer.cs
src/PSRule/Resources/PSRuleResources.resx
tests/PSRule.Tests/FromFile.Rule.ps1
tests/PSRule.Tests/PSRule.Hint.Tests.ps1

- Deprecated usage of the `-TargetName` parameter on the `Hint` keyword has been removed #81

Removed deprecated Hint -TargetName parameter #81

---

CHANGELOG.md
README.md
docs/commands/PSRule/en-US/Get-PSRule.md
docs/commands/PSRule/en-US/Invoke-PSRule.md
docs/commands/PSRule/en-US/New-PSRuleOption.md
docs/commands/PSRule/en-US/PSRule.md
docs/commands/PSRule/en-US/Set-PSRuleOption.md
docs/commands/PSRule/en-US/Test-PSRuleTarget.md
docs/concepts/PSRule/en-US/about_PSRule_Options.md
src/PSRule/Configuration/BindingOption.cs
src/PSRule/Configuration/PSRuleOption.cs
src/PSRule/PSRule.psd1
src/PSRule/PSRule.psm1
src/PSRule/Resources/PSRuleResources.Designer.cs
src/PSRule/Resources/PSRuleResources.resx
src/PSRule/en-AU/PSRule.Resources.psd1
src/PSRule/en-US/PSRule.Resources.psd1
tests/PSRule.Tests/PSRule.Options.Tests.ps1
tests/PSRule.Tests/PSRule.Tests4.yml

- Added `Set-PSRuleOption` cmdlet to configure YAML options file. #135
- Added parameters to New-PSRuleOption to configure common options. #134
Fixes #135 
Fixes #134 

Add and update cmdlets to set options from parameters #135 #134

---

CHANGELOG.md
src/PSRule/Host/HostHelper.cs
src/PSRule/PSRule.psd1
src/PSRule/PSRule.psm1
tests/PSRule.Tests/PSRule.Common.Tests.ps1
tests/PSRule.Tests/PSRule.PSGallery.Tests.ps1

- Fix discovery of rules within paths that contain spaces fails. #168
- Fix exporting of `Recommend` keyword and `Hint` alias. #171
Fixes #168 
Fixes #171 

Fix for path space and exporting of recommend keyword #168 #171

---

CHANGELOG.md
docs/keywords/PSRule/en-US/about_PSRule_Keywords.md
src/PSRule/Commands/InvokeRuleBlockCommand.cs
src/PSRule/Host/HostHelper.cs
src/PSRule/Pipeline/PipelineContext.cs
src/PSRule/Resources/PSRuleResources.Designer.cs
src/PSRule/Resources/PSRuleResources.resx
src/PSRule/Rules/RuleConditionResult.cs
tests/PSRule.Tests/FromFileWithError.Rule.ps1
tests/PSRule.Tests/PSRule.Common.Tests.ps1

- Fix handling of non-boolean results in rules. Rule is failed with more specific error message. #187
Fixes #187 

Fix handling of non-boolean results in rules #187

---

CHANGELOG.md
src/PSRule/Commands/NewRuleDefinitionCommand.cs
src/PSRule/Commands/RuleLanguageAst.cs
src/PSRule/Host/DependencyGraphBuilder.cs
src/PSRule/PSRule.psm1
src/PSRule/Resources/PSRuleResources.Designer.cs
src/PSRule/Resources/PSRuleResources.resx
tests/PSRule.Tests/FromFileNested.Rule.ps1
tests/PSRule.Tests/FromFileWithError.Rule.ps1
tests/PSRule.Tests/PSRule.Common.Tests.ps1

- Fix circular rule dependency issue. #190
- Fix error message when attempting to use the rule keyword in a rule definition. #189
Fixes #190 
Fixes #189 

Fix circular dependencies and rule nesting error handling #190 #189

---

.vscode/settings.json
CHANGELOG.md
README.md
docs/features.md
docs/scenarios/install-instructions.md
src/PSRule/Commands/NewRuleDefinitionCommand.cs
src/PSRule/Pipeline/InvokeResult.cs
src/PSRule/Pipeline/NUnit3Serializer.cs
src/PSRule/Pipeline/PipelineContext.cs
src/PSRule/Rules/RuleRecord.cs
tests/PSRule.Tests/FromFile.Rule.ps1
tests/PSRule.Tests/FromFileInvalid.Rule.ps1
tests/PSRule.Tests/FromFileWithError.Rule.ps1
tests/PSRule.Tests/PSRule.Common.Tests.ps1

- Fix rule `DependsOn` parameter allows null. #191
- **Breaking change**: Rule time is recorded in milliseconds instead of seconds. #192
Fixes #191 
Fixes #192 

Fix rule DependsOn parameter allows null and change rule timing to milliseconds #191 #192

---

docs/keywords/PSRule/en-US/about_PSRule_Keywords.md

- Fix documentation error, `TypeOf -TypeName` is case sensitive. #201
Fixes #201

TypeOf TypeName parameter is case sensitive #201

---

.azure-pipelines/azure-pipelines.yaml

- Fix marking GitHub releases as pre-release in CI pipeline.

Fix marking GitHub releases as pre-release

---

CHANGELOG.md
docs/keywords/PSRule/en-US/about_PSRule_Keywords.md
src/PSRule/Commands/AssertMatchCommand.cs
src/PSRule/Commands/AssertWithinCommand.cs
src/PSRule/PSRule.psm1
tests/PSRule.Tests/FromFile.Rule.ps1
tests/PSRule.Tests/PSRule.Match.Tests.ps1
tests/PSRule.Tests/PSRule.Within.Tests.ps1

- Add `-Not` switch to `Within` and `Match` keywords to allow negative comparison. #208
#208 

Add -Not to Within and Match keywords #208

---

CHANGELOG.md
src/PSRule/Pipeline/PipelineHookActions.cs
tests/PSRule.Tests/PSRule.Common.Tests.ps1
tests/PSRule.Tests/PSRule.TypeOf.Tests.ps1

- Fix TargetName binding when TargetName or Name property is null. #202
Fixes #202 

Fix TargetName binding of null #202

---

CHANGELOG.md
README.md
docs/concepts/PSRule/en-US/about_PSRule_Variables.md
src/PSRule/Commands/NewRuleDefinitionCommand.cs
src/PSRule/Host/Host.cs
src/PSRule/Host/HostHelper.cs
src/PSRule/Pipeline/PipelineContext.cs
src/PSRule/Rules/RuleBlock.cs
src/PSRule/Runtime/Assert.cs
src/PSRule/Runtime/LocalizedData.cs
tests/PSRule.Tests/FromFile.Rule.ps1
tests/PSRule.Tests/PSRule.Variables.Tests.ps1
tests/PSRule.Tests/en-ZZ/PSRule-rules.psd1

- Add culture support for PowerShell informational messages. #158
- A new `$LocalizedData` variable can be used within rule definitions.
Fixes #158 

Add culture support for rule informational messages #158

---

CHANGELOG.md
docs/commands/PSRule/en-US/Get-PSRule.md
docs/commands/PSRule/en-US/Invoke-PSRule.md
docs/commands/PSRule/en-US/Test-PSRuleTarget.md
docs/concepts/PSRule/en-US/about_PSRule_Options.md
src/PSRule/Configuration/OutputFormat.cs
src/PSRule/PSRule.Format.ps1xml
src/PSRule/PSRule.psm1
src/PSRule/Resources/ViewStrings.Designer.cs
src/PSRule/Resources/ViewStrings.resx
src/PSRule/Rules/TagSet.cs
tests/PSRule.Tests/PSRule.Common.Tests.ps1

- Improve discovery of rule tags. #209
- Add wide format `-OutputFormat Wide` to `Get-PSRule` to allow output of rule tags. 
- **Breaking change**: Change rule filtering by tag to be case-insensitive. #204
- Previously tag value was case-sensitive, however this is confusing since PowerShell is case-insensitive by default.
Fixes #209 
Fixes #204 

Improve handling of rule tags and filtering #209 #204

---

CHANGELOG.md
src/PSRule/Commands/AssertWithinCommand.cs
tests/PSRule.Tests/FromFile.Rule.ps1
tests/PSRule.Tests/PSRule.Within.Tests.ps1

- Fix comparison of non-string types with `Within`. #226
Fixes #226 

Fix Within comparison of non-string types #226

---

CHANGELOG.md
src/PSRule/Configuration/PSRuleOption.cs
src/PSRule/PSRule.Format.ps1xml
src/PSRule/Resources/PSRuleResources.Designer.cs
src/PSRule/Resources/PSRuleResources.resx
src/PSRule/Resources/ViewStrings.Designer.cs
src/PSRule/Resources/ViewStrings.resx
tests/PSRule.Tests/PSRule.Options.Tests.ps1

- Fix YAML options file discovery issue in dotted directory. #232
- PSRule options are now displayed as YAML instead of complex object. #233 
Fixes #232 
Fixes #233 

Fix YAML options discovery and display #232 #233

---

CHANGELOG.md
docs/keywords/PSRule/en-US/about_PSRule_Keywords.md

- Added per object reason for failing rules. #200
- The keywords `Exists`, `Match`, `Within` and `TypeOf` automatically add a reason when they fail.
- Added `-Reason` parameter to `Exists`, `Match`, `Within` and `TypeOf` keywords to allow a custom reason to be set.
- Added `Reason` keyword to add to reason for custom logic.
- Added wide output display for `Invoke-PSRule` which include the reason why rule failed.
- To use wide output use the `-OutputFormat Wide` parameter.
- Renamed `-Message` parameter to `-Text` on the `Recommend` keyword.
- The `-Message` is an alias of `-Text` and will be deprecated in the future.

Pre-release v0.8.0-B190716

---

CHANGELOG.md
README.md
docs/concepts/PSRule/en-US/about_PSRule_Assert.md
docs/concepts/PSRule/en-US/about_PSRule_Variables.md
pipeline.build.ps1
src/PSRule/Common/PSObjectExtensions.cs
src/PSRule/Common/StringExtensions.cs
src/PSRule/PSRule.csproj
src/PSRule/Pipeline/PipelineContext.cs
src/PSRule/Pipeline/PowerShellPipelineStream.cs
src/PSRule/Resources/PSRuleResources.Designer.cs
src/PSRule/Resources/PSRuleResources.resx
src/PSRule/Resources/ReasonStrings.Designer.cs
src/PSRule/Resources/ReasonStrings.resx
src/PSRule/Rules/RuleConditionResult.cs
src/PSRule/Runtime/Assert.cs
src/PSRule/Runtime/AssertResult.cs
tests/PSRule.Tests/FromFile.Json.schema.json
tests/PSRule.Tests/FromFile.Rule.ps1
tests/PSRule.Tests/FromFileAssert.Rule.ps1
tests/PSRule.Tests/PSRule.Assert.Tests.ps1
tests/PSRule.Tests/PSRule.Variables.Tests.ps1

- Fix inconsistent handling of `$PWD`. #249
- Added assertion helper `$Assert` for extensibility. #250
- Add built-in assertions for `HasField`, `HasFieldValue` and `NullOrEmpty`.
- Add JSON schema assertion method `JsonSchema`. #42
Fixes #249 
Fixes #250 
Fixes #42 

Add assertion helper and fix $PWD #249 #250 #42

---

CHANGELOG.md

- Fix inconsistent handling of `$PWD`. #249
- Add detection for improper keyword use. #203
- Automatically load rule modules. #218
- Added assertion helper `$Assert` for extensibility. #250
- Add built-in assertions for `HasField`, `HasFieldValue` and `NullOrEmpty`.
- Add JSON schema assertion method `JsonSchema`. #42
- **Breaking change**: Use rule references consistent with cmdlet fully qualified syntax. #217
- Previously rule names only had to be unique within a single file, now rule names have to be unique within the current execution path or within a module.
- Previously the `filename.rule.ps1/RuleName` was supported to reference rules across files. Because rule names must be unique this syntax is no longer required or supported.
- You can reference a rule from a loaded module by …

Pre-release v0.8.0-B190742

---

CHANGELOG.md
src/PSRule/PSRule.psm1
tests/PSRule.Tests/PSRule.Common.Tests.ps1

- Fix module reloading with different versions. #254
- Fix not finding rules in current path by default. #256
Fixes #254 
Fixes #256 

Fix module reloading and finding rules #254 #256

---

CHANGELOG.md
docs/concepts/PSRule/en-US/about_PSRule_Assert.md
docs/concepts/PSRule/en-US/about_PSRule_Variables.md
src/PSRule/PSRule.psd1
src/PSRule/PSRule.psm1

- Fix export of assertion helper variable `$Assert`. #262
Fixes #262 

Fix export of $Assert variable #262

---

CHANGELOG.md
src/PSRule/Commands/NewRuleDefinitionCommand.cs
src/PSRule/PSRule.Format.ps1xml
src/PSRule/Resources/DocumentStrings.Designer.cs
src/PSRule/Resources/DocumentStrings.resx
src/PSRule/Rules/RuleHelpInfo.cs
tests/PSRule.Tests/PSRule.Common.Tests.ps1
tests/PSRule.Tests/TestModule/en-AU/M1.Rule1.md
tests/PSRule.Tests/TestModule/en-US/M1.Rule1.md
tests/PSRule.Tests/en-ZZ/FromFile1.md

- Added rule info display name. #276
- Fix ModuleName not displayed in Get-PSRuleHelp list. #275
Fixes #276 
Fixes #275 

Added rule info display name #276 #275

---

CHANGELOG.md

- Added support for a wildcard match using the `Within` keyword. #272
- Added rule info display name. #276
- Fix ModuleName not displayed in Get-PSRuleHelp list. #275

Pre-release v0.9.0-B190819

---

CHANGELOG.md
src/PSRule/PSRule.psm1

- Fix export of `Like` parameter for `Within` keyword. #279
Fixes #279 

Fix export of Like parameter for Within #279

---

CHANGELOG.md

- Added support for matching an array of tag values. #282
- Updated `Get-PSRuleHelp` to include help within the current path by default. #197
- Fix can not serialize nested System.IO.DirectoryInfo property. #281
- Fix export of `Like` parameter for `Within` keyword. #279
- **Breaking change**: Added named baselines. This changes how baselines work. #274]
- Previously, baselines were specified as workspace options.
- Now, baselines are a separate resource that can be individually used. Additionally:
- Baselines can be packaged within module.
- Modules can specify a default baseline in module manifest.
- Target binding options (`Binding`) are now part of baselines.
- The previous `baseline` options property has been renamed to `rule`.
- The previous `configuration` property is now a top …

Pre-release v0.9.0-B190905

---

CHANGELOG.md
README.md
docs/concepts/PSRule/en-US/about_PSRule_Assert.md
src/PSRule/Runtime/Assert.cs
tests/PSRule.Tests/FromFileAssert.Rule.ps1
tests/PSRule.Tests/PSRule.Assert.Tests.ps1

- Added assertion helper for checking field default value. #289
Fixes #289 

Add assertion for default value #289

---

CHANGELOG.md
docs/commands/PSRule/en-US/Get-PSRule.md
src/PSRule/Common/DictionaryExtensions.cs
src/PSRule/Configuration/OutputOption.cs
src/PSRule/Host/DependencyGraph.cs
src/PSRule/Host/DependencyGraphBuilder.cs
src/PSRule/Host/HostHelper.cs
src/PSRule/PSRule.psm1
src/PSRule/Parser/MarkdownReader.cs
src/PSRule/Parser/MarkdownToken.cs
src/PSRule/Parser/MarkdownTokenExtensions.cs
src/PSRule/Parser/RuleLexer.cs
src/PSRule/Parser/TokenStream.cs
src/PSRule/Pipeline/CsvOutputWriter.cs
src/PSRule/Pipeline/GetRulePipeline.cs
src/PSRule/Pipeline/InvokeRulePipeline.cs
src/PSRule/Pipeline/NUnit3OutputWriter.cs
src/PSRule/Pipeline/PipelineBuilder.cs
src/PSRule/Pipeline/PipelineWriter.cs
src/PSRule/Pipeline/RulePipeline.cs
src/PSRule/Rules/Rule.cs
src/PSRule/Rules/RuleBlock.cs
tests/PSRule.Tests/PSRule.Common.Tests.ps1

- Added dependency `DependsOn` information to results from `Get-PSRule`. #210
- To include dependencies that would normally be filtered out use `-IncludeDependencies`.
Fixes #210 

Expose DependsOn from Get-PSRule #210

---

.vscode/settings.json
CHANGELOG.md
docs/commands/PSRule/en-US/Assert-PSRule.md
docs/commands/PSRule/en-US/Invoke-PSRule.md
docs/commands/PSRule/en-US/Test-PSRuleTarget.md
docs/concepts/PSRule/en-US/about_PSRule_Options.md
src/PSRule/Common/PSObjectExtensions.cs
src/PSRule/Configuration/InputFormat.cs
src/PSRule/PSRule.psm1
src/PSRule/Parser/MarkdownConvert.cs
src/PSRule/Parser/MarkdownReader.cs
src/PSRule/Pipeline/InvokeRulePipeline.cs
src/PSRule/Pipeline/PipelineReciever.cs
src/PSRule/Rules/ResourceRef.cs
tests/PSRule.Tests/ObjectFromFile.md
tests/PSRule.Tests/PSRule.Common.Tests.ps1

- Added input format for reading markdown front matter. #301
- Markdown front matter is deserialized and evaluated as an object.
- Added source note properties to input objects read from disk with `-InputPath`. #302
Fixes #301 
Fixes #302 

Add markdown format and source info #301 #302

---

CHANGELOG.md
docs/keywords/PSRule/en-US/about_PSRule_Keywords.md
src/PSRule/Host/Host.cs
src/PSRule/PSRule.psd1
src/PSRule/PSRule.psm1
tests/PSRule.Tests/FromFile.Rule.ps1
tests/PSRule.Tests/PSRule.PSGallery.Tests.ps1
tests/PSRule.Tests/PSRule.Recommend.Tests.ps1

- **Breaking change**: Removed previously deprecated alias `Hint` for `Recommend`. #165
- Use the `Recommend` keyword instead.
Fixes #165 

Remove Hint alias for Recommend #165

---

CHANGELOG.md

- Added dependency `DependsOn` information to results from `Get-PSRule`. #210
- To include dependencies that would normally be filtered out use `-IncludeDependencies`.
- Added input format for reading markdown front matter. #301
- Markdown front matter is deserialized and evaluated as an object.
- Added source note properties to input objects read from disk with `-InputPath`. #302
- **Breaking change**: Removed previously deprecated alias `Hint` for `Recommend`. #165
- Use the `Recommend` keyword instead.

Pre-release v0.10.0-B1910036

---

CHANGELOG.md

- Fixed missing `Markdown` input format in options schema. #315
- Added `-TargetType` parameter to filter input objects by target type. #176
- This parameter applies to `Invoke-PSRule`, `Assert-PSRule` and `Test-PSRuleTarget`.
- **Breaking change**: Unprocessed object results are not returned from `Test-PSRuleTarget` by default. #318
- Previously unprocessed objects returned `$True`, now unprocessed objects return no result.
- Use `-Outcome All` to return `$True` for unprocessed objects the same as <= v0.10.0.

Pre-release v0.11.0-B1910014

---

CHANGELOG.md
src/PSRule/Common/PSObjectExtensions.cs

- Fixed null reference exception when bound property is null. #323
Fixes #323 

Fixed null reference on bound property #323

---

CHANGELOG.md
docs/keywords/PSRule/en-US/about_PSRule_Keywords.md
src/PSRule.Benchmark/PSRule.Benchmark.csproj
src/PSRule/Commands/AssertExistsCommand.cs
src/PSRule/Resources/ReasonStrings.Designer.cs
src/PSRule/Resources/ReasonStrings.resx
tests/PSRule.Tests/FromFile.Rule.ps1
tests/PSRule.Tests/PSRule.Exists.Tests.ps1
tests/PSRule.Tests/PSRule.Tests.csproj

- Added `-All` option to `Exists` keyword. #331 
Fixes #331 

Added -All option to Exists keyword #331

---

CHANGELOG.md

- Fixed TargetType fall back to type name. #339
- Added custom field binding. #321
- Added new option `Binding.Field` available in baselines to configure binding.
- Added parameter alias `-f` for `-InputPath`. #340
- `-f` was added to `Invoke-PSRule`, `Assert-PSRule` and `Test-PSRuleTarget` cmdlets.
- **Important change**: Added `$PSRule` generic context variable. #341
- Deprecated `TargetName`, `TargetType` and `TargetObject` properties on `$Rule`.
- Use `TargetName`, `TargetType` and `TargetObject` on `$PSRule` instead.
- Properties `TargetName`, `TargetType` and `TargetObject` on `$Rule` will be removed in the future.
- Going forward `$Rule` will only contain properties that relate to the current rule context.

Pre-release v0.12.0-B1912002

---

CHANGELOG.md
docs/commands/PSRule/en-US/Get-PSRule.md
docs/concepts/PSRule/en-US/about_PSRule_Options.md
schemas/PSRule-language.schema.json
schemas/PSRule-options.schema.json
src/PSRule/Configuration/BaselineOption.cs
src/PSRule/PSRule.psm1
src/PSRule/Pipeline/GetRulePipeline.cs
src/PSRule/Rules/RuleFilter.cs
src/PSRule/Rules/TagSet.cs
tests/PSRule.Tests/Baseline.Rule.yaml
tests/PSRule.Tests/FromFileBaseline.Rule.ps1
tests/PSRule.Tests/PSRule.Baseline.Tests.ps1
tests/PSRule.Tests/PSRule.Options.Tests.ps1
tests/PSRule.Tests/RuleFilterTests.cs

- Fixed multiple value tag filtering. #346
- Added filtering for rules against a baseline with `Get-PSRule`. #345
Fixes #346 
Fixes #345 

Fixed multiple value tag filtering #346 #345

---

CHANGELOG.md

- Fixed multiple value tag filtering. #346
- Added filtering for rules against a baseline with `Get-PSRule`. #345

Pre-release v0.12.0-B1912007

---

CHANGELOG.md
README.md
docs/concepts/PSRule/en-US/about_PSRule_Assert.md
src/PSRule/Resources/PSRuleResources.Designer.cs
src/PSRule/Resources/PSRuleResources.resx
src/PSRule/Resources/ReasonStrings.Designer.cs
src/PSRule/Resources/ReasonStrings.resx
src/PSRule/Runtime/Assert.cs
src/PSRule/Runtime/AssertResult.cs
src/PSRule/Runtime/SemanticVersion.cs
tests/PSRule.Tests/AssertTests.cs
tests/PSRule.Tests/FromFileAssert.Rule.ps1
tests/PSRule.Tests/PSRule.Assert.Tests.ps1
tests/PSRule.Tests/SemanticVersionTests.cs

- Added semantic version assertion helper `Version`. #344
- Added string affix assertion helpers. #353
- Added methods `StartsWith`, `EndsWith` and `Contains`. See `about_PSRule_Assert` for usage details.
- Added `WithReason` to append/ replace reasons from assertion result. #354
Fixes #344 
Fixes #353 
Fixes #354 

Added semver assertion helper #344 #353 #354

---

CHANGELOG.md

- Added semantic version assertion helper `Version`. #344
- Added string affix assertion helpers. #353
- Added methods `StartsWith`, `EndsWith` and `Contains`. See `about_PSRule_Assert` for usage details.
- Added `WithReason` to append/ replace reasons from assertion result. #354

Pre-release v0.13.0-B1912005

---

tests/PSRule.Tests/PSRule.PSGallery.Tests.ps1

- PSScriptAnalyzer tests intermittently fail based on an exception occurring between PSScriptAnalyzer and PowerShell. These tests will be disabled until the upstream issue can be resolved. #229

Disable flaky PSScriptAnalyzer tests #299

---

CHANGELOG.md
docs/commands/PSRule/en-US/Assert-PSRule.md
docs/commands/PSRule/en-US/Invoke-PSRule.md
docs/commands/PSRule/en-US/New-PSRuleOption.md
docs/commands/PSRule/en-US/Set-PSRuleOption.md
docs/commands/PSRule/en-US/Test-PSRuleTarget.md
docs/concepts/PSRule/en-US/about_PSRule_Options.md
schemas/PSRule-options.schema.json
src/PSRule/Common/PSObjectExtensions.cs
src/PSRule/Configuration/InputFormat.cs
src/PSRule/PSRule.psm1
src/PSRule/Pipeline/InvokeRulePipeline.cs
src/PSRule/Pipeline/PipelineHookActions.cs
src/PSRule/Pipeline/PipelineReciever.cs
src/PSRule/Runtime/ObjectHelper.cs
tests/PSRule.Tests/InputFormatDeserializerTests.cs
tests/PSRule.Tests/ObjectFromFile.psd1
tests/PSRule.Tests/PSRule.Common.Tests.ps1
tests/PSRule.Tests/PSRule.Tests.csproj

- Added input format for reading PowerShell data `.psd1` files. #368 
- `PowerShellData` has been added to `Input.Format`.
- See `about_PSRule_Options` for details.
Fixes #368 

Added input format for PowerShell data files #368

---

CHANGELOG.md

- Added input format for reading PowerShell data `.psd1` files. #368
- `PowerShellData` has been added to `Input.Format`.
- See `about_PSRule_Options` for details.
- Added numeric comparison assertion helpers. #374
- Added methods `Greater`, `GreaterOrEqual`, `Less` and `LessOrEqual`.
- See `about_PSRule_Assert` for usage details.

Pre-release v0.13.0-B1912043

---

CHANGELOG.md
docs/commands/PSRule/en-US/Get-PSRuleHelp.md
docs/concepts/PSRule/en-US/about_PSRule_Docs.md
docs/scenarios/rule-docs/en-US/metadata.Name.md
docs/scenarios/rule-docs/rule-docs.md
src/PSRule.Benchmark/Benchmark.Rule.ps1
src/PSRule.Benchmark/PSRule.cs
src/PSRule.Benchmark/en-ZZ/BenchmarkHelp.md
src/PSRule/Commands/NewRuleDefinitionCommand.cs
src/PSRule/PSRule.Format.ps1xml
src/PSRule/PSRule.psm1
src/PSRule/Parser/MarkdownReader.cs
src/PSRule/Parser/RuleLexer.cs
src/PSRule/Pipeline/GetRuleHelpPipeline.cs
src/PSRule/Resources/DocumentStrings.Designer.cs
src/PSRule/Resources/DocumentStrings.resx
src/PSRule/Rules/RuleHelpInfo.cs
tests/PSRule.Tests/RuleDocumentTests.cs

- Added rule documentation links and notes to help. #382
- Added `-Full` switch to `Get-PSRuleHelp` to display links and notes sections.
Fixes #382 

Added links and notes to help #382

---

CHANGELOG.md
docs/commands/PSRule/en-US/Assert-PSRule.md
docs/commands/PSRule/en-US/Get-PSRule.md
docs/commands/PSRule/en-US/Get-PSRuleBaseline.md
docs/commands/PSRule/en-US/Get-PSRuleHelp.md
docs/commands/PSRule/en-US/Invoke-PSRule.md
docs/commands/PSRule/en-US/Test-PSRuleTarget.md
src/PSRule/PSRule.psm1

- Added aliases for `-OutputFormat` (`-o`) and `-Module` (`-m`) parameters. #384
Fixes #384 

Added aliases for OutputFormat and Module #384

---

CHANGELOG.md
docs/concepts/PSRule/en-US/about_PSRule_Assert.md
src/PSRule/Commands/AssertAllOfCommand.cs
src/PSRule/Commands/AssertAnyOfCommand.cs
src/PSRule/Commands/InvokeRuleBlockCommand.cs
src/PSRule/Host/HostHelper.cs
src/PSRule/Rules/RuleBlock.cs
src/PSRule/Runtime/Assert.cs
src/PSRule/Runtime/RuleConditionResult.cs
tests/PSRule.Tests/AssertTests.cs
tests/PSRule.Tests/FromFileAssert.Rule.ps1
tests/PSRule.Tests/PSRule.Assert.Tests.ps1

- Improved numeric comparison assertion helpers to support strings. #387
- Methods `Greater`, `GreaterOrEqual`, `Less` and `LessOrEqual` now also check string length.
- Added support for assertion methods to be used within script pre-conditions. #386
Fixes #386 
Fixes #387 

Added assert in pre-conditions #386 #387

---

CHANGELOG.md

- Fixed JSON de-serialization fails with single object. #379
- Fixed stack overflow when parsing malformed JSON. #380
- Added rule documentation links and notes to help. #382
- Added `-Full` switch to `Get-PSRuleHelp` to display links and notes sections.
- Added aliases for `-OutputFormat` (`-o`) and `-Module` (`-m`) parameters. #384
- Improved numeric comparison assertion helpers to support strings. #387
- Methods `Greater`, `GreaterOrEqual`, `Less` and `LessOrEqual` now also check string length.
- Added support for assertion methods to be used within script pre-conditions. #386

Pre-release v0.13.0-B2001013

---

CHANGELOG.md
README.md
docs/concepts/PSRule/en-US/about_PSRule_Assert.md
docs/concepts/PSRule/en-US/about_PSRule_Variables.md
docs/features.md
src/PSRule/Host/Host.cs
src/PSRule/Pipeline/PipelineContext.cs
src/PSRule/Resources/ReasonStrings.Designer.cs
src/PSRule/Resources/ReasonStrings.resx
src/PSRule/Runtime/Assert.cs
src/PSRule/Runtime/LocalizedData.cs
src/PSRule/Runtime/PSRule.cs
tests/PSRule.Tests/AssertTests.cs
tests/PSRule.Tests/FromFile.Rule.ps1
tests/PSRule.Tests/FromFileAssert.Rule.ps1
tests/PSRule.Tests/PSRule.Assert.Tests.ps1

- Added assertion method `HasJsonSchema` to check if a JSON schema is referenced. #398
- See `about_PSRule_Assert` for usage details.
- Added file content helper for reading objects from files. #399
- The method `GetContent` of `$PSRule` can be used to read files as objects.
- See `about_PSRule_Variables` for usage details.
Fixes #398 
Fixes #399 

Added HasJsonSchema method #398 #399

---

CHANGELOG.md

- Added support for qualified target names. #395
- Added options `Binding.UseQualifiedName` and `Binding.NameSeparator`.
- See `about_PSRule_Options` for details.
- Added assertion method `HasJsonSchema` to check if a JSON schema is referenced. #398
- See `about_PSRule_Assert` for usage details.
- Added file content helper for reading objects from files. #399
- The method `GetContent` of `$PSRule` can be used to read files as objects.
- See `about_PSRule_Variables` for usage details.

Pre-release v0.14.0-B2001020

---

CHANGELOG.md

- Fixed wide formatting of rules with `Get-PSRule`. #407
- Fixed TargetName hash serialization for base types. #406
- Fixed output not generated with Assert-PSRule and Stop. #405
- Fixed NUnit results incorrectly reporting that the test had not executed. #403
- Improved NUnit results to include a failure message based on reported reasons. #404
- Improved reporting on runtime errors in rule blocks. #239

Pre-release v0.14.0-B2002003

---

CHANGELOG.md
src/PSRule/Pipeline/AssertPipeline.cs
tests/PSRule.Tests/FromFile.Rule.ps1
tests/PSRule.Tests/PSRule.Common.Tests.ps1

- Fix output of warning with `Assert-PSRule`. #417
Fixes #417 

Fix output of warning with Assert-PSRule #417

---

CHANGELOG.md

- Fixed output of warning with `Assert-PSRule`. #417
- Fixed NUnit report to include a failure element when reason is not specified. #420
- Added recommendation to failure message of NUnit results. #421

Pre-release v0.15.0-B2002012

---

CHANGELOG.md
docs/commands/PSRule/en-US/Assert-PSRule.md
src/PSRule/PSRule.psm1
src/PSRule/Pipeline/AssertPipeline.cs
src/PSRule/Pipeline/HostContext.cs
src/PSRule/Pipeline/InvokeRulePipeline.cs
src/PSRule/Pipeline/Output/CsvOutputWriter.cs
src/PSRule/Pipeline/Output/FileOutputWriter.cs
src/PSRule/Pipeline/Output/NUnit3OutputWriter.cs
src/PSRule/Pipeline/Output/PSPipelineWriter.cs
src/PSRule/Pipeline/PipelineBuilder.cs
src/PSRule/Pipeline/PipelineLogger.cs
src/PSRule/Pipeline/TestPipeline.cs
src/PSRule/Rules/RuleSource.cs
tests/PSRule.Tests/PSRule.Common.Tests.ps1

- Added `-ResultVariable` to store results from Assert-PSRule into a variable. #412
Fixes #412 

Add -ResultVariable to Assert-PSRule #412

---

CHANGELOG.md
src/PSRule/Runtime/SemanticVersion.cs
tests/PSRule.Tests/PSRule.Tests.csproj
tests/PSRule.Tests/SemanticVersionTests.cs

- Fixed handling of `v` in field value with `$Assert.Version`. #429
Fixes #429 

Fixed handling of v in version field value #429

---

CHANGELOG.md
src/PSRule/Pipeline/AssertPipeline.cs
src/PSRule/Pipeline/Output/PSPipelineWriter.cs
src/PSRule/Pipeline/PipelineBuilder.cs
src/PSRule/Pipeline/PipelineWriter.cs
tests/PSRule.Tests/PSRule.Common.Tests.ps1

- Fixed handling of warning action preference with `Assert-PSRule`. #428
Fixes #428 

Fixed handling of warning in Assert-PSRule #428

---

CHANGELOG.md

- Fixed handling of `v` in field value with `$Assert.Version`. #429
- Fixed handling of warning action preference with `Assert-PSRule`. #428

Pre-release v0.15.0-B2002031

---

.azure-pipelines/azure-pipelines.yaml
.azure-pipelines/jobs/test.yaml
.azure-pipelines/jobs/testContainer.yaml

- Azure Pipelines is not using PS 7.0 as default. Update CI process to check PS 6.2.4.
- Fix CI issue with YamlDotNet being used between PSRule and PlatyPS.

Update CI pipeline for PS 7.0 as default

---

CHANGELOG.md
docs/concepts/PSRule/en-US/about_PSRule_Assert.md
src/PSRule/Runtime/Assert.cs
src/PSRule/Runtime/NameToken.cs
src/PSRule/Runtime/ObjectHelper.cs
tests/PSRule.Tests/AssertTests.cs
tests/PSRule.Tests/FromFileAssert.Rule.ps1
tests/PSRule.Tests/ObjectHelperTests.cs
tests/PSRule.Tests/PSRule.Assert.Tests.ps1

- Improved handling of fields to allow the input object to be referenced with `.`. #437
Fixes #437 

Support input of self reference #437

---

CHANGELOG.md
docs/concepts/PSRule/en-US/about_PSRule_Assert.md
src/PSRule/Runtime/Assert.cs
src/PSRule/Runtime/AssertResult.cs
tests/PSRule.Tests/AssertTests.cs
tests/PSRule.Tests/FromFile.Rule.ps1
tests/PSRule.Tests/PSRule.Assert.Tests.ps1

- Fixed numeric comparison assertion with non-int types. #436
Fixes #436 

Fixed numeric comparison with non-int #436

---

CHANGELOG.md
src/PSRule/Pipeline/AssertPipeline.cs
src/PSRule/Resources/FormatterStrings.Designer.cs
src/PSRule/Resources/FormatterStrings.resx

- Improved `Assert-PSRule` output formatting.
- Added recommendation and reasons for `Client` and `Plain` styles. #456
Fixes #456 

Add PS 7.0 style for client and plain styles #456

---

CHANGELOG.md
pipeline.build.ps1
src/PSRule/Pipeline/AssertPipeline.cs

- Improved `Assert-PSRule` output formatting. #472
- Added recommendation and reasons for `AzurePipelines` and `GitHubActions` styles.
- Summary line is has been updated to include synopsis instead of reasons.
Fixes #472 

Improved Assert-PSRule output formatting #472

---

pipeline.build.ps1

- Set Pester version to v4.10.1 as v5 introduces breaking changes.

Fix Pester version to v4.10.1

---

CHANGELOG.md
docs/concepts/PSRule/en-US/about_PSRule_Options.md
src/PSRule/Pipeline/InvokeRulePipeline.cs
src/PSRule/Pipeline/Output/CsvOutputWriter.cs
tests/PSRule.Tests/PSRule.Common.Tests.ps1

- Bug fixes:
- Fixed `Csv` output format with summary for `Invoke-PSRule`. #486
Fixes #486 

Fixed Csv output format with summary #486

---

CHANGELOG.md
src/PSRule/Runtime/ObjectHelper.cs
tests/PSRule.Tests/ObjectHelperTests.cs

- Fixed unable to read properties for .NET `DynamicObject`. #491
Fixes #491 

Fixed unable to read properties DynamicObject #491

---

CHANGELOG.md
src/PSRule/Runtime/Assert.cs
tests/PSRule.Tests/PSRule.Assert.Tests.ps1

- Fixed actual value in reason for numeric comparison assertion method. #505
Fixes #505 

Fixed actual value in for numeric assertion #505

---

CHANGELOG.md
src/PSRule/Runtime/Assert.cs
tests/PSRule.Tests/FromFileAssert.Rule.ps1
tests/PSRule.Tests/PSRule.Assert.Tests.ps1

- Fixed `Assert.In` unable to compare PSObject wrapped array items. #512
Fixes #512 

Fixed Assert.In compare of array items #512

---

CHANGELOG.md

- Bug fixes:
- Fixed `Assert.In` unable to compare PSObject wrapped array items. #512

Pre-release v0.19.0-B2007030

---

CHANGELOG.md
docs/concepts/PSRule/en-US/about_PSRule_Baseline.md
schemas/PSRule-language.schema.json
src/PSRule/Common/DictionaryExtensions.cs
src/PSRule/Definitions/Baseline.cs
src/PSRule/Definitions/ISpec.cs
src/PSRule/Definitions/ModuleConfig.cs
src/PSRule/Definitions/SpecFactory.cs
src/PSRule/Pipeline/OptionContext.cs
src/PSRule/Pipeline/PipelineBuilder.cs
src/PSRule/Pipeline/PipelineContext.cs
src/PSRule/Pipeline/PipelineWriter.cs
src/PSRule/Pipeline/RunspaceContext.cs
src/PSRule/Resources/PSRuleResources.Designer.cs
src/PSRule/Resources/PSRuleResources.resx
tests/PSRule.Tests/Baseline.Rule.yaml
tests/PSRule.Tests/BaselineTests.cs
tests/PSRule.Tests/PSRule.Baseline.Tests.ps1

- Baselines can now be flagged as obsolete. #499
- Set the `metadata.annotations.obsolete` property to `true` to flag a baseline as obsolete.
- When an obsolete baseline is used, a warning will be generated.
Fixes #499 

Warn when an obsolete baseline is used #499

---

CHANGELOG.md

What's changed since pre-release v0.20.0-B2008002:
- Baselines can now be flagged as obsolete. #499
- Set the `metadata.annotations.obsolete` property to `true` to flag a baseline as obsolete.
- When an obsolete baseline is used, a warning will be generated.
- Engineering:
- Bump YamlDotNet dependency to v8.1.2. #439

Pre-release v0.20.0-B2008010

---

CHANGELOG.md
src/PSRule/Commands/NewRuleDefinitionCommand.cs
src/PSRule/Parser/MarkdownReader.cs
tests/PSRule.Tests/PSRule.Common.Tests.ps1

- Fixed out of bounds exception when empty markdown documentation is used. #516
Fixes #516 

Fixed empty markdown out of bounds #516

---

.ps-rule/OpenSource.Rule.ps1
CHANGELOG.md
README.md
docs/concepts/PSRule/en-US/about_PSRule_Assert.md
src/PSRule/Resources/ReasonStrings.Designer.cs
src/PSRule/Resources/ReasonStrings.resx
src/PSRule/Runtime/Assert.cs
tests/PSRule.Tests/AssertTests.cs
tests/PSRule.Tests/FromFileAssert.Rule.ps1
tests/PSRule.Tests/PSRule.Assert.Tests.ps1

- Added file assertion helpers `FileHeader`, and `FilePath`. #534
- `FileHeader` checks for a comment header in the file.
- `FilePath` checks that a file path, optionally with suffixes exist.
Fixes #534 

Added file assertion helpers #534

---

CHANGELOG.md
README.md
docs/concepts/PSRule/en-US/about_PSRule_Variables.md
docs/scenarios/fruit/isFruit.Rule.ps1
docs/scenarios/index.md
src/PSRule/Pipeline/RunspaceContext.cs
src/PSRule/Resources/PSRuleResources.Designer.cs
src/PSRule/Resources/PSRuleResources.resx
src/PSRule/Runtime/Rule.cs
tests/PSRule.Tests/FromFile.Rule.ps1
tests/PSRule.Tests/FromFileBaseline.Rule.ps1
tests/PSRule.Tests/TestModule4/rules/Module4.Rule.ps1

- Warn when deprecated `$Rule` properties are used. #536
Fixes #536 

Warn on deprecated $Rule properties #536

---

CHANGELOG.md
docs/concepts/PSRule/en-US/about_PSRule_Options.md
src/PSRule/Common/GitHelper.cs

- Fixed lines breaks in `RepositoryInfo` target name with git ref. #538
Fixes #538 

Fixed git ref line break #538

---

CHANGELOG.md
src/PSRule/Data/InputFileInfo.cs
src/PSRule/Data/RepositoryInfo.cs
src/PSRule/Rules/Rule.cs

- Added automatic binding for Rule object. #542
- Bug fixes:
- Fixed `InputFileInfo` `Type` property causes downstream binding issues. #541
Fixes #541 
Fixes #542 

Fix automatic binding properties #541 #542

---

CHANGELOG.md
src/PSRule/Pipeline/PipelineWriter.cs
src/PSRule/Pipeline/PipelineWriterExtensions.cs
src/PSRule/Pipeline/RunspaceContext.cs
src/PSRule/Resources/PSRuleResources.Designer.cs
src/PSRule/Resources/PSRuleResources.resx

- Fixed excessive obsolete property warnings. #545
Fixes #545 

Fixed excessive obsolete property warnings #545

---

CHANGELOG.md
README.md
docs/concepts/PSRule/en-US/about_PSRule_Options.md
schemas/PSRule-options.schema.json
src/PSRule/Configuration/OutputFormat.cs
src/PSRule/Configuration/OutputOption.cs
src/PSRule/Configuration/PSRuleOption.cs
src/PSRule/PSRule.psm1
src/PSRule/Pipeline/AssertPipeline.cs
src/PSRule/Pipeline/InvokeRulePipeline.cs
src/PSRule/Pipeline/Output/MarkdownOutputWriter.cs
src/PSRule/Pipeline/Output/PSPipelineWriter.cs
src/PSRule/Pipeline/PipelineBuilder.cs
src/PSRule/Pipeline/PipelineWriter.cs
src/PSRule/Pipeline/TestPipeline.cs
src/PSRule/Resources/ReportStrings.Designer.cs
src/PSRule/Resources/ReportStrings.resx
tests/PSRule.Tests/PSRule.Options.Tests.ps1
tests/PSRule.Tests/PSRule.Tests.yml

- Added support for formatting results as markdown. #474
- Use `-OutputFormat Markdown` or configure `Output.Format` to output markdown.
- To format as either detail or summary, use the `-As` parameter or configure `Output.As`.
- Added outcome `Output.Outcome` as a configurable option. #552
Fixes #474 
Fixes #552 

Added markdown output format #474 #552

---

CHANGELOG.md
README.md
docs/concepts/PSRule/en-US/about_PSRule_Assert.md
src/PSRule/Resources/ReasonStrings.Designer.cs
src/PSRule/Resources/ReasonStrings.resx
src/PSRule/Runtime/Assert.cs
tests/PSRule.Tests/AssertTests.cs
tests/PSRule.Tests/FromFileAssert.Rule.ps1
tests/PSRule.Tests/PSRule.Assert.Tests.ps1

- Added character case assertion helpers `IsLower`, and `IsUpper`. [#555](https://github.com/microsoft/PSRule/issues/555)
- `IsLower` checks that all letters in a field value are lowercase.
- `IsUpper` checks that all letters in a field value are uppercase.
Fixes #555 

Added character case assertion helpers #555

---

CHANGELOG.md
src/PSRule/Common/StringBuilderExtensions.cs
src/PSRule/Parser/MarkdownConvert.cs
src/PSRule/Parser/MarkdownLexer.cs
src/PSRule/Parser/MarkdownReader.cs
src/PSRule/Parser/MarkdownStream.cs
src/PSRule/Parser/RuleLexer.cs
src/PSRule/Pipeline/Output/MarkdownOutputWriter.cs
src/PSRule/Pipeline/Output/NUnit3OutputWriter.cs
src/PSRule/Pipeline/PipelineWriter.cs
src/PSRule/Runtime/RuleConditionResult.cs
tests/PSRule.Tests/FromFile.Rule.ps1
tests/PSRule.Tests/PSRule.Common.Tests.ps1

- Fixed NUnit report reasons should be escaped in markdown. #471
Fixed #471 

Fixed NUnit report reasons escaping markdown #471

---

CHANGELOG.md

What's changed since pre-release v0.21.0-B2009016:
- Added help links and default snippets to schemas. #561
- Engineering:
- Bump Manatee.Json from 13.0.2 to 13.0.3. #563
- Bug fixes:
- Fixed reporting of error when rule error is handled. #564
- Fixed first exception stops other rules from being processed. #566

Pre-release v0.21.0-B2010003

---

CHANGELOG.md
docs/concepts/PSRule/en-US/about_PSRule_Options.md
src/PSRule/Common/JsonConverters.cs
src/PSRule/Pipeline/PipelineReciever.cs
tests/PSRule.Tests/ObjectFromFileSingle.jsonc
tests/PSRule.Tests/PSRule.Common.Tests.ps1

- Input format detection now includes `.jsonc` and `.markdown` file extensions. #575

Add jsonc and markdown extensions #575

---

CHANGELOG.md
docs/concepts/PSRule/en-US/about_PSRule_Assert.md
src/PSRule/Runtime/Assert.cs
tests/PSRule.Tests/FromFileAssert.Rule.ps1
tests/PSRule.Tests/PSRule.Assert.Tests.ps1

- Added `HasFields` assertion helper to check all fields exist. #578
- Updated `HasField` to check if any of the specified fields exist. #578
- Bug fixes:
- Fixed handling for null or empty arrays with `StartsWith`, `Contains`, `EndsWith`, `In`, and `NotIn`. #579
Fixes #578 
Fixes #579 

Update assertion helpers #578 #589

---

CHANGELOG.md
src/PSRule/Pipeline/AssertPipeline.cs
src/PSRule/Pipeline/PipelineBuilder.cs
src/PSRule/Pipeline/SourcePipeline.cs
src/PSRule/Resources/FormatterStrings.Designer.cs
src/PSRule/Resources/FormatterStrings.resx

- Added rule help link in failed `Assert-PSRule` output. #595

Added help links to assert output #595

---

CHANGELOG.md
docs/concepts/PSRule/en-US/about_PSRule_Variables.md
src/PSRule/Runtime/Rule.cs

- **Breaking change**: Removed deprecated `$Rule` properties. #495
Fixes #495 

Removed deprecated $Rule properties #495

---

CHANGELOG.md

What's changed since v0.22.0:
- Added rule help link in failed `Assert-PSRule` output. #595
- Engineering:
- **Breaking change**: Removed deprecated `$Rule` properties. #495
- Bump Manatee.Json from 13.0.3 to 13.0.4. #591

Pre-release v1.0.0-B2011028

---

CHANGELOG.md
docs/CHANGELOG-v0.md
docs/CHANGELOG-v1.md
docs/upgrade-notes.md

What's changed since v0.22.0:
- Added rule help link in failed `Assert-PSRule` output. #595
- Engineering:
- **Breaking change**: Removed deprecated `$Rule` properties. #495
- Bump Manatee.Json from 13.0.3 to 13.0.4. #591
What's changed since pre-release v1.0.0-B2011028:
- No additional changes.

Release v1.0.0

---

docs/CHANGELOG-v1.md
docs/concepts/PSRule/en-US/about_PSRule_Variables.md
src/PSRule/Data/InputFileInfo.cs
src/PSRule/Parser/MarkdownReader.cs
src/PSRule/Parser/MarkdownStream.cs
src/PSRule/Parser/RuleLexer.cs
src/PSRule/Parser/RuleModels.cs
src/PSRule/Parser/TokenStream.cs
src/PSRule/Rules/RuleRecord.cs
src/PSRule/Runtime/PSRule.cs
tests/PSRule.Tests/RuleDocument.md
tests/PSRule.Tests/RuleDocumentTests.cs

- Bug fixes:
- Fixed `GetContent` processing of `InputFileInfo`. #625
- Fixed null reference of rule reason with wide output. #626
- Fixed markdown help handling of include code blocks with `[`. #627
- Fixed markdown help inclusion of fenced code blocks in notes and description. #628
Fixes #625 
Fixes #626
Fixes #627 
Fixes #628 

Fixed GetContent and markdown help #625 #626 #627 #628

---

docs/CHANGELOG-v1.md
src/PSRule/Runtime/Assert.cs
tests/PSRule.Tests/PSRule.Assert.Tests.ps1

- Fixed reason reported fields for `HasField` and `HasFields` assertion helpers. #632
Fixes #632 

Fixed reason for HasField and HasFields #632

---

docs/CHANGELOG-v1.md
src/PSRule/Host/DependencyGraph.cs
src/PSRule/Rules/RuleBlock.cs
tests/PSRule.Tests/FromFileDependency.Rule.ps1
tests/PSRule.Tests/PSRule.Common.Tests.ps1

- Fixed dependent rule execution is skipped for consequent input objects. #657
Fixes #657 

Fixed dependent rule execution is skipped for consequent input object #657

---

docs/CHANGELOG-v1.md
docs/concepts/PSRule/en-US/about_PSRule_Variables.md
src/PSRule/Common/PSObjectExtensions.cs
src/PSRule/Pipeline/AssertPipeline.cs
src/PSRule/Pipeline/InvokeRulePipeline.cs
src/PSRule/Pipeline/PipelineBuilder.cs
src/PSRule/Pipeline/PipelineContext.cs
src/PSRule/Pipeline/PipelineReader.cs
src/PSRule/Pipeline/PipelineReciever.cs
src/PSRule/Runtime/PSRule.cs
src/PSRule/Runtime/PSRuleMemberInfo.cs
tests/PSRule.Tests/AssertTests.cs
tests/PSRule.Tests/BaselineTests.cs
tests/PSRule.Tests/ConfigTests.cs
tests/PSRule.Tests/FromFileConventions.Rule.ps1
tests/PSRule.Tests/PSRule.Conventions.Tests.ps1
tests/PSRule.Tests/PipelineTests.cs
tests/PSRule.Tests/TargetNameBindingTests.cs

- Added support for object expansion with conventions. #661
- Use the `$PSRule.Import` method to import child source objects into the pipeline.
Fixes #661 

Added support for object expansion with conventions #661

---

docs/CHANGELOG-v1.md

What's changed since pre-release v1.2.0-B2103016:
- Added support for object expansion with conventions. #661
- Use the `$PSRule.Import` method to import child source objects into the pipeline.

Pre-release v1.2.0-B2103023

---

docs/CHANGELOG-v1.md
docs/commands/PSRule/en-US/Assert-PSRule.md
docs/commands/PSRule/en-US/Invoke-PSRule.md
docs/commands/PSRule/en-US/Test-PSRuleTarget.md
docs/concepts/PSRule/en-US/about_PSRule_Assert.md
docs/concepts/PSRule/en-US/about_PSRule_Options.md
src/PSRule/Data/InputFileInfo.cs
src/PSRule/Runtime/Assert.cs
tests/PSRule.Tests/AssertTests.cs
tests/PSRule.Tests/Dockerfile
tests/PSRule.Tests/FromFile.Rule.ps1
tests/PSRule.Tests/PSRule.Common.Tests.ps1
tests/PSRule.Tests/PSRule.Tests.csproj

- Added support for detecting files headers from additional file extensions. #664
- Added `.bicep`, `.csx`, `.jsx`, `.groovy`, `.java`, `.json`, `.jsonc`,
`.scala`, `.rb`, `.bat`, `.cmd`.
- Added support for `Jenkinsfile` and `Dockerfile` without an extension.
- Added support for automatic type binding with files that do not have a file extension. #665
Fixes #664 
Fixes #665 

Improved file support #664 #665

---

README.md
docs/CHANGELOG-v1.md
docs/commands/PSRule/en-US/Assert-PSRule.md
docs/commands/PSRule/en-US/Invoke-PSRule.md
docs/commands/PSRule/en-US/New-PSRuleOption.md
docs/commands/PSRule/en-US/Set-PSRuleOption.md
docs/commands/PSRule/en-US/Test-PSRuleTarget.md
docs/concepts/PSRule/en-US/about_PSRule_Baseline.md
docs/concepts/PSRule/en-US/about_PSRule_Options.md
schemas/PSRule-language.schema.json
schemas/PSRule-options.schema.json
src/PSRule.Benchmark/PSRule.cs
src/PSRule/Configuration/BaselineOption.cs
src/PSRule/Configuration/BindingOption.cs
src/PSRule/Configuration/PipelineHook.cs
src/PSRule/PSRule.psm1
src/PSRule/Pipeline/OptionContext.cs
src/PSRule/Pipeline/PipelineBuilder.cs
src/PSRule/Pipeline/PipelineHookActions.cs
src/PSRule/Pipeline/TargetBinder.cs
tests/PSRule.Tests/InputFormatDeserializerTests.cs
tests/PSRule.Tests/PSRule.Options.Tests.ps1
tests/PSRule.Tests/PSRule.Tests.yml
tests/PSRule.Tests/TargetNameBindingTests.cs

- Added support for preferring automatic binding over custom binding configurations. #670
- Updates and fixes to documentation.

Added support to prefer target info #670

---

docs/CHANGELOG-v1.md

What's changed since v1.1.0:
- Added support for extensibility with conventions. #650
- Conventions provide an extensibility point within PSRule to execute actions within the pipeline.
- A convention can expose `Begin`, `Process`, and `End` blocks.
- In additional to within rules `$PSRule.Data` can be accessed from `Begin` and `Process` blocks.
- Added support for object expansion with conventions. #661
- Use the `$PSRule.Import` method to import child source objects into the pipeline.
- Added support for complex pre-conditions with selectors. #649
- Added support for preferring automatic binding over custom binding configurations. #670
- Added the `Binding.PreferTargetInfo` option to prefer target info specified by the object.
- Added strong …

Release v1.2.0

---

docs/CHANGELOG-v1.md

What's changed since v1.2.0:
- Added file path assertion helpers. #679
- Added `WithinPath` to check the file path field is within a specified path.
- Added `NotWithinPath` to check the file path field is not within a specified path
- See [about_PSRule_Assert] for details.
- Added DateTime type assertion helper. #680
- Added `IsDateTime` to check of object field is `[DateTime]`.
- See [about_PSRule_Assert] for details.
- Improved numeric comparison assertion helpers to compare `[DateTime]` fields. #685
- `Less`, `LessOrEqual`, `Greater`, and `GreaterOrEqual` compare the number of days from the current time.
- See [about_PSRule_Assert] for details.

Pre-release v1.3.0-B2104021

---

docs/CHANGELOG-v1.md
src/PSRule/Runtime/ObjectHelper.cs
tests/PSRule.Tests/ObjectHelperTests.cs

- Improved handling of field names for objects implementing `IList`, `IEnumerable`, and index properties. #693
Fixes #693

Improved handling of field names #693

---

docs/CHANGELOG-v1.md

What's changed since pre-release v1.3.0-B2104021:
- Improved handling of field names for objects implementing `IList`, `IEnumerable`, and index properties. #693
- Engineering:
- Bump YamlDotNet from 8.1.2 to 11.1.1. #690

Pre-release v1.3.0-B2104030

---

.vscode/tasks.json
README.md
docs/CHANGELOG-v1.md
docs/commands/PSRule/en-US/New-PSRuleOption.md
docs/commands/PSRule/en-US/Set-PSRuleOption.md
docs/concepts/PSRule/en-US/about_PSRule_Options.md
schemas/PSRule-options.schema.json
src/PSRule/Configuration/InputOption.cs
src/PSRule/PSRule.psm1
src/PSRule/Pipeline/GetTargetPipeline.cs
src/PSRule/Pipeline/InvokeRulePipeline.cs
src/PSRule/Pipeline/PathFilter.cs
tests/PSRule.Tests/PSRule.Common.Tests.ps1
tests/PSRule.Tests/PSRule.Options.Tests.ps1
tests/PSRule.Tests/PSRule.Tests.yml

- Exclude `.git` sub-directory by default for recursive scans. #697
Fixes #697 

Exclude .git sub-directory by default #697

---

docs/CHANGELOG-v1.md

What's changed since v1.2.0:
- Options can be configured with environment variables. #691
- Exclude `.git` sub-directory by default for recursive scans. #697
- Added `Input.IgnoreGitPath` option to configure inclusion of `.git` path.
- Added file path assertion helpers. #679
- Added `WithinPath` to check the file path field is within a specified path.
- Added `NotWithinPath` to check the file path field is not within a specified path
- Added DateTime type assertion helper. #680
- Added `IsDateTime` to check of object field is `[DateTime]`.
- Improved numeric comparison assertion helpers to compare `[DateTime]` fields. #685
- `Less`, `LessOrEqual`, `Greater`, and `GreaterOrEqual` compare the number of days from the current time.
- Improved …

Release v1.3.0

---

README.md
docs/CHANGELOG-v1.md
docs/concepts/PSRule/en-US/about_PSRule_Options.md
schemas/PSRule-options.schema.json
src/PSRule/Configuration/BannerFormat.cs
src/PSRule/Configuration/OutputOption.cs
src/PSRule/PSRule.psm1
src/PSRule/Pipeline/AssertPipeline.cs
src/PSRule/Pipeline/PipelineBuilder.cs
tests/PSRule.Tests/PSRule.Options.Tests.ps1
tests/PSRule.Tests/PSRule.Tests.yml
tests/PSRule.Tests/PSRule.Tests2.yml

- PSRule banner can be configured in output when using `Assert-PSRule`. #708
Fixes #708 

PSRule banner can be configured in output #708

---

README.md
docs/CHANGELOG-v1.md
docs/concepts/PSRule/en-US/about_PSRule_Assert.md
docs/concepts/PSRule/en-US/about_PSRule_Options.md
src/PSRule/Common/YamlConverters.cs
src/PSRule/Runtime/SemanticVersion.cs
tests/PSRule.Tests/SemanticVersionTests.cs

- Constraints support using a `@prerelease` or `@pre` to include prerelease versions. #717
Fixes #717 

Add pre-release constraint flag #717

---

docs/CHANGELOG-v1.md
src/PSRule/Commands/InvokeConventionCommand.cs
src/PSRule/Runtime/RunspaceContext.cs
tests/PSRule.Tests/FromFileConventions.Rule.ps1
tests/PSRule.Tests/PSRule.Conventions.Tests.ps1

- Fixed null reference in convention for nested exceptions. #725
Fixes #725 

Fixed null reference in convention #725

---

docs/CHANGELOG-v1.md
src/PSRule/Common/PSObjectExtensions.cs
src/PSRule/Data/TargetSourceInfo.cs
src/PSRule/Pipeline/PipelineReader.cs
src/PSRule/Runtime/PSRuleMemberInfo.cs
tests/PSRule.Tests/PSRule.Common.Tests.ps1
tests/PSRule.Tests/PipelineTests.cs
tests/PSRule.Tests/SourceTests.cs

- Added support for source location of pipeline objects. #729
Fixes #729 

Add source location of pipeline objects #729

---

docs/CHANGELOG-v1.md
docs/commands/PSRule/en-US/Assert-PSRule.md
docs/commands/PSRule/en-US/New-PSRuleOption.md
docs/commands/PSRule/en-US/Set-PSRuleOption.md
docs/concepts/PSRule/en-US/about_PSRule_Options.md
docs/upgrade-notes.md
schemas/PSRule-options.schema.json
src/PSRule/Common/JsonConverters.cs
src/PSRule/Common/StringExtensions.cs
src/PSRule/Common/YamlConverters.cs
src/PSRule/Configuration/OutputOption.cs
src/PSRule/Configuration/OutputStyle.cs
src/PSRule/Data/TargetSourceInfo.cs
src/PSRule/PSRule.csproj
src/PSRule/PSRule.psm1
src/PSRule/Pipeline/AssertPipeline.cs
src/PSRule/Pipeline/InvokeResult.cs
src/PSRule/Pipeline/PipelineReciever.cs
src/PSRule/Resources/FormatterStrings.Designer.cs
src/PSRule/Resources/FormatterStrings.resx
src/PSRule/Rules/RuleHelpInfo.cs
src/PSRule/Runtime/PSRuleMemberInfo.cs
tests/PSRule.Tests/PSRule.Options.Tests.ps1
tests/PSRule.Tests/SemanticBreakTests.cs

- Added support for Visual Studio Code with `VisualStudioCode` style. #731
- Updated output format provides support for problem matchers in task output.
- Automatically detect output style from environment variables. #732
- _Assert-PSRule_ now defaults to `Detect` instead of `Client`.
Fixes #731 
Fixes #732 

Added VSCode support and style detection #731 #732

---

docs/CHANGELOG-v1.md

What's changed since v1.3.0:
- PSRule banner can be configured in output when using `Assert-PSRule`. #708
- Source location of objects are included in results.
- Source location of objects from JSON and YAML input files are read automatically. #624
- Source location of objects from the pipeline are read from properties. #729
- Assert output improvements:
- Added support for Visual Studio Code with `VisualStudioCode` style. #731
- Updated output format provides support for problem matchers in task output.
- Automatically detect output style from environment variables. #732
- _Assert-PSRule_ now defaults to `Detect` instead of `Client`.
- Improved support for version constraints by:
- Constraints can include prerelease versions of other matching versions. #714
- …

Release v1.4.0

---

docs/CHANGELOG-v1.md
schemas/PSRule-options.schema.json

- Fixed options schema should allow spacing after `@pre`.
Fixes #743

Fixes schema requires #743

---

docs/CHANGELOG-v1.md
src/PSRule/Definitions/Selectors/SelectorExpressions.cs
tests/PSRule.Tests/SelectorTests.cs

- Fixed match selector expression passing on missing field.
Fixes #745

Fixed match selector expression #745

---

docs/CHANGELOG-v1.md

What's changed since v1.4.0:
- Added string selector conditions. #747
- Use `startWith`, `contains`, and `endsWith` to check for a sub-string.
- Use `isString`, `isLower`, and `isUpper` to check for string type and casing.
- Engineering:
- Bump YamlDotNet dependency to 11.2.1. #740
- Bug fixes:
- Fixed options schema should allow spacing after `@pre`. #743
- Fixed match selector expression passing on missing field. #745
What's changed since pre-release v1.5.0-B2107009:
- No additional changes.

Release v1.5.0

---

README.md
docs/CHANGELOG-v1.md
docs/commands/PSRule/en-US/Assert-PSRule.md
docs/commands/PSRule/en-US/Get-PSRule.md
docs/commands/PSRule/en-US/Get-PSRuleBaseline.md
docs/commands/PSRule/en-US/Invoke-PSRule.md
docs/commands/PSRule/en-US/New-PSRuleOption.md
docs/commands/PSRule/en-US/Set-PSRuleOption.md
docs/concepts/PSRule/en-US/about_PSRule_Options.md
ps-rule.yaml
schemas/PSRule-options.schema.json
src/PSRule/Configuration/ExecutionOption.cs
src/PSRule/Configuration/IncludeOption.cs
src/PSRule/Configuration/PSRuleOption.cs
src/PSRule/PSRule.psm1
src/PSRule/Pipeline/SourcePipeline.cs
tests/PSRule.Tests/PSRule.Common.Tests.ps1
tests/PSRule.Tests/PSRule.Options.Tests.ps1
tests/PSRule.Tests/PSRule.Tests7.yml
tests/PSRule.Tests/PSRule.Tests8.yml
tests/PSRule.Tests/rules/.ps-rule/Common.Rule.ps1
tests/PSRule.Tests/rules/Test.Rule.ps1
tests/PSRule.Tests/rules/extra/Extra.Rule.ps1
tests/PSRule.Tests/rules/main/Main.Rule.ps1

- Default rule source location `.ps-rule/` is automatically included. #742
- Added `Include.Path` and `Include.Module` options to automatically include rule sources.
Fixes #742 

Automatically include default path #742

---

README.md
docs/CHANGELOG-v1.md
docs/commands/PSRule/en-US/New-PSRuleOption.md
docs/commands/PSRule/en-US/Set-PSRuleOption.md
docs/commands/PSRule/en-US/toc.yml
docs/concepts/PSRule/en-US/about_PSRule_Options.md
schemas/PSRule-options.schema.json
src/PSRule/Configuration/InputOption.cs
src/PSRule/PSRule.psm1
src/PSRule/Pipeline/GetTargetPipeline.cs
src/PSRule/Pipeline/InvokeRulePipeline.cs
src/PSRule/Pipeline/PathFilter.cs
tests/PSRule.Tests/PSRule.Options.Tests.ps1
tests/PSRule.Tests/PSRule.Tests.yml
tests/PSRule.Tests/PathFilterTests.cs
tests/PSRule.Tests/Selectors.Rule.yaml

- Automatically exclude common repository files from input files. #721
- Added `Input.IgnoreRepositoryCommon` option to change default behavior.
Fixes #721 

Automatically exclude common repository files #721

---

docs/CHANGELOG-v1.md
docs/concepts/PSRule/en-US/about_PSRule_Assert.md
src/PSRule/Resources/ReasonStrings.Designer.cs
src/PSRule/Resources/ReasonStrings.resx
src/PSRule/Runtime/Assert.cs
src/PSRule/Runtime/AssertResult.cs
tests/PSRule.Tests/AssertTests.cs
tests/PSRule.Tests/FromFileAssert.Rule.ps1
tests/PSRule.Tests/PSRule.Assert.Tests.ps1

- Added aggregation assertion methods for `AnyOf` and `AllOf`. #776
Fixes #776 

Added aggregation assertions AnyOf and AllOf #776

---

docs/CHANGELOG-v1.md
src/PSRule/Common/YamlConverters.cs
src/PSRule/Configuration/PSRuleOption.cs
src/PSRule/Host/HostHelper.cs
tests/PSRule.Tests/Baseline.Rule.yaml
tests/PSRule.Tests/BaselineTests.cs
tests/PSRule.Tests/ConfigurationTests.cs
tests/PSRule.Tests/PSRule.Options.Tests.ps1
tests/PSRule.Tests/PSRule.Tests.yml

- Fixed configuration array deserializes as dictionary from YAML options.
Fixes #779

Fixes configuration array as dictionary #779

---

docs/CHANGELOG-v1.md

What's changed since v1.6.0:
- Added support for generating badges from rule results. #623
- Standard or custom badges can be generated using a convention and the badge API.
- Rule results now include a run ID or each run. #774
- Run ID is returned in `Assert-PSRule` output at the end of each run by default.
- By default a unique `runId` is generated when the rule is run.
- The `Output.Footer`option was added to configure the output footer.
- Automatically exclude common repository files from input files. #721
- Added `Input.IgnoreRepositoryCommon` option to change default behavior.
- Added aggregation assertion methods for `AnyOf` and `AllOf`. #776
- Allow baselines to include local rules. #756
- The `Rule.IncludeLocal`option was automatically …

Release v1.7.0

---

docs/CHANGELOG-v1.md
src/PSRule/Definitions/Resource.cs
src/PSRule/Definitions/Rules/Rule.cs
tests/PSRule.Tests/RulesTests.cs

- Fixed ResourceTags does not contain a method named ToHashtable.
Fixes #798

Fixed resource tags ToHashtable method #798

---

docs/CHANGELOG-v1.md
src/PSRule/Host/HostHelper.cs
src/PSRule/PSRule.Format.ps1xml
src/PSRule/PSRule.psm1
src/PSRule/Pipeline/OptionContext.cs
src/PSRule/Pipeline/SourcePipeline.cs
src/PSRule/Resources/ViewStrings.Designer.cs
src/PSRule/Resources/ViewStrings.resx
src/PSRule/Runtime/LanguageScope.cs
tests/PSRule.Tests/BaselineTests.cs
tests/PSRule.Tests/PSRule.Baseline.Tests.ps1

- Fixed `Get-PSRuleBaseline` does not return any results from module.
Fixes #801

Fixed get baseline from module #801

---

docs/CHANGELOG-v1.md
docs/concepts/PSRule/en-US/about_PSRule_Assert.md
src/PSRule/Runtime/AssertResult.cs
tests/PSRule.Tests/AssertTests.cs

- Added support for conditional reason messages with `ReasonIf`. #804

Added support for ReasonIf #804

---

.vscode/launch.json
.vscode/settings.json
docs/CHANGELOG-v1.md
docs/commands/PSRule/en-US/Get-PSRuleBaseline.md
docs/concepts/PSRule/en-US/about_PSRule_Options.md
src/PSRule/Common/YamlConverters.cs
src/PSRule/Definitions/Resource.cs
src/PSRule/PSRule.psm1
src/PSRule/Pipeline/GetBaselinePipeline.cs
src/PSRule/Pipeline/Output/YamlOutputWriter.cs
tests/PSRule.Tests/BaselineTests.cs

Fix #326 
Added `OutputFormat` option for `Get-PSRuleBaseline` cmdlet.
Serializes as shown below:
```powershell
> Get-PSRuleBaseline -Module PSRule.Rules.Azure -Path ..\PSRule.Rules.Azure\ -Name Azure.GA_2021_09  -OutputFormat Yaml
- - apiVersion: github.com/microsoft/PSRule/v1
kind: Baseline
metadata:
annotations: {}
name: Azure.GA_2021_09
tags: {}
spec:
binding:
configuration:
convention:
rule:
exclude:
include: 
includeLocal:
tag:
ruleSet:
- 2020_06
- 2020_09
- 2020_12
- 2021_03
- 2021_06
- 2021_09
release: GA
```

Added Yaml OutputFormat option for Get-PSRuleBaseline cmdlet

---

docs/CHANGELOG-v1.md
pipeline.build.ps1
tests/PSRule.Tests/PSRule.AllOf.Tests.ps1
tests/PSRule.Tests/PSRule.AnyOf.Tests.ps1
tests/PSRule.Tests/PSRule.Assert.Tests.ps1
tests/PSRule.Tests/PSRule.Badges.Tests.ps1
tests/PSRule.Tests/PSRule.Baseline.Tests.ps1
tests/PSRule.Tests/PSRule.Common.Tests.ps1
tests/PSRule.Tests/PSRule.Conventions.Tests.ps1
tests/PSRule.Tests/PSRule.EndToEnd.Tests.ps1
tests/PSRule.Tests/PSRule.Exists.Tests.ps1
tests/PSRule.Tests/PSRule.Match.Tests.ps1
tests/PSRule.Tests/PSRule.Options.Tests.ps1
tests/PSRule.Tests/PSRule.PSGallery.Tests.ps1
tests/PSRule.Tests/PSRule.Reason.Tests.ps1
tests/PSRule.Tests/PSRule.Recommend.Tests.ps1
tests/PSRule.Tests/PSRule.Selectors.Tests.ps1
tests/PSRule.Tests/PSRule.TypeOf.Tests.ps1
tests/PSRule.Tests/PSRule.Variables.Tests.ps1
tests/PSRule.Tests/PSRule.Within.Tests.ps1

Fix #478
Converted to pester v5 tests syntax and v5.3.0 module version. 

Pester v5 migration

---

docs/CHANGELOG-v1.md
docs/commands/PSRule/en-US/Get-PSRule.md
docs/concepts/PSRule/en-US/about_PSRule_Options.md
src/PSRule/Common/JsonConverters.cs
src/PSRule/PSRule.psm1
src/PSRule/Pipeline/Output/JsonOutputWriter.cs
src/PSRule/Pipeline/SourcePipeline.cs
tests/PSRule.Tests/PSRule.Common.Tests.ps1

Fix #128
```pwsh
Get-PSRule -Module PSRule.Rules.Azure -Path ..\PSRule.Rules.Azure\ -OutputFormat Yaml -Name Azure.AKS.AutoScaling
```
```yaml
- info:
annotations:
pillar: Performance Efficiency
severity: Important
category: Performance
resource: Azure Kubernetes Service
online version: https://azure.github.io/PSRule.Rules.Azure/en/rules/Azure.AKS.AutoScaling/
description: In addition to perform manual scaling, AKS clusters support autoscaling. Autoscaling reduces manual intervention required to scale a cluster to keep up with application demands.
displayName: Enable AKS cluster autoscaler
moduleName: PSRule.Rules.Azure
name: Azure.AKS.AutoScaling
recommendation: Consider enabling autoscaling for AKS clusters deployed with virtual machine scale sets.
synopsis: Use Autoscaling to ensure …
```

Added Yaml/Json output format options for Get-PSRule

---

docs/CHANGELOG-v1.md

What's changed since pre-release v1.8.0-B2110006:
- Engine features
- Added YAML/JSON output format support for `Get-PSRule`. #128
- Engineering:
- Migration of Pester v4 tests to Pester v5. #478

Pre-release v1.8.0-B2110020

---

docs/CHANGELOG-v1.md

What's changed since pre-release v1.9.0-B2111009:
- Allow downstream issues to be consumed. #843
- Objects can be flagged with issues that have been generated externally.
- Migrated default baseline to module configuration. #809
- This enables configuration of the default baseline for a module with a module configuration.
- This depreciate configuring the default baseline within the module manifest.
- Modules using manifest configuration will start warning from v1.9.0.
- Added JSON support to read baselines from pipeline. #845
- Engineering:
- Bump System.Drawing.Common dependency to v6.0.0. #848

Pre-release v1.9.0-B2111024

---

docs/CHANGELOG-v1.md

What's changed since v1.8.0:
- Added improvements to YAML output for `Get-PSRuleBaseline`. #829
- Added `-Initialize` convention block. #826
- Use this block to perform any initialization that is required before any rules are run.
- This block is only run once instead of `-Begin` which is run once per object.
- Allow lifetime services to be used. #827
- Use `$PSRule.AddService` and `$PSRule.GetService` to add a service.
- Services allows a singleton instance to be used and shared across multiple rules.
- PSRule will automatically dispose the service when all rules have run.
- Added `Export-PSRuleBaseline` cmdlet to export baseline. #622
- Added JSON output format for Baseline cmdlets. #839
- Allow downstream issues to be consumed. #843
- Objects can be flagged with …

Release v1.9.0

---

docs/CHANGELOG-v1.md
docs/concepts/PSRule/en-US/about_PSRule_Rules.md
docs/concepts/PSRule/en-US/about_PSRule_Selectors.md
src/PSRule/Commands/NewRuleDefinitionCommand.cs
src/PSRule/Common/JsonConverters.cs
src/PSRule/Host/HostHelper.cs
src/PSRule/Pipeline/ExportBaselinePipelineBuilder.cs
src/PSRule/Pipeline/GetBaselinePipeline.cs
src/PSRule/Pipeline/GetRulePipeline.cs
src/PSRule/Pipeline/GetRulePipelineBuiler.cs
tests/PSRule.Tests/BaselineTests.cs
tests/PSRule.Tests/FromFile.Rule.jsonc
tests/PSRule.Tests/FromFileWithSelectors.Rule.ps1
tests/PSRule.Tests/PSRule.Common.Tests.ps1
tests/PSRule.Tests/PSRule.Selectors.Tests.ps1
tests/PSRule.Tests/Selectors.Rule.jsonc

Fix #857
Added JSON support for reading rules and selectors. 
Also did some refactoring and cleanup with some previous baseline code. 

Added JSON support for reading rules and selectors from pipeline

---

README.md
docs/CHANGELOG-v1.md
docs/concepts/PSRule/en-US/about_PSRule_Assert.md
docs/concepts/PSRule/en-US/about_PSRule_Expressions.md
schemas/PSRule-language.schema.json
src/PSRule/Common/ExpressionHelpers.cs
src/PSRule/Definitions/Expressions/ExpressionContext.cs
src/PSRule/Definitions/Expressions/LanguageExpressions.cs
src/PSRule/Resources/ReasonStrings.Designer.cs
src/PSRule/Resources/ReasonStrings.resx
src/PSRule/Runtime/Assert.cs
src/PSRule/Runtime/ObjectHelper.cs
tests/PSRule.Tests/AssertTests.cs
tests/PSRule.Tests/SelectorTests.cs
tests/PSRule.Tests/Selectors.Rule.yaml

- Added `HasSchema` expression to check the schema of an object. #860
- Fixed `$Assert.HasJsonSchema` accepts empty value. #859
Fixes #860 
Fixes #859 

Add HasSchema expression #860 #859

---

docs/CHANGELOG-v1.md
src/PSRule/Pipeline/PipelineContext.cs
tests/PSRule.Tests/TestModule4/rules/Config.Rule.yaml

- Fixed module configuration is not loaded when case does not match.
Fixes #864

Fix module config casing #864

---

.github/ISSUE_TEMPLATE/bug_report.md
docs/CHANGELOG-v1.md

What's changed since v1.9.0:
- Added JSON support for reading rules and selectors from pipeline. #857
- Added `HasSchema` expression to check the schema of an object. #860
- Bug fixes:
- Fixed `$Assert.HasJsonSchema` accepts empty value. #859
- Fixed module configuration is not loaded when case does not match. #864
What's changed since pre-release v1.10.0-B2112002:
- No additional changes.

Release v1.10.0

---

.azure-pipelines/azure-pipelines.yaml
docs/install-instructions.md

- Bump CI version to v1.11.0.
- Updated pipeline CI images to the latest versions, removing CI for Windows 2016.
- Update docs to point to the latest versions of PowerShell.

Bump CI pipeline images and version

---

README.md
docs/CHANGELOG-v1.md
docs/concepts/PSRule/en-US/about_PSRule_Expressions.md
docs/concepts/PSRule/en-US/about_PSRule_Selectors.md
schemas/PSRule-language.schema.json
src/PSRule/Common/ExpressionHelpers.cs
src/PSRule/Definitions/Expressions/LanguageExpressions.cs
tests/PSRule.Tests/SelectorTests.cs
tests/PSRule.Tests/Selectors.Rule.yaml

- Added `version` expression to check semantic version constraints. #861
- Added `hasDefault` expression to check field default value. #870
Fixes #861
Fixes #870

Added version and hasDefault expression #861 #870

---

docs/CHANGELOG-v1.md
src/PSRule/Runtime/AssertResult.cs
tests/PSRule.Tests/AssertTests.cs

Fix #874
Also did some code refactoring and turned `GetReason()` and `ToString()` into ternary operators.

Fix GetReason method returning no reasons #874

---

.github/workflows/stale.yaml

- Added `waiting-feedback` label to stale issue management.

Added waiting-feedback label for stale issues

---

docs/CHANGELOG-v1.md

What's changed since v1.10.0:
- Added `version` expression to check semantic version constraints. #861
- Added `hasDefault` expression to check field default value. #870
- Bug fixes:
- Fixed `GetReason()` not returning results for a failed assertion. #874
What's changed since pre-release v1.11.0-B2112016:
- No additional changes.

Release v1.11.0

---

CHANGELOG.md
docs/CHANGELOG-v0.md
docs/CHANGELOG-v1.md
docs/authoring/packaging-rules/Enterprise.Rules/Enterprise.Rules.psd1
docs/authoring/packaging-rules/Enterprise.Rules/rules/Config.Rule.yaml
docs/upgrade-notes.md
mkdocs.yml
src/PSRule/Common/JsonConverters.cs
src/PSRule/Common/ResourceExtensions.cs
src/PSRule/Common/YamlConverters.cs
src/PSRule/Definitions/Resource.cs
src/PSRule/Definitions/Spec.cs
src/PSRule/Pipeline/PipelineContext.cs
src/PSRule/Pipeline/SourcePipeline.cs
src/PSRule/Resources/PSRuleResources.Designer.cs
src/PSRule/Resources/PSRuleResources.resx
src/PSRule/Runtime/RunspaceContext.cs
tests/PSRule.Tests/Baseline.Rule.yaml
tests/PSRule.Tests/BaselineTests.cs
tests/PSRule.Tests/PSRule.Baseline.Tests.ps1
tests/PSRule.Tests/TestModule6/TestModule6.psd1
tests/PSRule.Tests/TestModule7/TestModule7.psd1

- **Breaking change:** Removal of deprecated default baseline from module manifest. #755
- Set the default module baseline using module configuration.
- **Breaking change:** Require `apiVersion` on YAML and JSON to be specified. #648
- Resources should use `github.com/microsoft/PSRule/v1` as the `apiVersion`.
- Resources that do not specify an `apiVersion` will be ignored.
Fixes #755 
Fixes #648 

Clean up #755 #648

---

CHANGELOG.md
README.md
docs/CHANGELOG-v1.md
docs/concepts/PSRule/en-US/about_PSRule_SuppressionGroups.md
docs/hooks.py
mkdocs.yml
schemas/PSRule-language.schema.json
schemas/PSRule-resources.schema.json
src/PSRule/Definitions/Expressions/LanguageExpressions.cs
src/PSRule/Definitions/Resource.cs
src/PSRule/Definitions/ResourceId.cs
src/PSRule/Definitions/ResourceIndex.cs
src/PSRule/Definitions/Spec.cs
src/PSRule/Definitions/SuppressionGroups/SuppressionGroup.cs
src/PSRule/Definitions/SuppressionGroups/SuppressionGroupVisitor.cs
src/PSRule/Host/HostHelper.cs
src/PSRule/Pipeline/InvokeRulePipeline.cs
src/PSRule/Pipeline/PipelineContext.cs
src/PSRule/Resources/PSRuleResources.Designer.cs
src/PSRule/Resources/PSRuleResources.resx
src/PSRule/Rules/SuppressionFilter.cs
src/PSRule/Runtime/RunspaceContext.cs
tests/PSRule.Tests/PSRule.Common.Tests.ps1
tests/PSRule.Tests/PSRule.Tests.csproj
tests/PSRule.Tests/SuppressionFilterTests.cs
tests/PSRule.Tests/SuppressionGroupTests.cs
tests/PSRule.Tests/SuppressionGroups.Rule.yaml

Fix #793.
Added `SuppressionGroup` resource which can suppress rules based on selector expression.

Added support for Suppression Groups

---

.vscode/settings.json
README.md
docs/CHANGELOG-v1.md
docs/concepts/PSRule/en-US/about_PSRule_Options.md
docs/scenarios/azure-tags/ps-rule.yaml
docs/scenarios/kubernetes-resources/ps-rule.yaml
pipeline.build.ps1
schemas/PSRule-options.schema.json
src/PSRule/Configuration/ExecutionOption.cs
src/PSRule/PSRule.psm1
src/PSRule/Pipeline/GetRuleHelpPipeline.cs
src/PSRule/Pipeline/GetRulePipelineBuiler.cs
src/PSRule/Pipeline/InvokeRulePipeline.cs
src/PSRule/Runtime/RunspaceContext.cs
tests/PSRule.Tests/PSRule.Common.Tests.ps1
tests/PSRule.Tests/PSRule.Options.Tests.ps1
tests/PSRule.Tests/PSRule.Tests.yml
tests/PSRule.Tests/PSRule.Tests10.yml
tests/PSRule.Tests/PSRule.Tests11.yml
tests/PSRule.Tests/PSRule.Tests12.yml
tests/PSRule.Tests/PSRule.Tests13.yml
tests/PSRule.Tests/PSRule.Tests5.yml
tests/PSRule.Tests/PSRule.Tests9.yml
tests/PSRule.Tests/PipelineTests.cs

Fix #899.
Added `Execution.InvariantCultureWarning` option.

Added Invariant Culture Warning option

---

docs/CHANGELOG-v2.md
docs/upgrade-notes.md
src/PSRule/Common/RunspaceContextExtensions.cs
src/PSRule/Host/HostHelper.cs
src/PSRule/PSRule.psm1
src/PSRule/Resources/PSRuleResources.Designer.cs
src/PSRule/Resources/PSRuleResources.resx
tests/PSRule.Tests/PSRule.Common.Tests.ps1
tests/PSRule.Tests/TestModule8/TestModule8.psd1
tests/PSRule.Tests/TestModule8/rules/Test.Rule.ps1

Fix #610.
Added code change to prefer module sources over loose files. 
Ensured loose files detected by PWD is moved after module sources are discovered, to ensure modules are looked at first.
Also used a hashset approach to keep track rule names and ids, then add a warning for duplicate rule names and throw an error for duplicate rule IDs if any are found.

Prefer module sources over loose files

---

docs/CHANGELOG-v2.md
src/PSRule/Common/JsonConverters.cs
src/PSRule/Host/HostHelper.cs
src/PSRule/Pipeline/Output/JsonOutputWriter.cs
tests/PSRule.Tests/Baseline.Rule.jsonc
tests/PSRule.Tests/BaselineTests.cs
tests/PSRule.Tests/ConfigTests.cs
tests/PSRule.Tests/ModuleConfig.Rule.jsonc
tests/PSRule.Tests/PSRule.Tests.csproj
tests/PSRule.Tests/RulesTests.cs
tests/PSRule.Tests/SelectorTests.cs
tests/PSRule.Tests/Selectors.Rule.jsonc
tests/PSRule.Tests/SuppressionGroupTests.cs
tests/PSRule.Tests/SuppressionGroups.Rule.jsonc

Fixes #929.
Fixes #833.
Made the following changes:
- Added more JSON tests for baselines, module configs and selectors.
- Refactored `HostHelper.cs` test methods to fetch language blocks for YAML and JSON.
- Updated JSON contract resolver to always serialize properties to camelcase.

Added more JSON tests and refactoring

---

docs/CHANGELOG-v2.md
src/PSRule/Definitions/Expressions/LanguageExpressions.cs
src/PSRule/Definitions/ResourceIndex.cs
src/PSRule/Rules/SuppressionFilter.cs
tests/PSRule.Tests/PSRule.Common.Tests.ps1
tests/PSRule.Tests/SuppressionGroups2.Rule.yaml

Fixes #931
Fixes #932
Added code changes to handle undefined rules and `rule: []`. Both run suppression group against all rules where the selector matches.

Fix suppression group undefined or empty rules

---

docs/CHANGELOG-v2.md

What's changed since pre-release v2.0.0-B2201117:
- Engineering:
- **Breaking change:** Prefer module sources over loose files. #610
- Module sources are discovered before loose files.
- Warning is shown for duplicate rule names, and exception is thrown for duplicate rule Ids.
- Added more tests for JSON resources. #929
- Bug fixes:
- Fixed empty suppression group rules property applies to no rules. #931
- Fixed object reference for suppression group will rule not defined. #932

Pre-release v2.0.0-B2201135

---

docs/CHANGELOG-v2.md
docs/commands/PSRule/en-US/Assert-PSRule.md
docs/commands/PSRule/en-US/Export-PSRuleBaseline.md
docs/commands/PSRule/en-US/Get-PSRule.md
docs/commands/PSRule/en-US/Get-PSRuleBaseline.md
docs/commands/PSRule/en-US/Invoke-PSRule.md
docs/commands/PSRule/en-US/New-PSRuleOption.md
docs/commands/PSRule/en-US/Set-PSRuleOption.md
docs/commands/PSRule/en-US/Test-PSRuleTarget.md
docs/upgrade-notes.md
src/PSRule/Common/StringExtensions.cs
src/PSRule/PSRule.psm1
src/PSRule/Pipeline/SourcePipeline.cs
tests/PSRule.Tests/PSRule.Common.Tests.ps1

Fixes #760
Fixes #939
Added code changes to remove `$PWD` from `-Path` by default. 

Require rule sources from current working directory to be explicitly included

---

docs/CHANGELOG-v2.md

What's changed since pre-release v2.0.0-B2201135:
- Engineering:
- **Breaking change:** Require rule sources from current working directory to be explicitly included. #760
- From v2 onwards, `$PWD` is not included by default unless `-Path .` or `-Path $PWD` is explicitly specified.
- Bug fixes:
- Fixed rule source loading twice from `$PWD` and `.ps-rule/`. #939

Pre-release v2.0.0-B2201146

---

docs/CHANGELOG-v2.md
docs/commands/PSRule/en-US/Assert-PSRule.md
docs/commands/PSRule/en-US/Invoke-PSRule.md
docs/commands/PSRule/en-US/New-PSRuleOption.md
docs/commands/PSRule/en-US/Set-PSRuleOption.md
docs/concepts/PSRule/en-US/about_PSRule_Options.md
schemas/PSRule-options.schema.json
src/PSRule.Badges/PSRule.Badges.csproj
src/PSRule.Benchmark/PSRule.Benchmark.csproj
src/PSRule.BuildTool/PSRule.BuildTool.csproj
src/PSRule/Common/OutputOptionExtensions.cs
src/PSRule/Configuration/OutputFormat.cs
src/PSRule/Data/TargetSourceInfo.cs
src/PSRule/PSRule.csproj
src/PSRule/PSRule.psm1
src/PSRule/Pipeline/Output/SarifOutputWriter.cs
src/PSRule/Pipeline/PipelineBuilder.cs
src/PSRule/Pipeline/SourcePipeline.cs
src/PSRule/Resources/FormatterStrings.Designer.cs
src/PSRule/Resources/FormatterStrings.resx
src/PSRule/Resources/ReportStrings.Designer.cs
src/PSRule/Resources/ReportStrings.resx
tests/PSRule.Tests/OutputWriterTests.cs
tests/PSRule.Tests/PSRule.Baseline.Tests.ps1
tests/PSRule.Tests/PSRule.Common.Tests.ps1

- Added support for formatting results as SARIF.
- Set `Output.Format` to `Sarif` to output results in the SARIF format.
Fixes #878

Added SARIF support #878

---

docs/CHANGELOG-v2.md

What's changed since pre-release v2.0.0-B2201146:
- Added support for rule severity level. #880
- Rules can be configured to be `Error`, `Warning`, or `Information`.
- Failing rules with the `Error` severity level will cause the pipeline to fail.
- Rules with the `Warning` severity level will be reported as warnings.
- Rules with the `Information` severity level will be reported as informational messages.
- By default, the severity level for a rule is `Error`.
- Added expression support for type based assertions. #908
- Included the following expressions:
- `IsArray`
- `IsBoolean`
- `IsDateTime`
- `IsInteger`
- `IsNumeric`
- Added support for formatting results as SARIF. #878
- Set `Output.Format` to `Sarif` to output results in the SARIF format.

Pre-release v2.0.0-B2201161

---

docs/CHANGELOG-v2.md
src/PSRule/Host/HostHelper.cs
tests/PSRule.Tests/FromFile.Rule.jsonc
tests/PSRule.Tests/FromFileEmpty.Rule.jsonc
tests/PSRule.Tests/FromFileEmpty.Rule.yaml
tests/PSRule.Tests/PSRule.Common.Tests.ps1

Fixed Invoke-PSRule hanging if JSON rule file is empty

---

docs/CHANGELOG-v2.md
docs/commands/PSRule/en-US/Export-PSRuleBaseline.md
docs/commands/PSRule/en-US/New-PSRuleOption.md
docs/commands/PSRule/en-US/Set-PSRuleOption.md
docs/concepts/PSRule/en-US/about_PSRule_Options.md
schemas/PSRule-options.schema.json
src/PSRule/Common/GitHelper.cs
src/PSRule/Configuration/BannerFormat.cs
src/PSRule/Configuration/PSRuleOption.cs
src/PSRule/Configuration/RepositoryOption.cs
src/PSRule/PSRule.psm1
src/PSRule/Pipeline/Formatters/AssertFormatter.cs
src/PSRule/Pipeline/Output/SarifOutputWriter.cs
src/PSRule/Pipeline/PipelineReciever.cs
src/PSRule/Resources/FormatterStrings.Designer.cs
src/PSRule/Resources/FormatterStrings.resx
tests/PSRule.Tests/OutputWriterTests.cs
tests/PSRule.Tests/PSRule.Options.Tests.ps1
tests/PSRule.Tests/PSRule.Tests.yml

- Capture and output repository info in Assert-PSRule runs. #978
- Added `Repository.Url` option set repository URL reported in output.
- Repository URL is detected automatically for GitHub Actions and Azure Pipelines.
- Added `RepositoryInfo` to `Output.Banner` option.
- Repository info is shown by default.
- Fixed SARIF should report base branch. #964
Fixes #978
Fixes #964

Added repository info in output #978 #964

---

docs/CHANGELOG-v2.md
docs/concepts/PSRule/en-US/about_PSRule_Expressions.md
schemas/PSRule-language.schema.json
src/PSRule/Common/ExpressionHelpers.cs
src/PSRule/Definitions/Expressions/LanguageExpressions.cs
tests/PSRule.Tests/SelectorTests.cs
tests/PSRule.Tests/Selectors.Rule.jsonc
tests/PSRule.Tests/Selectors.Rule.yaml

- Added `convert` and `caseSensitive` to string comparison expressions.
- The following expressions support type convertion and case-sensitive comparison.
- `startsWith`, `contains`, and `endsWith`.
- `equals` and `notEquals`.
Fixes #1001 

Add type conversion and case-sensitivity #1001

---

docs/CHANGELOG-v2.md

What's changed since pre-release v2.0.0-B2203019:
- Added `Extent` property on rules reported by `Get-PSRule`. #990
- Extent provides the line and position of the rule in the source code.
- Engineering:
- Bump Sarif.Sdk to 2.4.13. #1007
- Bump PowerShellStandard.Library to 5.1.1. #999

Pre-release v2.0.0-B2203033

---

docs/CHANGELOG-v2.md
docs/concepts/PSRule/en-US/about_PSRule_Expressions.md
schemas/PSRule-language.schema.json
src/PSRule/Definitions/Expressions/LanguageExpressions.cs
tests/PSRule.Tests/SelectorTests.cs
tests/PSRule.Tests/Selectors.Rule.jsonc
tests/PSRule.Tests/Selectors.Rule.yaml

- Added `convert` to numeric comparison expressions. #943
- Type conversion is now supported for `less`, `lessOrEquals`, `greater`, and `greaterOrEquals`.
Fixes #943 

Added convert to numeric expressions #943

---

.github/ISSUE_TEMPLATE/bug_report.md
.vscode/settings.json
CHANGELOG.md
docs/CHANGELOG-v1.md
docs/CHANGELOG-v2.md
docs/upgrade-notes.md

What's changed since v1.11.1:
- Add support for suppression groups. #793
- New `SuppressionGroup` resource has been included.
- Added source expression property. #933
- Included the following expressions:
- `source`
- `withinPath`
- `notWithinPath`
- Added support for rule severity level. #880
- Rules can be configured to be `Error`, `Warning`, or `Information`.
- Failing rules with the `Error` severity level will cause the pipeline to fail.
- Rules with the `Warning` severity level will be reported as warnings.
- Rules with the `Information` severity level will be reported as informational messages.
- By default, the severity level for a rule is `Error`.
- Added expression support for type based assertions. #908
- Included the following expressions:
- `IsArray`
- …

Release v2.0.0

---

docs/CHANGELOG-v2.md
src/PSRule/Common/JsonConverters.cs
src/PSRule/Pipeline/Formatters/AssertFormatter.cs
tests/PSRule.Tests/ObjectFromFile.json
tests/PSRule.Tests/PSRule.Common.Tests.ps1
tests/PSRule.Tests/PathExpressionTests.cs

- Fixed read JSON failed with comments. #1051
- Fixed null reference on elapsed time when required module check fails. #1054
- Fixed failed to read JSON objects with a empty property name. #1052
Fixes #1051 
Fixes #1054 
Fixes #1052 

Fix JSON parsing and null ref #1051 #1054 #1052

---

requirements-docs.txt

This reverts commit 52ff32d0cdecdfb685035951dceb1e53aaa330d7.
- Compatibility issue with mkdocs-material v8.2.11.

Revert "Bump pymdown-extensions from 9.3 to 9.4 (#1066)"

---

docs/CHANGELOG-v2.md

What's changed since v2.0.1:
- Added `notStartsWith`, `notEndsWith`, and `notContains` expressions and assertion helpers. #1047
- Added `like`, `notLike` expressions and assertion helpers. #1048
- Added additional repository paths to ignore by default. #1043
- Added custom suppression message during PSRule runs. #1046
- When a rule is suppressed using a suppression group the synopsis is shown in the suppression warning.
- Configure the suppression group synopsis to display a custom message.
- Suppression groups synopsis can be localized using markdown documentation.
- Use markdown to set a culture specific synopsis.
- Custom suppression messages are not supported when suppressing individual rules using `ps-rule.yaml`.
- Added source support for string conditions. …

Release v2.1.0

---

docs/CHANGELOG-v2.md
tests/PSRule.Tests/PathExpressionTests.cs

Related to #1110
Added more object path tests for current ref comparisons with no dot selector comparisons.
Alot of the other test paths seemed covered already, so not much to add here 🙂. Will add more in the future if I find any.

Added more object path tests

---

docs/CHANGELOG-v2.md
docs/concepts/PSRule/en-US/about_PSRule_Options.md
schemas/PSRule-options.schema.json
src/PSRule/Configuration/FooterFormat.cs
src/PSRule/Pipeline/AssertPipeline.cs
src/PSRule/Pipeline/Output/FileOutputWriter.cs
src/PSRule/Pipeline/PipelineBuilder.cs
src/PSRule/Resources/PSRuleResources.Designer.cs
src/PSRule/Resources/PSRuleResources.resx

- Added informational message when output has been written to disk.
Fixes #1074 

Added output path information #1074

---

docs/CHANGELOG-v2.md
src/PSRule/Runtime/ObjectPath/PathExpressionBuilder.cs
src/PSRule/Runtime/ObjectPath/PathTokenizer.cs
tests/PSRule.Tests/PathExpressionTests.cs
tests/PSRule.Tests/PathTokenizerTests.cs

- Added descendant selector to object path syntax.
[#1133](https://github.com/microsoft/PSRule/issues/1133)
- Use `..` to traverse into child objects, for example `$..name` finds names for all nested objects.
Fixes #1133 

Added object path descendant selector #1133

---

.vscode/settings.json
docs/CHANGELOG-v2.md
src/PSRule.SDK/PSRule.SDK.csproj

- Fixed issue building a PSRule project by removing PSRule.psd1 from compile target.
Fixes #1140 

Fix NuGet compile issue #1140

---

docs/CHANGELOG-v2.md

What's changed since pre-release v2.2.0-B0131:
- Bug fixes:
- Fixed issue building a PSRule project by removing PSRule.psd1 from compile target.
[#1140](https://github.com/microsoft/PSRule/issues/1140)

Pre-release v2.2.0-B0175

---

docs/CHANGELOG-v2.md

What's changed since v2.1.0:
- Added `notCount` expression and assertion helper by @ArmaanMcleod.
[#1091](https://github.com/microsoft/PSRule/issues/1091)
- Improved reporting of the object path that caused rule failures by @BernieWhite.
[#1092](https://github.com/microsoft/PSRule/issues/1092)
- Output include a new `Detail` property with details of the reason and the object path.
- Custom methods `ReasonFrom` and `ReasonIf` accept a `path` parameter to specify the object path.
- Added informational message when output has been written to disk by @BernieWhite.
[#1074](https://github.com/microsoft/PSRule/issues/1074)
- The `Output.Footer` option now supports `OutputFile` which reports the output file path.
This is enabled by default.
- Added …

Release v2.2.0

---

docs/CHANGELOG-v2.md
src/PSRule.SDK/PSRule.SDK.csproj

- Fixed path within SDK package causes `psd1` to compile.
Fixes #1146 

Update pathing for SDK package #1146

---

docs/CHANGELOG-v2.md
schemas/PSRule-options.schema.json

- Added PSRule for Azure expansion configuration to options schema.
Fixes #1149 

Add expansion config to options schema #1149

---

docs/CHANGELOG-v2.md
src/PSRule/Common/ExpressionHelpers.cs
src/PSRule/Configuration/PSRuleOption.cs
tests/PSRule.Tests/ExpressionHelpersTests.cs

- Fixed startIndex cannot be larger than length of string.
Fixes #1160 

Fixes normalize path #1160

---

docs/CHANGELOG-v2.md
src/PSRule/Common/JsonConverters.cs
src/PSRule/Common/PSObjectExtensions.cs
src/PSRule/Runtime/PSRuleMemberInfo.cs
tests/PSRule.Tests/InputFormatDeserializerTests.cs
tests/PSRule.Tests/PipelineTests.cs

- Improved full path support by adding full path from JSON objects.
Fixes #1174 

Added full path from JSON objects #1174

---

docs/CHANGELOG-v2.md
src/PSRule.Badges/PSRule.Badges.csproj
src/PSRule.Benchmark/PSRule.Benchmark.csproj
src/PSRule.BuildTool/PSRule.BuildTool.csproj
src/PSRule.Common.props
src/PSRule.SDK/README.md
src/PSRule.Tool/PSRule.Tool.csproj
src/PSRule/PSRule.csproj
src/PSRule/README.md

- Added support for publishing symbols with NuGet packages.
Fixes #1173

Added support for NuGet symbol packages #1173

---

docs/CHANGELOG-v2.md
docs/concepts/PSRule/en-US/about_PSRule_Assert.md
src/PSRule/Definitions/ResultReason.cs
src/PSRule/Runtime/AssertResult.cs
src/PSRule/Runtime/Operand.cs
tests/PSRule.Tests/AssertTests.cs
tests/PSRule.Tests/FromFile.Rule.ps1
tests/PSRule.Tests/PSRule.Common.Tests.ps1
tests/PSRule.Tests/PipelineTests.cs

- Added `PathPrefix` method to add an object path prefix to assertion reasons.
Fixes #1198 

Added PathPrefix method to add path prefix #1198

---

docs/CHANGELOG-v2.md

What's changed since pre-release v2.3.0-B0130:
- Added `PathPrefix` method to add an object path prefix to assertion reasons by @BernieWhite.
[#1198](https://github.com/microsoft/PSRule/issues/1198)
- Engineering:
- Bump xunit to v2.4.2.
[#1200](https://github.com/microsoft/PSRule/pull/1200)

Pre-release v2.3.0-B0163

---

docs/CHANGELOG-v2.md

What's changed since v2.2.0:
- Added `PathPrefix` method to add an object path prefix to assertion reasons by @BernieWhite.
[#1198](https://github.com/microsoft/PSRule/issues/1198)
- Added support for binding with JSON objects by @BernieWhite.
[#1182](https://github.com/microsoft/PSRule/issues/1182)
- Added support for full path from JSON objects by @BernieWhite.
[#1174](https://github.com/microsoft/PSRule/issues/1174)
- Improved reporting of full object path from pre-processed results by @BernieWhite.
[#1169](https://github.com/microsoft/PSRule/issues/1169)
- Added PSRule for Azure expansion configuration to options schema by @BernieWhite.
[#1149](https://github.com/microsoft/PSRule/issues/1149)
- Engineering:
- Bump xunit to v2.4.2. …

Release v2.3.0

---

.vscode/settings.json
docs/CHANGELOG-v2.md
src/PSRule/Definitions/ResultReason.cs
src/PSRule/Runtime/Operand.cs
tests/PSRule.Tests/AssertTests.cs

- Fixed handling of object path joins when self-identifier is used.
Fixes #1204 

Fixes object path for self identifier #1204

---

docs/CHANGELOG-v2.md
schemas/PSRule-options.schema.json
src/PSRule/Common/GitHelper.cs
src/PSRule/Pipeline/Formatters/AssertFormatter.cs
src/PSRule/Pipeline/Output/SarifOutputWriter.cs
src/PSRule/Pipeline/PipelineBuilder.cs
tests/PSRule.Tests/PSRule.Options.Tests.ps1

- Fixed repository information not in output.
Fixes #1219 

Fixes repository information not in output #1219

---

docs/CHANGELOG-v2.md

What's changed since pre-release v2.4.0-B0063:
- Engineering:
- Bump BenchmarkDotNet to v0.13.2.
[#1241](https://github.com/microsoft/PSRule/pull/1241)
- Bump BenchmarkDotNet.Diagnostics.Windows to v0.13.2.
[#1242](https://github.com/microsoft/PSRule/pull/1242)

Pre-release v2.4.0-B0091

---

.github/ISSUE_TEMPLATE/bug_report.md
docs/CHANGELOG-v2.md

What's changed since v2.3.2:
- **Experimental**: Added support for functions within YAML and JSON expressions by @BernieWhite.
[#1227](https://github.com/microsoft/PSRule/issues/1227)
[#1016](https://github.com/microsoft/PSRule/issues/1016)
- Added conversion functions `boolean`, `string`, and `integer`.
- Added lookup functions `configuration`, and `path`.
- Added string functions `concat`, `substring`.
- See [functions][3] for more information.
- **Experimental**: Added support for sub-selector YAML and JSON expressions by @BernieWhite.
[#1024](https://github.com/microsoft/PSRule/issues/1024)
[#1045](https://github.com/microsoft/PSRule/issues/1045)
- Sub-selector pre-conditions add an additional expression to determine if a rule is executed.
- Sub-selector object filters …

Release v2.4.0

---

README.md
docs/CHANGELOG-v2.md
docs/commands/PSRule/en-US/New-PSRuleOption.md
docs/commands/PSRule/en-US/Set-PSRuleOption.md
docs/concepts/PSRule/en-US/about_PSRule_Options.md
schemas/PSRule-options.schema.json
src/PSRule/Configuration/ExecutionOption.cs
src/PSRule/Configuration/SessionState.cs
src/PSRule/Host/Host.cs
src/PSRule/PSRule.psm1
src/PSRule/Pipeline/PipelineBuilder.cs
src/PSRule/Pipeline/PipelineContext.cs
src/PSRule/Pipeline/PipelineWriter.cs
tests/PSRule.Tests/PSRule.Options.Tests.ps1
tests/PSRule.Tests/PSRule.Tests.yml

- Fixed could not load Microsoft.Management.Infrastructure.
- To use minimal initial session state set `Execution.InitialSessionState` to `Minimal`.
Fixes #1249 

Fixes could not load Microsoft.Management.Infrastructure #1249

---

src/PSRule.BuildTask/PSRule.BuildTask.csproj

This reverts commit 2d78a2bda19820fe2618c429e1eac94d0766ce11.
- Rollback to v4.2.0 of Microsoft.CodeAnalysis.Common to fix an issue with code generation task.

Revert "Bump Microsoft.CodeAnalysis.Common from 4.2.0 to 4.3.0 (#1254)"

---

docs/CHANGELOG-v2.md
src/PSRule/Resources/PSRuleResources.Designer.cs
src/PSRule/Resources/PSRuleResources.resx
src/PSRule/Runtime/ObjectPath/Exceptions.cs
src/PSRule/Runtime/ObjectPath/PathExpressionBuilder.cs
tests/PSRule.Tests/PathExpressionTests.cs

- Fixed exception with `PathExpressionBuilder.GetAllRecurse`.
Fixes #1301 

Fixed PathExpressionBuilder.GetAllRecurse #1301

---

docs/CHANGELOG-v2.md

What's changed since v2.4.2:
- **Experimental**: Added support for only processing changed files by @BernieWhite.
[#688](https://github.com/microsoft/PSRule/issues/688)
- To ignore unchanged files, set the `Input.IgnoreUnchangedPath` option to `true`.
- Added labels metadata from grouping and filtering rules by @BernieWhite.
[#1272](https://github.com/microsoft/PSRule/issues/1272)
- Labels are metadata that extends on tags to provide a more structured way to group rules.
- Rules can be classified by setting the `metadata.labels` property or `-Labels` parameter.
- Provide unblock for command line tools by @BernieWhite.
[#1261](https://github.com/microsoft/PSRule/issues/1261)
- Engineering:
- Bump Microsoft.NET.Test.Sdk to v17.3.1. …

Release v2.5.0

---

docs/CHANGELOG-v2.md

What's changed since v2.5.3:
- Added support for generating job summaries by @BernieWhite.
[#1264](https://github.com/microsoft/PSRule/issues/1264)
- Job summaries provide a markdown output for pipelines in addition to other supported output formats.
- To use, configure the `Output.JobSummaryPath` option.
- Added support for time bound suppression groups by @BernieWhite.
[#1335](https://github.com/microsoft/PSRule/issues/1335)
- Suppression groups can be configured to expire after a specified time by setting the `spec.expiresOn` property.
- When a suppression group expires, the suppression group will generate a warning by default.
- Configure the `Execution.SuppressionGroupExpired` option to ignore or error on expired suppression groups.
- Engineering:
- Bump …

Release v2.6.0

---

docs/CHANGELOG-v2.md
src/PSRule/Common/Engine.cs
src/PSRule/Configuration/PSRuleOption.cs
src/PSRule/Help/MarkdownStream.cs
src/PSRule/Pipeline/CommandLineBuilder.cs
src/PSRule/Pipeline/SourcePipeline.cs
tests/PSRule.Tests/ModuleConfigTests.cs
tests/PSRule.Tests/PSRuleOptionTests.cs

- Fixes exception calling `RuleSource` value cannot be null.
Fixes #1343 

Fixes exception calling RuleSource value #1343

---

src/PSRule/Pipeline/CommandLineBuilder.cs

- Additional clean up of `Path.GetDirectoryName` call.

Additional clean up on #1343

---

README.md
docs/CHANGELOG-v2.md
docs/concepts/PSRule/en-US/about_PSRule_Assert.md
docs/concepts/PSRule/en-US/about_PSRule_Expressions.md
schemas/PSRule-language.schema.json
src/PSRule.Types/Data/DateVersion.cs
src/PSRule.Types/Data/ModuleConstraint.cs
src/PSRule/Definitions/Expressions/LanguageExpressions.cs
src/PSRule/Runtime/Assert.cs
tests/PSRule.Tests/AssertTests.cs
tests/PSRule.Tests/DateVersionTests.cs
tests/PSRule.Tests/SelectorTests.cs
tests/PSRule.Tests/Selectors.Rule.jsonc
tests/PSRule.Tests/Selectors.Rule.yaml
tests/PSRule.Tests/SemanticVersionTests.cs

- Added API version date comparison assertion method and expression.
Fixes #1356 

Added API version date comparison #1356

---

docs/CHANGELOG-v2.md
docs/expressions/functions.md
schemas/PSRule-language.schema.json
src/PSRule/Common/ArrayExtensions.cs
src/PSRule/Common/ExpressionHelpers.cs
src/PSRule/Common/StringExtensions.cs
src/PSRule/Definitions/Expressions/Functions.cs
tests/PSRule.Tests/FunctionTests.cs
tests/PSRule.Tests/Functions.Rule.jsonc
tests/PSRule.Tests/Functions.Rule.yaml
tests/PSRule.Tests/SelectorTests.cs
tests/PSRule.Tests/StringExtensionsTests.cs

- Added support for `trim`, `replace`, `split`, `first`, and `last` functions.
Fixes #1227

Added new function support #1227

---

docs/CHANGELOG-v2.md
src/PSRule/Runtime/ObjectPath/PathExpressionBuilder.cs
tests/PSRule.Tests/ObjectFromFile.json
tests/PSRule.Tests/PSRule.Common.Tests.ps1
tests/PSRule.Tests/PSRule.Tests.csproj
tests/PSRule.Tests/PathExpressionTests.cs

- Fixed object path fails to iterate JSON object with wildcard selector.
Fixes #1376 

Fixed object path wildcard selector #1376

---

docs/CHANGELOG-v2.md
docs/concepts/PSRule/en-US/about_PSRule_Assert.md
docs/concepts/PSRule/en-US/about_PSRule_Expressions.md
docs/concepts/PSRule/en-US/about_PSRule_Variables.md
schemas/PSRule-language.schema.json
src/PSRule/Common/DictionaryExtensions.cs
src/PSRule/Common/ExpressionHelpers.cs
src/PSRule/Common/HashtableExtensions.cs
src/PSRule/Common/PSObjectExtensions.cs
src/PSRule/Definitions/Expressions/LanguageExpressions.cs
src/PSRule/Pipeline/TargetObject.cs
src/PSRule/Runtime/Assert.cs
src/PSRule/Runtime/LanguageScope.cs
src/PSRule/Runtime/Operand.cs
src/PSRule/Runtime/PSRule.cs
src/PSRule/Runtime/PSRuleMemberInfo.cs
tests/PSRule.Tests/SelectorTests.cs
tests/PSRule.Tests/Selectors.Rule.jsonc
tests/PSRule.Tests/Selectors.Rule.yaml

- Added support for `hasValue` expression with `scope`.
- Return target object scope as an array.
- Improve support of string comparisons to support an array of strings.
Fixes #1382 
Fixes #1383 
Fixes #1384 

Improvements to scope and string #1382 #1383 #1384

---

docs/CHANGELOG-v2.md
src/PSRule/Definitions/Expressions/ExpressionContext.cs
src/PSRule/Definitions/Expressions/LanguageExpressions.cs
src/PSRule/Rules/RuleHelpInfo.cs
src/PSRule/Runtime/RunspaceContext.cs

- Fixed null reference for link property.
- Fixed reason are emitted for pre-condition sub-selectors.
Fixes #1393 
Fixes #1394 

Added fixes for link and sub-selectors #1393 #1394

---

docs/CHANGELOG-v2.md

What's changed since pre-release v2.6.0:
- Added API version date comparison assertion method and expression by @BernieWhite.
[#1356](https://github.com/microsoft/PSRule/issues/1356)
[#1227](https://github.com/microsoft/PSRule/issues/1227)
- Added support for `trim`, `replace`, `split`, `first`, and `last`.
- Added support target scope by @BernieWhite.
[#1350](https://github.com/microsoft/PSRule/issues/1350)
- Added support for `hasValue` expression with `scope` by @BernieWhite.
[#1382](https://github.com/microsoft/PSRule/issues/1382)
- Return target object scope as an array by @BernieWhite.
[#1383](https://github.com/microsoft/PSRule/issues/1383)
- Improve support of string comparisons to support …

Release v2.7.0

---

docs/CHANGELOG-v2.md

What's changed since pre-release v2.8.0-B0034:
- Engineering:
- Bump Newtonsoft.Json to v13.0.3.
[#1467](https://github.com/microsoft/PSRule/pull/1467)
- Bump Microsoft.CodeAnalysis.NetAnalyzers to v7.0.1.
[#1468](https://github.com/microsoft/PSRule/pull/1468)
- Bug fixes:
- Fixed problem binding when not set locally by @BernieWhite.
[#1473](https://github.com/microsoft/PSRule/issues/1473)

Pre-release v2.8.0-B0076

---

docs/CHANGELOG-v2.md
docs/troubleshooting.md
src/PSRule/Pipeline/Output/JobSummaryWriter.cs
src/PSRule/Pipeline/PipelineWriter.cs
src/PSRule/Resources/PSRuleResources.Designer.cs
src/PSRule/Resources/PSRuleResources.resx

- Fixed no output with using job summary with as summary.
- Fixed output and added error for unsupported scenarios.
Fixes #1483

Fixes no output with using job summary #1483

---

docs/CHANGELOG-v2.md
docs/concepts/PSRule/en-US/about_PSRule_Expressions.md
schemas/PSRule-language.schema.json
src/PSRule/Definitions/Expressions/LanguageExpressions.cs
tests/PSRule.Tests/SelectorTests.cs
tests/PSRule.Tests/Selectors.Rule.jsonc
tests/PSRule.Tests/Selectors.Rule.yaml

- Added support for case sensitivity matching with `match` and `notMatch` expressions.
Fixes #1480

Added case sensitive match #1480

---

docs/CHANGELOG-v2.md

What's changed since release v2.7.0:
- **Important change**: Replaced `SuppressedRuleWarning` execution option with `RuleSuppressed` by @BernieWhite.
[#1456](https://github.com/microsoft/PSRule/issues/1456)
- Improved options for output of suppressed rules with `RuleSuppressed` option.
- Deprecated `SuppressedRuleWarning` option, which will be removed in v3.
- Added support for logging excluded rules by @BernieWhite.
[#1432](https://github.com/microsoft/PSRule/issues/1432)
- Added additional options to schema for PSRule for Azure by @BernieWhite.
[#1446](https://github.com/microsoft/PSRule/issues/1446)
- Improved error message for failing to read options file by @BernieWhite.
[#1433](https://github.com/microsoft/PSRule/issues/1433)
- Added support for import within …

Release v2.8.0

---

README.md
docs/CHANGELOG-v2.md
docs/concepts/PSRule/en-US/about_PSRule_Options.md
docs/deprecations.md
schemas/PSRule-options.schema.json
src/PSRule/Common/RunspaceContextDiagnosticExtensions.cs
src/PSRule/Configuration/ExecutionOption.cs
src/PSRule/PSRule.psm1
src/PSRule/Pipeline/InvokeRulePipeline.cs
src/PSRule/Pipeline/PipelineWriterExtensions.cs
src/PSRule/Runtime/RunspaceContext.cs
tests/PSRule.Tests/PSRule.Common.Tests.ps1
tests/PSRule.Tests/PSRule.Options.Tests.ps1
tests/PSRule.Tests/PSRule.Reason.Tests.ps1
tests/PSRule.Tests/PSRule.Recommend.Tests.ps1
tests/PSRule.Tests/PSRule.Tests.yml
tests/PSRule.Tests/PSRule.Tests10.yml
tests/PSRule.Tests/PSRule.Tests11.yml
tests/PSRule.Tests/PSRule.Tests12.yml
tests/PSRule.Tests/PSRule.Tests13.yml
tests/PSRule.Tests/PSRule.Tests5.yml
tests/PSRule.Tests/PSRule.Tests9.yml
tests/PSRule.Tests/PipelineTests.cs

- **Important change**: Rename of execution options.
- Renamed options allow configuration of output level as `Ignore`, `Warn`, `Error`, or `Debug`.
- `Execution.AliasReferenceWarning` is replaced with `Execution.AliasReference`.
- `Execution.InconclusiveWarning` is replaced with `Execution.RuleInconclusive`.
- `Execution.InvariantCultureWarning` is replaced with `Execution.InvariantCulture`.
- `Execution.NotProcessedWarning` is replaced with `Execution.UnprocessedObject`.
- Deprecated `AliasReferenceWarning` option, which will be removed in v3.
- Deprecated `InconclusiveWarning` option, which will be removed in v3.
- Deprecated `InvariantCultureWarning` option, which will be removed in v3.
- Deprecated `NotProcessedWarning` option, which will be removed in v3.
Fixes #1456 
- **Code …

Rename and improvement of logging options #1456

---

docs/CHANGELOG-v2.md
docs/commands/PSRule/en-US/New-PSRuleOption.md
docs/commands/PSRule/en-US/Set-PSRuleOption.md

What's changed since release v2.8.1:
- **Important change**: Rename of execution options by @BernieWhite.
[#1456](https://github.com/microsoft/PSRule/issues/1456)
- Renamed options allow configuration of output level as `Ignore`, `Warn`, `Error`, or `Debug`.
- `Execution.AliasReferenceWarning` is replaced with `Execution.AliasReference`.
- `Execution.InconclusiveWarning` is replaced with `Execution.RuleInconclusive`.
- `Execution.InvariantCultureWarning` is replaced with `Execution.InvariantCulture`.
- `Execution.NotProcessedWarning` is replaced with `Execution.UnprocessedObject`.
- Deprecated `AliasReferenceWarning` option, which will be removed in v3.
- Deprecated `InconclusiveWarning` option, which will be removed in v3.
- Deprecated `InvariantCultureWarning` …

Pre-release v2.9.0-B0013

---

.vscode/settings.json
docs/CHANGELOG-v2.md
docs/concepts/PSRule/en-US/about_PSRule_Expressions.md
docs/expressions/functions.md
docs/expressions/sub-selectors.md
schemas/PSRule-language.schema.json
src/PSRule/Definitions/Expressions/LanguageExpressions.cs
tests/PSRule.Tests/FromFileSubSelector.Rule.jsonc
tests/PSRule.Tests/FromFileSubSelector.Rule.yaml
tests/PSRule.Tests/RulesTests.cs
tests/PSRule.Tests/SelectorTests.cs
tests/PSRule.Tests/Selectors.Rule.jsonc
tests/PSRule.Tests/Selectors.Rule.yaml

- Added sub-selector quantifiers for `allOf` or `anyOf` operators by @BernieWhite.
[#1423](https://github.com/microsoft/PSRule/issues/1423)
- Quantifiers allow you to specify the number of matches with `count`, `less`, `lessOrEqual`, `greater`, or `greaterOrEqual`.
- See [Sub-selectors][4] for more information.
[4]: expressions/sub-selectors.md
Fixes #1423

Added sub-selector quantifiers #1423

---

docs/CHANGELOG-v2.md
docs/expressions/functions.md
schemas/PSRule-language.schema.json
src/PSRule/Common/DictionaryExtensions.cs
src/PSRule/Definitions/Expressions/Functions.cs
tests/PSRule.Tests/FunctionTests.cs
tests/PSRule.Tests/Functions.Rule.jsonc
tests/PSRule.Tests/Functions.Rule.yaml
tests/PSRule.Tests/SelectorTests.cs

[#1422](https://github.com/microsoft/PSRule/issues/1422)
- Added support for `padLeft`, and `padRight`.
Fixes #1422 

Added padLeft and padRight functions #1422

---

docs/CHANGELOG-v2.md

What's changed since pre-release v2.9.0-B0033:
- **Experimental**: Added support for baseline groups by @BernieWhite.
[#1541](https://github.com/microsoft/PSRule/issues/1541)
- Baseline groups allow you to reference a baseline by a friendly name.
- Update the baseline group to point to a new baseline.
- Currently only a single baseline can be referenced by a baseline group.
- Added style and improved handling for restore command by @BernieWhite.
[#1152](https://github.com/microsoft/PSRule/issues/1152)
- Engineering:
- Bump Microsoft.NET.Test.Sdk to v17.6.2.
[#1544](https://github.com/microsoft/PSRule/pull/1544)
- Bump Microsoft.CodeAnalysis.Common to v4.6.0.
[#1534](https://github.com/microsoft/PSRule/pull/1534)
- Bug fixes:
- Fixed include local …

Pre-release v2.9.0-B0033

---

docs/CHANGELOG-v2.md

What's changed since release v2.8.1:
- Added sub-selector quantifiers for `allOf` or `anyOf` operators by @BernieWhite.
[#1423](https://github.com/microsoft/PSRule/issues/1423)
- Quantifiers allow you to specify the number of matches with `count`, `less`, `lessOrEqual`, `greater`, or `greaterOrEqual`.
[#1422](https://github.com/microsoft/PSRule/issues/1422)
- Added support for `padLeft`, and `padRight`.
- **Experimental**: Added support for baseline groups by @BernieWhite.
[#1541](https://github.com/microsoft/PSRule/issues/1541)
- Baseline groups allow you to reference a baseline by a friendly name.
- Update the baseline group to point to a new baseline.
- Currently only a single baseline can be referenced by a baseline …

Release v2.9.0

---

docs/CHANGELOG-v2.md
docs/concepts/PSRule/en-US/about_PSRule_Assert.md
src/PSRule/Runtime/Assert.cs

- Expanded support for `FileHeader` assertion.
Fixes #1521 

Expanded support for FileHeader assertion #1521

---

.vscode/settings.json
overrides/main.html

Add an announcement banner to let visitors know they are viewing the vNext version.

Add vNext announcement in docs

---

README.md
docs/CHANGELOG-v3.md
docs/concepts/PSRule/en-US/about_PSRule_Options.md
docs/upgrade-notes.md
schemas/PSRule-options.schema.json
src/PSRule.Tool/ClientHelper.cs
src/PSRule.Types/Options/ExecutionActionPreference.cs
src/PSRule.Types/Options/ExecutionOption.cs
src/PSRule.Types/Options/HashAlgorithm.cs
src/PSRule.Types/Options/LanguageMode.cs
src/PSRule.Types/Options/SessionState.cs
src/PSRule/Common/RunspaceContextDiagnosticExtensions.cs
src/PSRule/Configuration/PSRuleOption.cs
src/PSRule/Host/Host.cs
src/PSRule/PSRule.psm1
src/PSRule/Pipeline/GetRuleHelpPipeline.cs
src/PSRule/Pipeline/PipelineBuilder.cs
src/PSRule/Pipeline/PipelineContext.cs
src/PSRule/Pipeline/PipelineHookActions.cs
src/PSRule/Runtime/RunspaceContext.cs
tests/PSRule.Tests/PSRule.Common.Tests.ps1
tests/PSRule.Tests/PSRule.Options.Tests.ps1
tests/PSRule.Tests/PSRule.Tests.yml
tests/PSRule.Tests/PipelineTests.cs
tests/PSRule.Tests/TargetNameBindingTests.cs

- **Breaking change:** Switch to use SHA-512 for generating unbound objects by @BernieWhite.
- Objects that have no bound name will automatically be assigned a name based on the SHA-512 hash of the object.
- Previously a SHA-1 hash was used, however this is no longer considered secure.
- The name for unbound objects that are suppressed will change as a result.
- Additionally the hash can be changed by setting the `Execution.HashAlgorithm` option.
Fixes #1155 

Use SHA-512 for name generation #1155

---

.vscode/settings.json
docs/CHANGELOG-v3.md
docs/install-instructions.md
docs/upgrade-notes.md
pipeline.build.ps1
src/PSRule.Benchmark/PSRule.Benchmark.csproj
src/PSRule.Tool/PSRule.Tool.csproj
tests/PSRule.Tests/PSRule.Tests.csproj
tests/PSRule.Tool.Tests/PSRule.Tool.Tests.csproj

Updated development tooling for .NET 7 and bumped supported PowerShell version to 7.3.

Bump tooling to .NET 7 #1631

---

docs/CHANGELOG-v3.md

What's changed since release v2.9.0:
- Added lock file support when using CLI and related tools by @BernieWhite.
[#1660](https://github.com/microsoft/PSRule/issues/1660)
- The lock file used used during analysis and when installing modules to select a specific version.
- **Breaking change:** Switch to use SHA-512 for generating unbound objects by @BernieWhite.
[#1155](https://github.com/microsoft/PSRule/issues/1155)
- Objects that have no bound name will automatically be assigned a name based on the SHA-512 hash of the object.
- Previously a SHA-1 hash was used, however this is no longer considered secure.
- The name for unbound objects that are suppressed will change as a result.
- Additionally the hash can be changed by setting the …

Pre-release v3.0.0-B0084

---

.github/workflows/docs.yaml

Update docs deployment

---

docs/CHANGELOG-v3.md

What's changed since pre-release v3.0.0-B0084:
- Engineering:
- Bump xunit to v2.6.1.
[#1656](https://github.com/microsoft/PSRule/pull/1656)
- Bump System.Drawing.Common to v8.0.0.
[#1669](https://github.com/microsoft/PSRule/pull/1669)
- Bug fixes:
- Fixed CLI IndexOutOfRangeException with lock file by @BernieWhite.
[#1676](https://github.com/microsoft/PSRule/issues/1676)

Pre-release v3.0.0-B0093

---

docs/CHANGELOG-v3.md
docs/concepts/cli.md
src/PSRule.Tool/AnalyzerOptions.cs
src/PSRule.Tool/ClientBuilder.cs
src/PSRule.Tool/ClientHelper.cs
src/PSRule.Tool/Resources/CmdStrings.Designer.cs
src/PSRule.Tool/Resources/CmdStrings.resx
src/PSRule.Types/Data/SemanticVersion.cs
src/PSRule/Configuration/PSRuleOption.cs

- Added `--outcome` argument for CLI to support filtering output.
Fixes #1706

Added outcome argument for CLI #1706

---

docs/CHANGELOG-v3.md
docs/upgrade-notes.md

What's changed since pre-release v3.0.0-B0122:
- **Breaking change:** Moved the `restore` command to a sub-command of `module` by @BernieWhite.
[#1730](https://github.com/microsoft/PSRule/issues/1730)
- The functionality of the `restore` command is now available as `module restore`.
- Added CLI commands to list and report status of locked modules by @BernieWhite.
[#1729](https://github.com/microsoft/PSRule/issues/1729)
- Added `module init` sub-command to initialize the lock file from configured options.
- Added `module list` sub-command to list locked and unlocked modules associated with the workspace.
- Added `version` property to the lock file schema to support versioning of the lock file.
- Engineering:
- Bump BenchmarkDotNet to v0.13.12. …

Pre-release v3.0.0-B0137

---

docs/CHANGELOG-v3.md
src/PSRule/Common/ExpressionContextExtensions.cs
src/PSRule/Definitions/Expressions/ExpressionContext.cs
src/PSRule/Definitions/Expressions/ExpressionInfo.cs
src/PSRule/Definitions/Expressions/FunctionBuilder.cs
src/PSRule/Definitions/Expressions/FunctionDescriptor.cs
src/PSRule/Definitions/Expressions/FunctionFactory.cs
src/PSRule/Definitions/Expressions/FunctionReader.cs
src/PSRule/Definitions/Expressions/IExpressionContext.cs
src/PSRule/Definitions/Expressions/IFunctionDescriptor.cs
src/PSRule/Definitions/Expressions/LanguageExpressionBuilder.cs
src/PSRule/Definitions/Expressions/LanguageExpressionFactory.cs
src/PSRule/Definitions/Expressions/LanguageExpressionType.cs
src/PSRule/Definitions/Expressions/LanguageExpressions.cs
src/PSRule/Definitions/Expressions/Primitives.cs
src/PSRule/Properties/AssemblyInfo.cs
src/PSRule/Runtime/RunspaceContext.cs
tests/PSRule.Tests/Expressions/LanguageExpressionsTests.cs
tests/PSRule.Tests/PSRule.Tests.csproj
tests/PSRule.Tests/Usings.cs

- Fixed reason reported for `startsWith`.
Fixes #1818

Fixed reason reported for startsWith #1818

---

docs/CHANGELOG-v3.md

What's changed since pre-release v3.0.0-B0198:
- **Breaking change**: Simplify handling of inputs from files using emitters by @BernieWhite.
[#1179](https://github.com/microsoft/PSRule/issues/1179)
- Files are automatically read from input paths and emitted as objects to the pipeline.
- Emitter interface can be used to implement custom file readers and expansion of custom file types.
- The `File` and `Detect` input formats are no longer required and have been removed.
- Processing files and objects with rules is no longer recommended, and disabled by default.
- The `Input.FileObjects` can be set to `true` to enable processing of files as objects with rules.
- Engineering:
- Bump Microsoft.NET.Test.Sdk to v17.10.0.
[#1826](https://github.com/microsoft/PSRule/pull/1826)
- …

Pre-release v3.0.0-B0203

---

src/Directory.Build.props

- Exclude restore lock mode in GH actions for dependabot.

Update lock mode for Dependabot

---

docs/CHANGELOG-v3.md
docs/specs/emitter-spec.md
src/PSRule.Types/Runtime/ILoggerFactory.cs
src/PSRule.Types/Runtime/ILogger_TCategoryName.cs
src/PSRule.Types/Runtime/Logger_T.cs
src/PSRule.Types/Runtime/NullLogger.cs
src/PSRule.Types/Runtime/NullLogger_T.cs
src/PSRule/Commands/ExportConventionCommand.cs
src/PSRule/Common/LoggerExtensions.cs
src/PSRule/Pipeline/Emitters/EmitterBuilder.cs
src/PSRule/Pipeline/Emitters/JsonEmitter.cs
src/PSRule/Pipeline/Emitters/YamlEmitter.cs
src/PSRule/Resources/PSRuleResources.Designer.cs
src/PSRule/Resources/PSRuleResources.resx
src/PSRule/Runtime/LoggerFactory.cs
tests/PSRule.Tests/ConventionTests.cs
tests/PSRule.Tests/Emitters/JsonEmitterTests.cs
tests/PSRule.Tests/Emitters/YamlEmitterTests.cs

- Added support for native logging within emitters.
Fixes #1837

Add native logging for emitters #1837

---

src/PSRule.Types/Definitions/ResourceHelper.cs
src/PSRule.Types/Definitions/ResourceId.cs
src/PSRule/Commands/NewRuleDefinitionCommand.cs
src/PSRule/Definitions/ResourceValidator.cs
src/PSRule/Host/HostHelper.cs
src/PSRule/Pipeline/IPipelineReader.cs
src/PSRule/Pipeline/OptionContextBuilder.cs
src/PSRule/Pipeline/PipelineContext.cs
src/PSRule/Pipeline/ResourceIssue.cs
src/PSRule/Pipeline/ResourceIssueType.cs
src/PSRule/Pipeline/TargetBinder.cs
src/PSRule/Runtime/ILanguageScope.cs

Refactoring of context related to #1215.

Context refactoring

---

docs/CHANGELOG-v3.md
docs/commands/PSRule/en-US/New-PSRuleOption.md
docs/deprecations.md
src/PSRule/Configuration/PSRuleOption.cs
src/PSRule/Configuration/PipelineHook.cs
src/PSRule/PSRule.psm1
src/PSRule/Pipeline/AssertPipelineBuilder.cs
src/PSRule/Pipeline/ExportBaselinePipelineBuilder.cs
src/PSRule/Pipeline/GetBaselinePipelineBuilder.cs
src/PSRule/Pipeline/GetRuleHelpPipeline.cs
src/PSRule/Pipeline/GetRulePipelineBuilder.cs
src/PSRule/Pipeline/GetTargetPipelineBuilder.cs
src/PSRule/Pipeline/InvokePipelineBuilderBase.cs
src/PSRule/Pipeline/PipelineBuilderBase.cs
src/PSRule/Pipeline/PipelineHookActions.cs
src/PSRule/Pipeline/RulePipeline.cs
src/PSRule/Runtime/RunspaceContext.cs
tests/PSRule.Tests/PSRule.Common.Tests.ps1

- Pipeline refactoring, working towards #1215.

Minor pipeline refactor

---

docs/CHANGELOG-v3.md
src/PSRule/Runtime/Assert.cs
src/PSRule/Runtime/AssertResult.cs
tests/PSRule.Tests/AssertTests.cs

- Fixed aggregation of reasons with `$Assert.AnyOf()`.
Fixes #1829 

Fixed aggregation of reasons with $Assert.AnyOf() #1829

---

docs/CHANGELOG-v3.md
src/PSRule/PSRule.psm1

Fixes https://github.com/microsoft/PSRule/issues/2542
Added valid and documented value `Problem` to validate sets of the parameter `OutputOutcome` to three functions.

Add `Problem` to validate sets of `OutputOutcome`, fix #2542

---

docs/CHANGELOG-v3.md

What's changed since pre-release v3.0.0-B0203:
- Added option to configure the severity level that PSRule will break the pipeline at by @BernieWhite.
[#1508](https://github.com/microsoft/PSRule/issues/1508)
- Previously only rules with the severity level `Error` would break the pipeline.
- With this update rules with the severity level `Error` that fail will break the pipeline by default.
- The `Execution.Break` option can be set to `Never`, `OnError`, `OnWarning`, or `OnInformation`.
- If a rule fails with a severity level equal or higher than the configured level the pipeline will break.
- **Breaking change**: Improve scope handling for correctly handling cases with multiple module by @BernieWhite. …

Pre-release v3.0.0-B0267

---

docs/CHANGELOG-v3.md

What's changed since pre-release v3.0.0-B0267:
- Allow CLI upgrade command to upgrade a single module by @BernieWhite.
[#2551](https://github.com/microsoft/PSRule/issues/2551)
- A single or specific modules can be upgraded by name when using `module upgrade`.
- By default, all modules are upgraded.
- Allow CLI to install pre-release modules by @BernieWhite.
[#2550](https://github.com/microsoft/PSRule/issues/2550)
- Add and upgrade pre-release modules with `--prerelease`.
- Pre-release modules will be restored from the lock file with `module restore`.
- **Breaking change**: Empty version comparison only accepts stable versions by default by @BernieWhite.
[#2557](https://github.com/microsoft/PSRule/issues/2557)
- `version` and `apiVersion` assertions …

Pre-release v3.0.0-B0275

---

docs/CHANGELOG-v3.md
docs/concepts/cli/index.md
docs/concepts/cli/restore.md
docs/concepts/cli/run.md
src/PSRule.CommandLine/ClientHost.cs
src/PSRule.CommandLine/Commands/ModuleCommand.cs
src/PSRule.CommandLine/Commands/RunCommand.cs
src/PSRule.CommandLine/Models/RestoreOptions.cs
src/PSRule.CommandLine/Models/RunOptions.cs
src/PSRule.Tool/ClientBuilder.cs
src/PSRule.Tool/Resources/CmdStrings.Designer.cs
src/PSRule.Tool/Resources/CmdStrings.resx
src/PSRule.Types/Environment.cs
src/PSRule/Pipeline/SourcePipelineBuilder.cs

- Automatically restore missing modules when running CLI.
Fixes #2552

Allow CLI run to automatically restore missing modules #2552

---

docs/CHANGELOG-v3.md

What's changed since pre-release v3.0.0-B0275:
- Added support for overriding rule severity level by @BernieWhite.
[#1180](https://github.com/microsoft/PSRule/issues/1180)
- Baselines now accept a new `spec.overrides.level` property which configures severity level overrides.
- Options now accept a new `overrides.level` properties which configures severity level overrides.
- For example, a rule that generates an `Error` can be overridden to `Warning`.
- Automatically restore missing modules when running CLI by @BernieWhite.
[#2552](https://github.com/microsoft/PSRule/issues/2552)
- Modules are automatically restored unless `--no-restore` is used with the `run` command.
- Engineering:
- Bump YamlDotNet to v16.2.0. …

Pre-release v3.0.0-B0315

---

.vscode/settings.json
docs/CHANGELOG-v3.md
src/PSRule/Pipeline/InvokePipelineBuilderBase.cs
src/PSRule/Pipeline/PathBuilder.cs
src/PSRule/Pipeline/PathFilter.cs
src/PSRule/Pipeline/PathFilterBuilder.cs
tests/PSRule.Tests/PathFilterTests.cs

- Fixes path filtering of ignored files includes prefixed files.
Fixes #2624

Fixes path filtering #2624

---

.vscode/settings.json
docs/CHANGELOG-v3.md
docs/updates/v3_0.md
ps-rule-ci.yaml
src/PSRule.CommandLine/StringExtensions.cs
src/PSRule.EditorServices/ClientBuilder.cs
src/PSRule.Types/Environment.cs
src/code/commands/openOptionsFile.ts

- VSCode extension set to use Microsoft verified name.
- Added support for overriding options path from the default in VSCode.
- Migrated VSCode extension into PSRule repository.
Fixes #2636
Fixes #2635 
Fixes #2615

Updates for vscode #2636 #2635 #2615

---

package.json
src/vscode-ps-rule/README.md

Update vscode extension readme

---

docs/troubleshooting.md

Update troubleshooting docs to include exit codes for CLI and language server.

Add exit code to troubleshooting

---

docs/CHANGELOG-v3.md
mkdocs.yml

What's changed since pre-release v3.0.0-B0342:
- Added an integrity hash to lock file by @BernieWhite.
[#2664](https://github.com/microsoft/PSRule/issues/2664)
- The lock file now includes an integrity hash to ensures the restored module matches originally added module.

Pre-release v3.0.0-B0351

---

docs/CHANGELOG-v3.md
src/PSRule/Pipeline/Output/JsonOutputWriter.cs
src/PSRule/Pipeline/Output/YamlOutputWriter.cs
tests/PSRule.Tests/Pipeline/Output/JsonOutputWriterTests.cs
tests/PSRule.Tests/Pipeline/Output/YamlOutputWriterTests.cs

- Fixed JSON output format returns exception when no results are produced.
Fixes #1832

Fixed JSON output format returns exception when no results

---

docs/CHANGELOG-v3.md
docs/concepts/cli/run.md
src/PSRule.CommandLine/ClientContext.cs
src/PSRule.CommandLine/ClientHost.cs
src/PSRule.CommandLine/Commands/ModuleCommand.cs
src/PSRule.CommandLine/Commands/RunCommand.cs
src/PSRule.CommandLine/Models/RunOptions.cs
src/PSRule.CommandLine/StringExtensions.cs
src/PSRule.EditorServices/ClientBuilder.cs
src/PSRule.Tool/ClientBuilder.cs
src/PSRule.Types/Properties/AssemblyInfo.cs
src/PSRule/Pipeline/CommandLineBuilder.cs
tests/PSRule.CommandLine.Tests/Commands/BaseTests.cs
tests/PSRule.CommandLine.Tests/Commands/RunCommandTests.cs
tests/PSRule.CommandLine.Tests/GlobalUsings.cs

- Fixed CLI output format argument not working.
Fixes #2699

Fixed CLI output format argument not working #2699

---

docs/CHANGELOG-v3.md
package.json
src/PSRule.CommandLine/Commands/ModuleCommand.cs
src/PSRule.EditorServices/Commands/ListenCommand.cs
src/PSRule.EditorServices/Handlers/UpgradeDependencyCommandHandler.cs
src/PSRule.EditorServices/Handlers/UpgradeDependencyCommandHandlerInput.cs
src/PSRule.EditorServices/Handlers/UpgradeDependencyCommandHandlerOutput.cs
src/PSRule.EditorServices/Hosting/LspServer.cs
src/PSRule.EditorServices/Hosting/ServerLogger.cs
src/PSRule.Tool/packages.lock.json
src/PSRule.Types/Runtime/LoggerExtensions.cs
src/vscode-ps-rule/README.md
src/vscode-ps-rule/client.ts
src/vscode-ps-rule/commands/upgradeDependency.ts
src/vscode-ps-rule/configuration.ts
src/vscode-ps-rule/dependencyLens.ts
src/vscode-ps-rule/docLens.ts
src/vscode-ps-rule/extension.ts
src/vscode-ps-rule/test/suite/configuration.test.ts
tests/PSRule.EditorServices.Tests/LanguageServerTestContainer.cs
tests/PSRule.EditorServices.Tests/LspServerTests.cs
tests/PSRule.EditorServices.Tests/PSRule.EditorServices.Tests.csproj
tests/PSRule.EditorServices.Tests/Usings.cs

- Added support dependency management in VSCode/
- Code lens in `ps-rule.lock.json` allows you to upgrade all or specific modules to the latest version.
- The command `Upgrade dependency` allows you to upgrade all or specific modules to the latest version.
Fixes #2734

Added support dependency management in VSCode #2734

---

docs/CHANGELOG-v3.md

What's changed since pre-release v3.0.0-B0390:
- Added support dependency management in VSCode by @BernieWhite.
[#2734](https://github.com/microsoft/PSRule/issues/2734)
- Code lens in `ps-rule.lock.json` allows you to upgrade all or specific modules to the latest version.
- The command `Upgrade dependency` allows you to upgrade all or specific modules to the latest version.
- Added support for enabling/ disabling emitters by @BernieWhite.
[#2752](https://github.com/microsoft/PSRule/issues/2752)
- Emitters can be enabled or disabled by setting the `enabled` property on each format.
- Additionally, the `formats` parameter/ input can be set on the command-line and CI to enable emitters for a run.
- Added support for configuring replacement string for each format by …

Pre-release v3.0.0-B0416

---

docs/changelog.md

What's changed since pre-release v3.0.0-B0416:
- Engineering:
- Bump System.Drawing.Common to v9.0.3.
[#2808](https://github.com/microsoft/PSRule/pull/2808)
- Bump NuGet.Protocol to v6.13.2.
[#2788](https://github.com/microsoft/PSRule/pull/2788)
- Bump vscode engine to v1.98.0.
[#2796](https://github.com/microsoft/PSRule/pull/2796)
- Bug fixes:
- Fixed custom emitter loaded too late by @BernieWhite.
[#2775](https://github.com/microsoft/PSRule/issues/2775)
- Fixed changed files includes excluded paths by @BernieWhite.
[#1465](https://github.com/microsoft/PSRule/issues/1465)
- Fixed branch ref for working with changes files only examples by @BernieWhite.
[#2777](https://github.com/microsoft/PSRule/issues/2777)

Pre-release v3.0.0-B0453

---

docs/changelog.md
package.json
src/PSRule.CommandLine/Commands/RunCommand.cs
src/PSRule.CommandLine/Models/RunCommandOutput.cs
src/PSRule.CommandLine/Models/RunOptions.cs
src/PSRule.CommandLine/Models/SessionContext.cs
src/PSRule.EditorServices/ClientBuilder.cs
src/PSRule.EditorServices/Handlers/RunAnalysisCommandHandler.cs
src/PSRule.EditorServices/Handlers/RunAnalysisCommandHandlerInput.cs
src/PSRule.EditorServices/Handlers/RunAnalysisCommandHandlerOutput.cs
src/PSRule.EditorServices/Handlers/UpgradeDependencyCommandHandler.cs
src/PSRule.EditorServices/Hosting/LspServer.cs
src/PSRule.Tool/ClientBuilder.cs
src/vscode-ps-rule/README.md
src/vscode-ps-rule/client.ts
src/vscode-ps-rule/commands/runAnalysisForPath.ts
src/vscode-ps-rule/configuration.ts
src/vscode-ps-rule/extension.ts
src/vscode-ps-rule/features/scanQuickpick/scanQuickpick.ts
src/vscode-ps-rule/test/suite/configuration.test.ts
tests/PSRule.CommandLine.Tests/Commands/RunCommandTests.cs

- **Experimental**: Added support for target scanning in Visual Studio Code by @BernieWhite.
- To scan a single file, right-click on the file in explorer or an open editor tab and select `Run scan on path`.
- To scan a folder, right-click on the folder in explorer and select `Run scan on path`.
Fixes #2641

Added support for target scanning in VSCode #2641

---

docs/changelog.md
src/PSRule/Pipeline/SourcePipelineBuilder.cs
tests/PSRule.Tests/PSRule.Tests.csproj
tests/PSRule.Tests/SourcePipelineBuilderTests.cs
tests/PSRule.Tests/TestModule8/TestModule8.psd1

- Fixed module path not found with pre-release.
Fixes #2889

Fixed module path not found with pre-release #2889
